const methods = [
{id:1,level:1,levelName:"Core Instructional Methods",title:"Direct Instruction & Explicit Teaching",icon:"🎯",category:"Instruction",summary:"Teach essential knowledge clearly through explanation, modelling, guided practice, and independent performance.",purpose:"Help learners acquire new knowledge or skills without leaving them to guess what to do.",best:"New concepts, foundational skills, procedures, worked examples.",steps:["State a clear, measurable learning objective.","Check prerequisite knowledge and correct gaps.","Explain one important idea at a time using precise language.","Model a worked example while thinking aloud.","Guide practice with prompts and immediate correction.","Check independent performance and decide the next step."],example:"Grade 2 Mathematics: model 27 + 15 using place-value blocks, explain why 12 ones are regrouped as 1 ten and 2 ones, practise a similar example together, then ask pupils to solve a new problem independently.",script:"“Watch how I solve this. First, I look at the ones. Seven ones plus five ones equals twelve ones. I exchange ten ones for one ten. Now I can add the tens. Let’s try another one together.”",mistakes:["Explaining too long without checking understanding.","Showing steps without explaining why they work.","Moving to independent work before pupils are ready."],check:"Can each learner solve a suitable new example and explain the important step?",task:"Plan one objective, one prior-knowledge question, one worked example, two guided questions, and one independent assessment.",tags:["New learning","Modelling","Guided practice"]},
{id:2,level:1,levelName:"Core Instructional Methods",title:"Demonstration Method",icon:"🧩",category:"Instruction",summary:"Show a skill or procedure step by step, explain important decisions, then let learners practise.",purpose:"Make a process visible when verbal explanation alone is not enough.",best:"Pronunciation, calculations, experiments, drawing, practical procedures.",steps:["Explain what learners are about to learn.","Prepare materials and ensure everyone can see.","Perform the task at a manageable pace.","Explain the purpose of each important step.","Highlight likely errors and safety considerations.","Ask learners to reproduce the skill and give feedback."],example:"In Science, demonstrate how to measure water using a measuring cylinder. Show eye-level reading, careful pouring, and how to record the measurement.",script:"“First, watch where I place my eyes. I read the level at eye height. Now I will show the same step again. Who can explain what I did before trying it?”",mistakes:["Demonstrating too quickly.","Assuming watching means understanding.","Forgetting to let every learner practise."],check:"Can learners reproduce the skill and explain the key steps?",task:"Choose a practical skill and prepare a five-minute demonstration followed by pupil practice.",tags:["Practical skills","Think-aloud","Modelling"]},
{id:3,level:1,levelName:"Core Instructional Methods",title:"Question-and-Answer Method",icon:"❓",category:"Discussion & Thinking",summary:"Use carefully sequenced questions to reveal understanding, stimulate reasoning, and diagnose misconceptions.",purpose:"Find out how learners are thinking, not merely whether they can recall an answer.",best:"Checking comprehension, discussion, review, reasoning.",steps:["Prepare questions aligned to the objective.","Ask one clear question at a time.","Give thinking time before selecting respondents.","Invite responses from a broad range of learners.","Probe with “How do you know?” or “Can you show another way?”","Use the answers to decide whether to continue or reteach."],example:"Ask: “What is 20 a multiple of 5? How do you know? What pattern do you notice in multiples of 5? Can you create a question with the answer 40?”",script:"“I want everyone to think first. Do not call out yet. In a moment, I will ask you to explain not only your answer but also how you know it.”",mistakes:["Asking only the quickest pupils.","Accepting yes/no answers when explanation is needed.","Answering your own question too quickly."],check:"Can you identify the reasoning or misconception behind pupil responses?",task:"Write six questions: two recall, two understanding, and two application or reasoning questions.",tags:["Reasoning","Assessment","Participation"]},
{id:4,level:1,levelName:"Core Instructional Methods",title:"Discussion Method",icon:"💬",category:"Discussion & Thinking",summary:"Organize purposeful exchange of ideas, supported by reasoning, evidence, listening, and a clear conclusion.",purpose:"Develop communication, interpretation, and the ability to compare ideas respectfully.",best:"Reading comprehension, values education, open-ended problems, interpretation.",steps:["Present a meaningful question.","Give time for individual thinking.","Let pairs or small groups discuss.","Ask learners to support ideas with evidence or examples.","Invite comparison and respectful challenge.","Summarize accurate ideas and resolve misconceptions."],example:"In English, ask whether a story character was courageous. Pupils must identify an event from the text and explain how it supports their view.",script:"“You may disagree with an idea, but explain your reason respectfully. Which detail from the story supports your answer?”",mistakes:["Letting a few confident pupils dominate.","Allowing unsupported claims to stand.","Ending without a summary."],check:"Can pupils support a claim with evidence or reasoning?",task:"Prepare one open-ended question and three prompts that require learners to explain their reasoning.",tags:["Communication","Evidence","Critical thinking"]},
{id:5,level:1,levelName:"Core Instructional Methods",title:"Storytelling & Real-Life Examples",icon:"📖",category:"Instruction",summary:"Connect new concepts to familiar events, stories, and situations without losing the learning objective.",purpose:"Give unfamiliar ideas a meaningful context and a reason to matter.",best:"Word problems, vocabulary, social studies, values, concept introductions.",steps:["Identify the exact concept to teach.","Choose a short, accurate, familiar context.","Present the story or scenario.","Pause for prediction, calculation, or interpretation.","Connect responses to the formal concept.","Give a new example to check transfer."],example:"Mia has 18 tomato seedlings and classmates plant 16 more. Pupils represent the groups, solve 18 + 16, and create a similar story.",script:"“Imagine this happened in our school garden. What information do we know? What do we need to find? How could we show the two groups?”",mistakes:["Making the story entertaining but irrelevant.","Adding unnecessary details.","Letting a misleading analogy create misconceptions."],check:"Can learners apply the concept to a new context?",task:"Turn a textbook question into a familiar real-life scenario and add an independent follow-up question.",tags:["Context","Memory","Application"]},
{id:6,level:1,levelName:"Core Instructional Methods",title:"Learner-Centred Teaching",icon:"🌱",category:"Active Learning",summary:"Make learners’ thinking, needs, participation, and progress central while the teacher deliberately guides learning.",purpose:"Build ownership, independence, and active thinking.",best:"Exploration, application, problem-solving, discussion.",steps:["Check what learners already know.","Set a meaningful task with clear expectations.","Allow an initial attempt or exploration.","Observe strategies and difficulties.","Provide guidance or explanation when needed.","Consolidate the concept and assess individual learning."],example:"Give pupils fraction strips showing 1/2, 2/4, and 4/8. Ask what they notice, guide them to equivalent fractions, then check with a new example.",script:"“Before I explain, study these representations. What do you notice? What evidence helps you decide that they represent the same amount?”",mistakes:["Confusing learner-centred with no teacher guidance.","Expecting novices to discover everything alone.","Assessing only the group, not individuals."],check:"Can learners explain the concept and apply it with decreasing support?",task:"Design a lesson opening in which learners investigate a question before your formal explanation.",tags:["Independence","Exploration","Agency"]},
{id:7,level:2,levelName:"Active & Collaborative Learning",title:"Activity-Based Learning",icon:"🎲",category:"Active Learning",summary:"Use purposeful tasks, manipulatives, games, experiments, and practical exercises to develop and apply learning.",purpose:"Give learners meaningful opportunities to practise and experience a concept.",best:"Skills practice, sorting, hands-on concepts, review.",steps:["State the objective and success criteria.","Prepare materials and safety instructions.","Explain and model the task.","Give clear steps and time limits.","Observe the activity and note errors.","Debrief, connect to the concept, and assess individually."],example:"Pupils sort shape cards by a chosen property, explain their sorting rule, and individually classify new shapes.",script:"“Your task is to sort the cards by one rule. Be ready to explain the rule and show a card that belongs in each group.”",mistakes:["Choosing fun over learning purpose.","Giving unclear directions.","Skipping the individual learning check."],check:"Does the activity produce evidence of the target skill?",task:"Plan a ten-minute activity with one objective, short instructions, and one exit question.",tags:["Hands-on","Practice","Engagement"]},
{id:8,level:2,levelName:"Active & Collaborative Learning",title:"Cooperative Learning",icon:"🤝",category:"Active Learning",summary:"Structure group work around a shared goal, meaningful contributions, social skills, and individual accountability.",purpose:"Help pupils learn with and from peers while each remains responsible for learning.",best:"Collaborative problem-solving, classification, peer explanation, projects.",steps:["Set a shared task and success criteria.","Assign useful roles and explain them.","Ensure every pupil has a contribution.","Teach listening, turn-taking, and respectful disagreement.","Monitor the group and provide prompts.","Check each pupil’s understanding after the task."],example:"Groups classify safe classroom materials by observable properties. Members record evidence, discuss categories, and present; each pupil answers an individual question afterward.",script:"“Your group needs one shared answer, but everyone must understand it. The checker will ask each member to explain the reason before you present.”",mistakes:["One pupil doing all the work.","No individual accountability.","Roles that are decorative rather than useful."],check:"Can each pupil explain the group’s reasoning independently?",task:"Design a group task with a shared outcome, meaningful roles, and an individual assessment.",tags:["Teamwork","Accountability","Peer learning"]},
{id:9,level:2,levelName:"Active & Collaborative Learning",title:"Inquiry-Based Learning",icon:"🔎",category:"Active Learning",summary:"Start with a question, gather evidence through investigation, and develop an explanation supported by observations.",purpose:"Develop curiosity, scientific thinking, and evidence-based reasoning.",best:"Science, pattern discovery, investigation, comparison.",steps:["Pose a focused investigable question.","Ask pupils to make a prediction and explain why.","Plan a safe, fair investigation.","Observe, test, measure, or compare.","Record results clearly.","Draw a conclusion that matches the evidence and reflect."],example:"Ask which classroom objects are attracted to a magnet. Pupils predict, test safe objects under supervision, record results, and compare evidence with predictions.",script:"“A prediction is what you think may happen. Evidence is what you observe. We will compare them before deciding what the results tell us.”",mistakes:["Treating guesses as evidence.","Using an unclear question.","Drawing conclusions beyond the observations."],check:"Can pupils connect a conclusion to recorded evidence?",task:"Write an inquiry question, prediction prompt, simple results table, and conclusion question.",tags:["Investigation","Evidence","Science"]},
{id:10,level:2,levelName:"Active & Collaborative Learning",title:"Problem-Based Learning",icon:"🧠",category:"Active Learning",summary:"Use a meaningful problem as the starting point for identifying knowledge needs, developing solutions, and justifying decisions.",purpose:"Apply knowledge to unfamiliar situations and compare possible approaches.",best:"Multi-step problems, design decisions, applied mathematics.",steps:["Present an authentic problem.","Identify important information and constraints.","List what is known and what must be found out.","Develop and compare possible solutions.","Justify a solution using evidence or mathematics.","Evaluate the result and reflect on the strategy."],example:"There are 24 pupils. How can they be arranged into equal teams with no pupil left out? Pupils explore factors and represent possible team arrangements.",script:"“There may be several workable answers. What conditions must every solution satisfy? How can you prove your arrangement works?”",mistakes:["Choosing a problem beyond pupils’ prerequisite knowledge.","Giving away the solution too early.","Accepting answers without checking constraints."],check:"Can pupils justify why their solution meets the problem’s conditions?",task:"Design a realistic problem that requires pupils to apply a previously learned skill.",tags:["Problem solving","Application","Reasoning"]},
{id:11,level:2,levelName:"Active & Collaborative Learning",title:"Project-Based Learning",icon:"🛠️",category:"Active Learning",summary:"Guide learners through an extended investigation that results in a meaningful product, presentation, or proposed solution.",purpose:"Connect academic learning to sustained work, revision, and authentic application.",best:"Interdisciplinary units, design, research, extended investigations.",steps:["Set clear subject-specific learning objectives.","Present a meaningful driving question.","Define the product and success criteria.","Break work into milestones and teach required skills.","Give feedback and opportunities to revise.","Present results and assess both group product and individual learning."],example:"Pupils design a classroom garden, measure the area, prepare a labelled plan, estimate materials, and explain their choices.",script:"“The project is not only the final display. I will also assess your measurements, reasoning, progress, and what each of you can explain.”",mistakes:["Focusing on decoration instead of learning.","Unrealistic scope or deadlines.","Grading only the final product."],check:"Can each pupil demonstrate the intended subject knowledge and skills?",task:"Draft a mini-project with a driving question, three milestones, an individual task, and a simple rubric.",tags:["Extended learning","Creation","Interdisciplinary"]},
{id:12,level:2,levelName:"Active & Collaborative Learning",title:"Experiential Learning & Role-Play",icon:"🎭",category:"Active Learning",summary:"Use a meaningful experience or simulation, followed by reflection, concept-building, and application.",purpose:"Help pupils connect practice with reflection and transfer.",best:"Language practice, social situations, practical decisions, simulations.",steps:["Set a learning purpose and clear boundaries.","Let learners take part in a task or role-play.","Ask what happened and what choices were made.","Connect the experience to a principle or skill.","Repeat or apply the learning in a new situation."],example:"Run a classroom market where pupils practise polite requests, take turns as customer and shopkeeper, and calculate simple totals.",script:"“After the role-play, we will discuss which phrases were appropriate, which calculations worked, and what you would change next time.”",mistakes:["Treating role-play as entertainment only.","Skipping the reflection stage.","Pressuring pupils into public performance without alternatives."],check:"Can learners explain what the experience taught them and apply it again?",task:"Plan a short role-play with roles, target skills, debrief questions, and an alternative participation option.",tags:["Simulation","Reflection","Communication"]},
{id:13,level:3,levelName:"Understanding Individual Learners",title:"Differentiated Instruction",icon:"🪜",category:"Inclusive Practice",summary:"Adapt support, process, challenge, or ways to demonstrate learning while keeping meaningful objectives clear.",purpose:"Respond to differences in readiness, language, and support needs without permanently labelling pupils.",best:"Mixed-readiness classes, varied prior knowledge, targeted support and extension.",steps:["Define a shared essential objective.","Check readiness and identify specific gaps.","Plan scaffolds for pupils who need them.","Provide core tasks for the objective.","Offer meaningful extension to pupils ready for more.","Use evidence to regroup learners as their needs change."],example:"For two-digit addition, one group uses base-ten blocks, another draws representations, and a ready group solves word problems and compares strategies.",script:"“Everyone is working toward understanding regrouping. Some of us will use blocks, some will use drawings, and some will explain two different strategies.”",mistakes:["Permanent ability labels.","Giving extra work without purpose.","Assuming a diagnosis predicts exactly what support is needed."],check:"Are all pupils progressing toward the objective with appropriate support and challenge?",task:"Create supported, core, and extension versions of one activity.",tags:["Readiness","Scaffolding","Challenge"]},
{id:14,level:3,levelName:"Understanding Individual Learners",title:"Scaffolding & Gradual Release",icon:"🏗️",category:"Inclusive Practice",summary:"Provide temporary support, then reduce it as learners become more accurate and independent.",purpose:"Bridge the gap between what pupils can do now and what they can do independently.",best:"New skills, complex tasks, writing, calculations, reading strategies.",steps:["Model the skill and reasoning (I do).","Guide practice and use prompts (We do).","Let pupils practise with a partner when appropriate.","Provide individual practice (You do).","Check accuracy and explanation, not only completion.","Restore or reduce support according to evidence."],example:"Model a paragraph, write one with the class, give pupils an outline and sentence starters, then gradually remove those supports as they become capable writers.",script:"“I will show the first one. We will do the next together. Then you will try one, and I will check what support you still need.”",mistakes:["Removing support too early.","Keeping prompts after they are no longer needed.","Mistaking copying for independent mastery."],check:"Can pupils perform the skill accurately on a new task with less help?",task:"List three supports for a difficult task and explain how you will gradually remove each.",tags:["I do / We do / You do","Independence","Guidance"]},
{id:15,level:3,levelName:"Understanding Individual Learners",title:"Teaching Aids & Multisensory Resources",icon:"🧱",category:"Inclusive Practice",summary:"Use objects, pictures, models, sound, movement, and digital resources when they clarify the learning objective.",purpose:"Make relationships visible, tangible, or easier to practise.",best:"Abstract concepts, vocabulary, maps, diagrams, practical skills.",steps:["Identify the concept pupils must understand.","Choose a resource that accurately represents it.","Explain what pupils should notice.","Connect the resource to the formal concept.","Ask pupils to use or interpret it.","Check understanding without relying only on the resource."],example:"Use base-ten blocks to build 243, draw hundreds/tens/ones, and then write 243 in numerals.",script:"“Look at how the blocks, drawing, and written number represent the same quantity. Explain what each part stands for.”",mistakes:["Using attractive but irrelevant materials.","Allowing visuals to distract.","Using a model that misrepresents the concept."],check:"Can pupils explain the concept and represent it in another form?",task:"Plan a concrete resource, a visual representation, and an abstract example for one concept.",tags:["Visuals","Manipulatives","Representation"]},
{id:16,level:3,levelName:"Understanding Individual Learners",title:"Inclusive Teaching",icon:"♿",category:"Inclusive Practice",summary:"Remove unnecessary barriers so diverse learners can participate and demonstrate meaningful learning.",purpose:"Provide access, belonging, and appropriate challenge without assuming every learner needs the same adjustment.",best:"Mixed language backgrounds, disability-related supports, varied communication needs.",steps:["Identify the essential learning objective.","Consider language, sensory, attention, and access barriers.","Use concise instructions and visible task steps where helpful.","Offer appropriate ways to access content and respond.","Check whether the adjustment is effective.","Coordinate with families and school specialists when appropriate."],example:"In a senses lesson, provide labelled pictures, safe real objects, short instructions, and a recording sheet. Match the response mode to the skill being assessed.",script:"“You may show your observation by writing or pointing to the matching picture for this activity. Then we will practise the vocabulary together.”",mistakes:["Assuming a diagnosis tells you everything.","Lowering expectations unnecessarily.","Offering adjustments without checking their impact."],check:"Can each learner access the task and demonstrate the specific objective?",task:"Identify three barriers in a lesson and propose a practical adjustment for each.",tags:["Access","Participation","Universal design"]},
{id:17,level:3,levelName:"Understanding Individual Learners",title:"Mastery Learning & Targeted Reteaching",icon:"🏆",category:"Assessment & Feedback",summary:"Check essential objectives, provide corrective instruction for gaps, and offer another opportunity to demonstrate learning.",purpose:"Help pupils secure prerequisite skills before advancing to more complex learning.",best:"Foundational literacy and numeracy, essential procedures, cumulative concepts.",steps:["Define observable success criteria.","Teach and practise the skill.","Assess individual performance.","Analyze errors to locate the gap.","Reteach using a targeted strategy or representation.","Reassess with a suitable new task and extend learning when ready."],example:"If pupils identify characters but cannot infer motivation, model how to connect actions and dialogue to evidence before giving a new inference question.",script:"“This answer shows what you already understand. Our next step is to work on the part that is not secure yet. Then you will try a new example.”",mistakes:["Repeating the same worksheet without addressing the cause.","Treating one correct answer as mastery.","Holding all learners to the same pace regardless of evidence."],check:"Can the pupil demonstrate the skill consistently on a suitable new task?",task:"Define mastery criteria, a short assessment, a targeted reteaching activity, and a follow-up assessment.",tags:["Reteaching","Progress","Mastery"]},
{id:18,level:4,levelName:"Assessment & Learning Retention",title:"Formative Assessment",icon:"📋",category:"Assessment & Feedback",summary:"Gather and use evidence during learning to decide whether to continue, clarify, reteach, or extend.",purpose:"Make instructional decisions based on what pupils actually understand.",best:"All subjects and stages of a lesson.",steps:["Choose evidence that matches the objective.","Use responses, mini-whiteboards, observations, quizzes, or exit tickets.","Look for patterns and misconceptions.","Decide the next instructional step.","Give learners an opportunity to respond to feedback.","Check again after any reteaching."],example:"After teaching 38 + 27, ask pupils to solve it independently and explain the regrouping. Use the errors to decide whether to reteach place value or the written procedure.",script:"“This question helps me see what we need next. It is not about catching you out; it is about finding the step we need to practise.”",mistakes:["Collecting scores without acting on them.","Relying only on volunteers.","Using questions that do not measure the objective."],check:"Can the evidence tell you what to teach next?",task:"Create a two-question exit ticket and write what you will do for different patterns of responses.",tags:["Checks for understanding","Exit ticket","Responsive teaching"]},
{id:19,level:4,levelName:"Assessment & Learning Retention",title:"Constructive Feedback",icon:"🗣️",category:"Assessment & Feedback",summary:"Give specific, actionable information about success, the gap, and the next step, then let learners use it.",purpose:"Help pupils improve rather than merely learn whether an answer was marked correct.",best:"Written work, oral answers, procedures, drafts, problem-solving.",steps:["Name something done correctly.","Identify one specific error or gap.","Give a useful prompt or next step.","Let the learner revise or try again.","Check whether the feedback improved performance."],example:"For 46 + 18 = 54, say: “You began with the correct columns. Six plus eight is fourteen ones. What should happen to those fourteen ones before you finish?”",script:"“You have correctly identified the information. Now check the operation you chose. Which clue in the problem helps you decide?”",mistakes:["Vague praise only.","Correcting too many issues at once.","Giving the answer before the pupil can revise."],check:"Does the learner use the feedback to improve a new attempt?",task:"Write feedback for three common errors that guides pupils toward correction.",tags:["Actionable feedback","Revision","Growth"]},
{id:20,level:4,levelName:"Assessment & Learning Retention",title:"Retrieval Practice & Spaced Review",icon:"🧠",category:"Assessment & Feedback",summary:"Ask learners to recall knowledge from memory and revisit important concepts over time.",purpose:"Strengthen long-term retention and expose knowledge gaps that rereading can hide.",best:"Facts, vocabulary, procedures, cumulative mathematics, previously taught concepts.",steps:["Choose important prior learning.","Ask pupils to recall without immediately showing the answer.","Use low-stakes questions or short quizzes.","Correct misunderstandings promptly.","Revisit concepts across later lessons.","Mix old and new learning where appropriate."],example:"Start mathematics lessons with a few questions from earlier topics, then return to those skills later in the week.",script:"“Try to remember first. It is fine if you are unsure; your response helps us identify what we should review.”",mistakes:["Reviewing only the most recent lesson.","Testing without correction.","Treating recall as proof of transfer to every new situation."],check:"Can pupils retrieve and apply important knowledge after time has passed?",task:"Plan five short retrieval questions that revisit earlier learning.",tags:["Memory","Review","Retention"]},
{id:21,level:4,levelName:"Assessment & Learning Retention",title:"Metacognition & Self-Regulated Learning",icon:"🪞",category:"Assessment & Feedback",summary:"Teach learners to plan a strategy, monitor whether it works, and evaluate their progress.",purpose:"Build independent learners who can recognize and address their own difficulties.",best:"Problem-solving, writing, reading comprehension, study skills.",steps:["Plan: clarify the task and choose a strategy.","Model self-questioning aloud.","Monitor: pause and check whether the strategy works.","Identify and correct mistakes.","Evaluate: compare performance with the success criteria.","Choose a next step for improvement."],example:"For a word problem, pupils identify what is known, what must be found, which strategy fits, and how they can check their answer.",script:"“Pause and ask yourself: Does this answer make sense? What evidence tells me my strategy is working?”",mistakes:["Asking only “What did you learn?”","Expecting self-monitoring without modelling it.","Treating reflection as a substitute for subject teaching."],check:"Can pupils select, monitor, and explain a strategy more independently?",task:"Create a five-question self-check checklist for one learning objective.",tags:["Self-monitoring","Strategy","Independence"]},
{id:22,level:4,levelName:"Assessment & Learning Retention",title:"Error Analysis & Reflection",icon:"🔁",category:"Assessment & Feedback",summary:"Examine plausible mistakes, identify their causes, correct the reasoning, and apply the correction to a new task.",purpose:"Develop deeper understanding by making misconceptions visible and discussable.",best:"Common mathematical errors, grammar, scientific reasoning, worked examples.",steps:["Present a realistic incorrect answer.","Ask learners to identify what is wrong.","Discuss why the error may have happened.","Correct the process and explain why.","Try a new example to test transfer."],example:"Show 28 + 17 = 35. Pupils identify that 8 + 7 makes 15 ones, which must be regrouped, giving the correct answer 45.",script:"“Let us examine the thinking, not blame the person. Which step caused the answer to change, and how can we repair it?”",mistakes:["Shaming the learner who made the error.","Correcting without exploring the cause.","Assuming pupils can transfer the correction automatically."],check:"Can pupils explain the error and avoid it in a new problem?",task:"Prepare one plausible incorrect solution and questions that guide learners to diagnose it.",tags:["Misconceptions","Reasoning","Reflection"]},
{id:23,level:5,levelName:"Classroom Leadership & Growth",title:"Classroom Management",icon:"🏫",category:"Classroom Leadership",summary:"Teach routines, set clear expectations, sustain engagement, and respond to behaviour calmly and consistently.",purpose:"Create a safe, respectful environment in which learning can happen.",best:"Every classroom and every lesson.",steps:["Teach a small set of clear, positive expectations.","Model and practise routines for transitions and materials.","Plan active, appropriately challenging learning.","Notice and reinforce specific positive behaviour.","Respond to difficulties calmly and consistently.","Investigate repeated patterns and seek support when needed."],example:"When pupils talk during an explanation, pause, use the established attention signal, wait, restate the expectation, and check that the next task is clear.",script:"“Pause, eyes this way. Thank you for getting ready. The next direction has two steps; listen first, then begin when I say go.”",mistakes:["Relying on shouting or humiliation.","Announcing routines without practising them.","Ignoring repeated triggers or learning barriers."],check:"Do routines support safe transitions, participation, and time spent learning?",task:"Write expectations and plan routines for entry, group work, transitions, and dismissal.",tags:["Routines","Behaviour","Relationships"]},
{id:24,level:5,levelName:"Classroom Leadership & Growth",title:"Lesson Planning & Alignment",icon:"🗓️",category:"Classroom Leadership",summary:"Align learning objectives, instructional activities, practice, and assessment so every part of a lesson serves the learning goal.",purpose:"Turn a list of activities into a coherent route toward measurable learning.",best:"Lesson preparation, unit planning, remediation, assessment design.",steps:["Identify the curriculum objective and prerequisite knowledge.","Define observable success criteria.","Choose methods and resources appropriate to the objective.","Plan modelling, guided practice, and independent application.","Anticipate likely misconceptions and support needs.","Plan evidence of learning and what to do with the results."],example:"If the objective is to explain regrouping, include a concrete model, a drawing or place-value representation, written practice, and an assessment requiring an explanation.",script:"“What must pupils be able to do by the end? Which activity prepares them for it, and what evidence will show that they can do it?”",mistakes:["Planning activities before defining the objective.","Assessing recall when the objective requires application.","Continuing the plan despite clear evidence of misunderstanding."],check:"Does the assessment directly measure the stated objective?",task:"Write one measurable objective, two misconceptions, aligned activities, and a matching assessment.",tags:["Objectives","Alignment","Preparation"]},
{id:25,level:5,levelName:"Classroom Leadership & Growth",title:"Reflective Teaching & Professional Growth",icon:"📈",category:"Classroom Leadership",summary:"Use pupil work and lesson evidence to identify successes, diagnose difficulties, and test deliberate improvements.",purpose:"Improve teaching through evidence rather than habit or impressions alone.",best:"After lessons, during planning, peer observation, professional development.",steps:["Restate the intended learning objective.","Review pupil responses and work samples.","Identify what supported learning and what remained difficult.","Choose one specific change to test.","Apply the change in a later lesson.","Compare evidence over time and refine the approach."],example:"Pupils can use blocks for addition but struggle with the written algorithm. Plan the next lesson to explicitly connect blocks, drawings, and written notation.",script:"“What evidence shows that learning happened? Which pupils still need support? What one change can I test next lesson?”",mistakes:["Judging success only by enjoyment or quietness.","Changing too many variables at once.","Treating one lesson as proof a method always works or never works."],check:"Can you identify a specific change and later evaluate its effect on learning?",task:"Complete a five-question reflection after your next lesson and choose one improvement to test.",tags:["Reflection","Evidence","Professional growth"]}
];

const levels = [
{name:"Core Instructional Methods",short:"Core instruction",range:[1,6],desc:"Explain, model, question, and guide."},
{name:"Active & Collaborative Learning",short:"Active learning",range:[7,12],desc:"Learn by doing, investigating, and collaborating."},
{name:"Understanding Individual Learners",short:"Inclusive practice",range:[13,17],desc:"Adapt support and build independence."},
{name:"Assessment & Learning Retention",short:"Assessment",range:[18,22],desc:"Check learning, give feedback, and strengthen memory."},
{name:"Classroom Leadership & Growth",short:"Leadership",range:[23,25],desc:"Manage routines, plan coherently, and improve."}
];
const scenarios = [
{q:"Several pupils are confused by a new mathematics procedure. What is the strongest next step?",opts:["Give a longer worksheet and move on","Model the procedure, guide practice, and check individual understanding","Ask pupils to discover the entire procedure without support"],answer:1,why:"New procedures often require explicit modelling, guided practice, and checks for understanding before independent work."},
{q:"A Science class is investigating which objects a magnet attracts. Which approach fits best?",opts:["Inquiry-based learning with safe testing and recorded evidence","A debate with no observations","Memorizing the conclusion before testing"],answer:0,why:"Inquiry lets pupils make predictions, investigate, record observations, and build conclusions from evidence."},
{q:"One pupil does all the work in every group activity. What should you improve?",opts:["Make groups larger","Remove group activities permanently","Structure roles and shared goals, then assess each pupil individually"],answer:2,why:"Cooperative learning needs meaningful contributions and individual accountability."},
{q:"Most pupils make the same error on an exit ticket. What should you do?",opts:["Analyze the misconception and adjust instruction","Ignore it because the lesson is finished","Give the class a harder test"],answer:0,why:"Formative assessment is useful when it changes the next instructional step."},
{q:"A pupil can solve a task with prompts but not alone. What does this suggest?",opts:["The pupil has mastered it completely","The pupil may need more guided practice and gradually reduced support","The pupil should never receive support again"],answer:1,why:"Scaffolding is temporary. Reduce support as evidence of independent performance improves."},
{q:"How can you tell whether a lesson was effective?",opts:["The teacher finished every slide","The room was silent","Pupils can demonstrate the objective and apply learning appropriately"],answer:2,why:"Evidence of what learners can do is more meaningful than lesson completion or silence alone."}
];

const tips = [
"Before a lesson, predict the two most likely misconceptions. Plan how you will spot and address them.",
"Ask a question, then give pupils quiet thinking time. A pause often improves the quality and range of responses.",
"After modelling, show a second example and ask pupils to explain the steps before they try one.",
"Use an exit ticket that directly measures the objective. Decide in advance what different responses will mean for your next lesson.",
"During group work, assign a shared goal but check each learner's understanding independently.",
"Replace “Do you understand?” with a task that makes understanding visible.",
"Do not confuse activity with learning. After a game or project, ask pupils to explain the concept it was designed to teach.",
"Give feedback that identifies one specific success and one actionable next step.",
"Revisit important knowledge over time instead of reviewing only the latest topic.",
"Treat a wrong answer as information about thinking. Find the misconception before choosing the correction."
];

const STORAGE_KEY = "teacherEdMethodsMasterclass_v1";
let state = {completed:[],theme:"light",plans:[],lastMethod:1};
let activeScenario = 0;
let scenarioAnswered = false;
let toastTimer;
const $ = id => document.getElementById(id);
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");state={...state,...saved};}catch(e){}}
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$("saveStatus").textContent="Progress saved on this device";}catch(e){$("saveStatus").textContent="Progress is temporary in this browser";}}
function showToast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2400);}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function renderLevels(){
 $("levelFilter").innerHTML='<option value="all">All learning levels</option>'+levels.map((l,i)=>`<option value="${i+1}">Level ${i+1}: ${l.short}</option>`).join("");
 $("categoryFilter").innerHTML='<option value="all">All method types</option>'+[...new Set(methods.map(m=>m.category))].map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join("");
 $("methodPlanSelect").innerHTML='<option value="">Choose a method</option>'+methods.map(m=>`<option value="${m.id}">${m.id}. ${escapeHtml(m.title)}</option>`).join("");
 $("levelMiniGrid").innerHTML=levels.map((l,i)=>{const items=methods.filter(m=>m.level===i+1);const done=items.filter(m=>state.completed.includes(m.id)).length;return `<div class="level-mini"><strong>${done}/${items.length}</strong><span>${escapeHtml(l.short)}</span></div>`}).join("");
}
function updateProgress(){
 const n=state.completed.length,pct=Math.round(n/methods.length*100);
 $("progressRing").textContent=pct+"%";$("progressFill").style.width=pct+"%";$("progressText").textContent=`${n} of ${methods.length} methods completed`;$("heroProgress").textContent=pct+"%";
 renderLevels();
}
function renderMethods(){
 const q=$("searchInput").value.trim().toLowerCase(),level=$("levelFilter").value,category=$("categoryFilter").value,status=$("statusFilter").value;
 const filtered=methods.filter(m=>{
 const text=[m.title,m.summary,m.purpose,m.best,m.category,m.levelName,...m.tags].join(" ").toLowerCase();
 return (!q||text.includes(q))&&(level==="all"||m.level===Number(level))&&(category==="all"||m.category===category)&&(status==="all"||(status==="completed"?state.completed.includes(m.id):!state.completed.includes(m.id)));
 });
 $("resultsCount").textContent=`${filtered.length} method${filtered.length===1?"":"s"}`;
 $("emptyState").classList.toggle("hidden",filtered.length>0);
 $("methodGrid").innerHTML=filtered.map(m=>`<article class="method-card" tabindex="0" role="button" aria-label="Open lesson ${m.id}: ${escapeHtml(m.title)}" data-id="${m.id}">
 <div class="card-top"><span class="method-icon">${m.icon}</span>${state.completed.includes(m.id)?'<span class="done-mark">✓ COMPLETE</span>':`<span class="method-number">METHOD ${String(m.id).padStart(2,"0")}</span>`}</div>
 <h3>${escapeHtml(m.title)}</h3><p>${escapeHtml(m.summary)}</p><div class="card-tags"><span class="tag">Level ${m.level}</span><span class="tag">${escapeHtml(m.category)}</span></div><div class="card-link"><span>${state.completed.includes(m.id)?"Review lesson":"Explore lesson"}</span><span>↗</span></div></article>`).join("");
 $("methodGrid").querySelectorAll(".method-card").forEach(card=>{
 const open=()=>openLesson(Number(card.dataset.id));
 card.addEventListener("click",open);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open();}});
 });
}
function openLesson(id){
 const m=methods.find(x=>x.id===id);if(!m)return;state.lastMethod=id;saveState();
 $("dialogLevel").textContent=`LEVEL ${m.level} · METHOD ${String(m.id).padStart(2,"0")} · ${m.levelName.toUpperCase()}`;
 const list=arr=>`<ul>${arr.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul>`;
 $("dialogContent").innerHTML=`<span class="eyebrow">${escapeHtml(m.category)}</span><h2>${m.icon} ${escapeHtml(m.title)}</h2><p class="lesson-purpose">${escapeHtml(m.summary)}</p>
 <div class="lesson-callout"><strong>Why use this method?</strong>${escapeHtml(m.purpose)}<br><br><strong>Especially useful for</strong>${escapeHtml(m.best)}</div>
 <h3>How to use it in your classroom</h3>${list(m.steps)}
 <h3>Classroom example</h3><p>${escapeHtml(m.example)}</p>
 <h3>What you can say</h3><div class="lesson-callout">${escapeHtml(m.script)}</div>
 <h3>Common mistakes to avoid</h3>${list(m.mistakes)}
 <h3>How to check learning</h3><p>${escapeHtml(m.check)}</p>
 <h3>Your practice task</h3><p>${escapeHtml(m.task)}</p>
 <div class="lesson-actions"><button class="button button-gold" id="completeMethodBtn">${state.completed.includes(m.id)?"✓ Marked complete — undo":"Mark method complete ✓"}</button><button class="button button-ghost" id="prevMethodBtn">← Previous</button><button class="button button-ghost" id="nextMethodBtn">Next method →</button></div>`;
 $("completeMethodBtn").addEventListener("click",()=>{if(state.completed.includes(m.id)){state.completed=state.completed.filter(x=>x!==m.id);}else{state.completed.push(m.id);}saveState();updateProgress();renderMethods();openLesson(id);showToast(state.completed.includes(m.id)?"Method marked complete!":"Completion status removed.");});
 $("prevMethodBtn").addEventListener("click",()=>openLesson(Math.max(1,id-1)));
 $("nextMethodBtn").addEventListener("click",()=>openLesson(Math.min(25,id+1)));
 const dlg=$("lessonDialog");if(!dlg.open)dlg.showModal();
}
function renderScenario(){
 const s=scenarios[activeScenario];scenarioAnswered=false;
 $("scenarioNumber").textContent=`SCENARIO ${activeScenario+1} / ${scenarios.length}`;
 $("scenarioQuestion").textContent=s.q;$("scenarioFeedback").textContent="";
 $("scenarioOptions").innerHTML=s.opts.map((o,i)=>`<button class="scenario-option" data-answer="${i}"><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${escapeHtml(o)}</span></button>`).join("");
 $("scenarioOptions").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>answerScenario(Number(b.dataset.answer))));
 $("nextScenario").textContent=activeScenario===scenarios.length-1?"Start again ↻":"Next scenario →";
}
function answerScenario(choice){
 if(scenarioAnswered)return;scenarioAnswered=true;const s=scenarios[activeScenario];
 $("scenarioOptions").querySelectorAll("button").forEach((b,i)=>{b.disabled=true;if(i===s.answer)b.classList.add("correct");else if(i===choice)b.classList.add("incorrect");});
 $("scenarioFeedback").textContent=(choice===s.answer?"Correct. ":"Not quite. ")+s.why;
}
function setTheme(theme){state.theme=theme;document.body.classList.toggle("dark",theme==="dark");$("themeToggle").textContent=theme==="dark"?"☾":"☼";saveState();}
function init(){
 loadState();setTheme(state.theme||"light");renderLevels();updateProgress();renderMethods();renderScenario();
 $("searchInput").addEventListener("input",renderMethods);["levelFilter","categoryFilter","statusFilter"].forEach(id=>$(id).addEventListener("change",renderMethods));
 $("clearFilters").addEventListener("click",()=>{$("searchInput").value="";$("levelFilter").value="all";$("categoryFilter").value="all";$("statusFilter").value="all";renderMethods();});
 $("gridViewBtn").addEventListener("click",()=>{$("methodGrid").classList.remove("list-view");$("gridViewBtn").classList.add("active");$("listViewBtn").classList.remove("active");});
 $("listViewBtn").addEventListener("click",()=>{$("methodGrid").classList.add("list-view");$("listViewBtn").classList.add("active");$("gridViewBtn").classList.remove("active");});
 $("continueBtn").addEventListener("click",()=>{const next=methods.find(m=>!state.completed.includes(m.id))||methods[0];openLesson(next.id);});
 $("quizHeroBtn").addEventListener("click",()=>document.querySelector(".practice-section").scrollIntoView({behavior:"smooth"}));
 $("themeToggle").addEventListener("click",()=>setTheme(state.theme==="dark"?"light":"dark"));
 $("closeDialog").addEventListener("click",()=>$("lessonDialog").close());
 $("lessonDialog").addEventListener("click",e=>{if(e.target===$("lessonDialog"))$("lessonDialog").close();});
 $("dailyTipBtn").addEventListener("click",()=>{$("tipOutput").textContent=tips[Math.floor(Math.random()*tips.length)];});
 $("scenarioReset").addEventListener("click",renderScenario);
 $("nextScenario").addEventListener("click",()=>{activeScenario=(activeScenario+1)%scenarios.length;renderScenario();});
 $("resetProgress").addEventListener("click",()=>{if(confirm("Reset completion progress for all 25 methods? Your saved teaching plans will remain.")){state.completed=[];saveState();updateProgress();renderMethods();showToast("Learning progress reset.");}});
 $("reflectionForm").addEventListener("submit",e=>{e.preventDefault();const plan={topic:$("lessonTopic").value.trim(),methodId:Number($("methodPlanSelect").value),evidence:$("successEvidence").value.trim(),date:new Date().toLocaleDateString()};state.plans.unshift(plan);saveState();$("planMessage").textContent="Teaching plan saved on this device.";showToast("Your teaching plan has been saved.");});
 $("printBtn").addEventListener("click",()=>window.print());
 if(state.plans.length){const p=state.plans[0];$("planMessage").textContent=`Last saved plan: ${p.topic} (${p.date}).`;}
}
document.addEventListener("DOMContentLoaded",init);
