const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='edjay_ap1_aralin11_v2';
const defaultState={points:0,stars:0,badges:0,streak:0,bestStreak:0,completed:[],missed:[],mastery:null,sound:true};
let state=load(); let sound=state.sound; let audioCtx=null;
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaultState}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateHome()}
function updateHome(){const p=Math.min(100,Math.round(state.points/90*100)); $('#homeProgress').textContent=p+'%';$('#homeBar').style.width=p+'%';$('#homeStars').textContent=state.stars;$('#homeBadges').textContent=state.badges;$('#homeStreak').textContent=state.streak}
function go(id){$$('.screen').forEach(x=>x.classList.remove('active'));const el=$('#'+id);if(el){el.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}updateHome()}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
$('#soundBtn').addEventListener('click',()=>{sound=!sound;state.sound=sound;save();$('#soundBtn').textContent=sound?'🔊':'🔇';toast(sound?'Tunog: ON':'Tunog: OFF')});
$('#soundBtn').textContent=sound?'🔊':'🔇';
function beep(ok=true){if(!sound)return;try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=ok?660:220;o.type='sine';g.gain.setValueAtTime(.001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.08,audioCtx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.16);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.17)}catch{}}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1800)}
function celebrate(){const box=$('#celebrate');box.innerHTML='';for(let i=0;i<34;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'%';c.style.animationDelay=Math.random()*.4+'s';c.style.transform=`rotate(${Math.random()*360}deg)`;box.appendChild(c)}setTimeout(()=>box.innerHTML='',1900)}
function reward(){state.points+=5;state.stars++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);if(state.streak>=3&&state.badges<1)state.badges=1;if(state.stars>=8&&state.badges<2)state.badges=2;save();beep(true);celebrate()}
function miss(label){state.streak=0;if(!state.missed.includes(label))state.missed.push(label);save();beep(false)}
const connectOpts=[['🧹','Tumulong maglinis ng bahay',true],['🎮','Maglaro buong araw',false],['🛏️','Iwanang magulo ang gamit',false]];
function initConnect(){const box=$('#connectChoices');box.innerHTML=connectOpts.map((o,i)=>`<button class="choice" data-c="${i}">${o[0]} ${o[1]}</button>`).join('');$$('[data-c]').forEach(b=>b.onclick=()=>{const o=connectOpts[+b.dataset.c];if(o[2]){b.classList.add('correct');$('#connectFeedback').className='feedback good';$('#connectFeedback').textContent='⭐ Tama! Ang pagtulong sa bahay ay isang mabuting tungkulin.';reward();$('#connectNext').classList.remove('hidden')}else{b.classList.add('wrong');$('#connectFeedback').className='feedback help';$('#connectFeedback').textContent='💡 Pag-isipan: Aling kilos ang nakatutulong sa pamilya?';miss('Connect: mabuting gawain')}})}
const guidedQ=[{q:'Nakikipag-usap ka kay Tatay. Alin ang magalang?',a:['“Opo, Tatay.”','“Hoy, Tatay!”','“Ayoko!”'],c:0,h:'Gamitin ang magalang na salita.'},{q:'Lalabas ka ng bahay. Ano ang dapat mong gawin?',a:['Magpaalam kina Nanay at Tatay.','Lumabas agad.','Magtago.'],c:0,h:'Sabihin muna sa magulang bago lumabas.'},{q:'May kapatid kang maliit. Ano ang mabuting gawin?',a:['Alagaan at igalang siya.','Asarin siya.','Iwan siyang mag-isa.'],c:0,h:'Ang kapatid ay dapat alagaan at igalang.'}];
const independentQ=[{q:'May takdang-aralin ka at gusto mong maglaro. Ano ang uunahin?',a:['Takdang-aralin','Laro','Pagtulog'],c:0,h:'Tapusin muna ang gawain bago maglaro.'},{q:'Saan ilalagay ang damit pagkatapos gamitin?',a:['Sa wastong lagayan.','Sa sahig.','Sa mesa.'],c:0,h:'Panatilihing maayos ang mga gamit.'},{q:'Sabado at may gawaing-bahay. Ano ang dapat mong gawin?',a:['Tumulong sa abot ng makakaya.','Maglaro lamang.','Umalis.'],c:0,h:'Ang pagtulong ay paraan ng pakikipagtulungan.'},{q:'Alin ang nagpapakita ng pagsunod sa pangaral ng magulang?',a:['Mag-aral nang mabuti.','Sadyang hindi makinig.','Magkalat.'],c:0,h:'Sundin ang mabuting pangaral ng magulang.'}];
const applyQ=[{q:'Nakakita ka ng damit sa sahig. Ano ang gagawin mo?',a:['Ilagay ito sa wastong lagayan.','Iwanan ito.','Itapon ito.'],c:0,h:'Ang tahanan ay dapat manatiling maayos.'},{q:'Gusto mong gumamit ng gadget pero hindi pa tapos ang takdang-aralin. Ano ang gagawin?',a:['Tapusin muna ang takdang-aralin.','Mag-gadget muna.','Huwag nang gumawa.'],c:0,h:'Unahin ang tungkulin.'},{q:'Sinabi ni Nanay na tumulong sa paglilinis. Ano ang mabuting tugon?',a:['“Opo, Nanay. Tutulong po ako.”','“Ayoko!”','“Mamaya na!”'],c:0,h:'Ipakita ang paggalang at pagtulong.'}];
const masteryQ=[{q:'Alin ang halimbawa ng paggalang sa magulang?',a:['Paggamit ng “po” at “opo”.','Pagsigaw sa magulang.','Hindi pakikinig.'],c:0},{q:'Alin ang dapat gawin bago lumabas ng bahay?',a:['Magpaalam.','Tumakbo palabas.','Magtago.'],c:0},{q:'Ano ang mabuting gawin sa kapatid?',a:['Igmalang at mahalin siya.','Asarin siya.','Saktan siya.'],c:0},{q:'Ano ang dapat unahin bago maglaro o gumamit ng gadget?',a:['Takdang-aralin.','Laro.','Panoorin ang video.'],c:0},{q:'Bakit tayo tumutulong sa mga gawaing-bahay?',a:['Para makipagtulungan at mapanatiling maayos ang tahanan.','Para hindi mag-aral.','Para makapaglaro buong araw.'],c:0},{q:'Alin ang tamang paraan ng pag-aayos ng damit?',a:['Ilagay sa wastong lagayan.','Ilagay sa sahig.','Iwan sa upuan.'],c:0}];
function renderQuiz(id,data,done){let i=0,answered=false;const box=$('#'+id);function draw(){answered=false;const x=data[i];box.innerHTML=`<div class="qnum">TANONG ${i+1} / ${data.length}</div><div class="question">${x.q}</div><div class="choices">${x.a.map((a,n)=>`<button class="choice" data-a="${n}">${String.fromCharCode(65+n)}. ${a}</button>`).join('')}</div><button class="secondary hintBtn" type="button">💡 Pahiwatig</button><div class="feedback" id="qfb"></div><button class="next hidden" id="qnext">${i===data.length-1?done?'🏆 Pumunta sa Huling Hamon':'🎉 Tapos!':'Susunod ➜'}</button>`;$$('#'+id+' [data-a]').forEach(b=>b.onclick=()=>answer(+b.dataset.a));$('.hintBtn').onclick=()=>{$('#qfb').className='hint';$('#qfb').textContent='💡 '+(x.h||'Balikan ang itinuro.')} ;$('#qnext').onclick=()=>{i++;if(i<data.length)draw();else done&&done()}}function answer(n){if(answered)return;answered=true;const x=data[i];const btns=$$('#'+id+' [data-a]');btns[x.c].classList.add('correct');if(n===x.c){$('#qfb').className='feedback good';$('#qfb').textContent='🌟 Tama! '+(x.h||'Magandang pag-iisip!');reward()}else{btns[n].classList.add('wrong');$('#qfb').className='feedback help';$('#qfb').textContent='💡 LET’S THINK AGAIN: '+(x.h||'Balikan ang halimbawa.');miss(id+': '+x.q)}$('#qnext').classList.remove('hidden')}draw()}
function startGuided(){renderQuiz('guidedGame',guidedQ,()=>{state.completed.push('guided');save();go('independent')})}
function startIndependent(){renderQuiz('independentGame',independentQ,()=>{state.completed.push('independent');save();go('games')})}
function startApply(){renderQuiz('applyGame',applyQ,()=>{state.completed.push('apply');save();go('mastery')})}
function startMastery(){renderQuiz('masteryGame',masteryQ,()=>finish())}
function finish(){state.mastery=Math.min(100,Math.round(state.points/90*100));save();showResults();go('results')}
function quickGame(){const qs=[{q:'Alin ang magalang na pananalita?',a:['“Opo.”','“Hoy!”','“Ayoko!”'],c:0},{q:'Ano ang gagawin bago lumabas?',a:['Magpaalam.','Tumakbo.','Magtago.'],c:0},{q:'Ano ang uunahin bago maglaro?',a:['Takdang-aralin.','Laro.','TV.'],c:0},{q:'Saan ilalagay ang damit?',a:['Wastong lagayan.','Sahig.','Hapag.'],c:0}];renderQuiz('gameArea',qs,()=>{$('#gamesNext').classList.remove('hidden');toast('Natapos ang Quick Pick!')})}
function sortGame(){const items=[['Po at opo','Paggalang'],['Magpaalam','Paggalang'],['Tumulong maglinis','Pagtutulungan'],['Ilagay ang damit sa lagayan','Pag-aayos'],['Tapusin ang takdang-aralin','Pag-aaral']];let selected=null;$('#gameArea').innerHTML=`<div class="quiz-card glass"><h3>🗂️ SORT IT</h3><p>Pindutin ang isang gawain, pagkatapos ay pindutin ang tamang grupo.</p><div class="sort-board"><div><h3>Mga Gawain</h3><div class="sort-items" id="items"></div></div><div><div class="dropzone" data-cat="Paggalang"><b>🙇 Paggalang</b></div><div class="dropzone" data-cat="Pagtutulungan"><b>🤝 Pagtutulungan</b></div><div class="dropzone" data-cat="Pag-aayos"><b>🧺 Pag-aayos</b></div><div class="dropzone" data-cat="Pag-aaral"><b>📚 Pag-aaral</b></div></div></div><div class="feedback" id="sortFb"></div></div>`;const itemsBox=$('#items');items.forEach((it,i)=>{const b=document.createElement('button');b.className='item-btn';b.textContent=it[0];b.onclick=()=>{selected=i;$$('.item-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#sortFb').textContent='Piliin ang tamang grupo.'};itemsBox.appendChild(b)});$$('.dropzone').forEach(z=>z.onclick=()=>{if(selected===null){toast('Pumili muna ng gawain.');return}const it=items[selected];if(z.dataset.cat===it[1]){state.points+=5;state.stars++;save();$('#sortFb').className='feedback good';$('#sortFb').textContent='⭐ Tama! '+it[0]+' ay para sa '+it[1]+'.';beep(true);celebrate();items.splice(selected,1);selected=null;renderItems();if(!items.length){$('#gamesNext').classList.remove('hidden');toast('Mahusay! Natapos mo ang Sort It.')}}else{$('#sortFb').className='feedback help';$('#sortFb').textContent='💡 Hindi pa. Isipin kung ano ang ipinapakita ng gawain.';miss('Sort It')}});function renderItems(){itemsBox.innerHTML='';items.forEach((it,i)=>{const b=document.createElement('button');b.className='item-btn';b.textContent=it[0];b.onclick=()=>{selected=i;$$('.item-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};itemsBox.appendChild(b)})}}
function matchGame(){const pairs=[['“Opo”','Paggalang'],['Magpaalam','Bago lumabas'],['Takdang-aralin','Unahin bago maglaro'],['Damit','Wastong lagayan']];let left=null,right=null,done=0;$('#gameArea').innerHTML=`<div class="quiz-card glass"><h3>🧩 MATCH IT</h3><p>Pindutin ang salita at ang katugmang kahulugan/gawain.</p><div class="match-board"><div id="ml"></div><div id="mr"></div></div><div id="matchFb" class="feedback"></div></div>`;const l=$('#ml'),r=$('#mr');function draw(){l.innerHTML='';r.innerHTML='';pairs.forEach((p,i)=>{const a=document.createElement('button');a.className='item-btn';a.textContent=p[0];a.dataset.i=i;a.onclick=()=>pick('l',i,a);l.appendChild(a);const b=document.createElement('button');b.className='item-btn';b.textContent=p[1];b.dataset.i=i;b.onclick=()=>pick('r',i,b);r.appendChild(b)})}function pick(side,i,el){if(side==='l')left=i;else right=i;el.classList.add('selected');if(left!==null&&right!==null){if(left===right){state.points+=5;state.stars++;done++;$('#matchFb').className='feedback good';$('#matchFb').textContent='⭐ Tamang pares!';beep(true);celebrate();pairs.splice(left,1)}else{$('#matchFb').className='feedback help';$('#matchFb').textContent='💡 Subukan muli.';miss('Match It')}left=null;right=null;save();setTimeout(()=>{if(pairs.length)draw();else{$('#gamesNext').classList.remove('hidden');toast('Mahusay! Natapos mo ang Match It.')}},450)}}draw()}
$$('.game-tab').forEach(b=>b.onclick=()=>{$$('.game-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.game==='quick')quickGame();if(b.dataset.game==='sort')sortGame();if(b.dataset.game==='match')matchGame()});
function showResults(){const pct=state.mastery||0;$('#finalPercent').textContent=pct+'%';$('#finalStars').textContent=state.stars;$('#finalBadges').textContent=state.badges;$('#finalStreak').textContent=state.bestStreak;$('#resultMessage').textContent=pct>=90?'🏆 Lesson Master! Napakahusay ng iyong pag-unawa.':pct>=80?'🌟 Halos handa ka na! Ipagpatuloy ang pagsasanay.':pct>=70?'👍 Magandang pag-unlad! Magsanay pa nang kaunti.':'💪 Patuloy na magsanay. Kaya mo ito!';const box=$('#mistakesBox');box.innerHTML=state.missed.length?'<h3>💡 Mga dapat balikan</h3>'+state.missed.slice(-8).map(x=>`<div class="mistake-item">${x}</div>`).join(''):'<h3>✨ Wala kang kailangang balikan!</h3>';const deg=pct*3.6;$('.score-ring').style.background=`conic-gradient(var(--gold) ${deg}deg,#e8eef5 ${deg}deg)`}
$('#retryBtn').onclick=()=>{state.points=0;state.stars=0;state.badges=0;state.streak=0;state.missed=[];state.mastery=null;state.completed=[];save();go('connect');initConnect()};$('#mistakeBtn').onclick=()=>{if(!state.missed.length){toast('Walang missed question. Mahusay!');return}go('independent');startIndependent()};
$('#resetBtn').onclick=()=>{if(confirm('Sigurado ka bang i-reset ang lahat ng progreso?')){localStorage.removeItem(KEY);state={...defaultState};save();toast('Na-reset na ang progreso.')}};
initConnect();updateHome();
// Start each stage when opened via map/flow.
$$('[data-go="guided"]').forEach(b=>b.addEventListener('click',()=>setTimeout(startGuided,80)));$$('[data-go="independent"]').forEach(b=>b.addEventListener('click',()=>setTimeout(startIndependent,80)));$$('[data-go="apply"]').forEach(b=>b.addEventListener('click',()=>setTimeout(startApply,80)));$$('[data-go="mastery"]').forEach(b=>b.addEventListener('click',()=>setTimeout(startMastery,80)));
// Prevent accidental duplicate initialization when moving from game zone through explicit buttons.
$('#gamesNext').addEventListener('click',()=>setTimeout(startApply,80));
