const LEVELS=['easy','average','difficult','boss'];
const games={
 easy:{title:'Evidence Finder',label:'EASY MISSION',type:'quiz',questions:[
  {passage:'Lena packed an extra bottle of water before leaving for the hike. The weather report predicted a very hot afternoon, so she wanted to make sure she had enough to drink.',claim:'Lena prepared carefully for the hike.',q:'Which sentence is the strongest evidence?',choices:['Lena went on a hike.','The weather report predicted a very hot afternoon.','Lena packed an extra bottle of water before leaving for the hike.','Lena wanted to go outside.'],answer:2,explain:'The sentence directly shows Lena taking a preparation step before the hike.',hint:'Look for an action that shows preparation.'},
  {passage:'Marcus noticed that the classroom floor was covered with scraps of paper. Before the teacher arrived, he picked up the papers and placed them in the recycling bin.',claim:'Marcus is helpful.',q:'Which detail best supports the claim?',choices:['The classroom had a floor.','Marcus noticed the scraps.','The teacher had not arrived.','Marcus picked up the papers and placed them in the recycling bin.'],answer:3,explain:'Helping by cleaning the classroom directly supports the claim that Marcus is helpful.',hint:'Which action helps someone or improves the room?'},
  {passage:'After practicing the piano every afternoon for a month, Ana played the song without stopping. Her family applauded when she finished.',claim:'Ana improved through practice.',q:'Which evidence best supports the claim?',choices:['Her family applauded.','She played the song without stopping after practicing every afternoon for a month.','Ana owned a piano.','The song had a beginning and an ending.'],answer:1,explain:'The detail connects regular practice with successfully playing the song.',hint:'Find the detail that includes both practice and improvement.'},
  {passage:'The school garden was dry after several days without rain. The students carried watering cans outside and watered the vegetables.',claim:'The students cared for the garden.',q:'Which evidence proves the claim?',choices:['The garden was at school.','Several days passed.','The students watered the vegetables.','The vegetables were green.'],answer:2,explain:'Watering the vegetables is a direct action that shows care for the garden.',hint:'Look for what the students actually did.'},
  {passage:'Jamal found a wallet near the playground. He took it to the office so the owner could get it back.',claim:'Jamal made an honest choice.',q:'Which detail best supports the claim?',choices:['He was near the playground.','He found a wallet.','He took the wallet to the office so the owner could get it back.','The office was in the school.'],answer:2,explain:'Taking the lost wallet to the office instead of keeping it is direct evidence of honesty.',hint:'Which action shows what he chose to do with the wallet?'},
  {passage:'Nina read the directions twice before beginning the science experiment. She arranged the materials in the order listed and followed each step carefully.',claim:'Nina followed instructions carefully.',q:'Which evidence is strongest?',choices:['Nina did a science experiment.','She had materials.','She read the directions twice and followed each step carefully.','The directions had several steps.'],answer:2,explain:'This detail directly describes Nina checking and following the instructions.',hint:'Look for the evidence that describes careful following.'}
 ]},
 average:{title:'Claim & Evidence Puzzle',label:'AVERAGE MISSION',type:'quiz',questions:[
  {passage:'During the school clean-up, Diego noticed that a younger student could not reach the high shelf. Diego moved a chair safely into place and asked the student to wait while he got the book.',claim:'Diego showed responsibility.',q:'Which evidence most strongly supports the claim?',choices:['Diego was in school.','A shelf was high.','Diego moved a chair safely and helped the student get the book.','The student wanted a book.'],answer:2,explain:'The evidence shows Diego acting safely and helping another student solve a problem.',hint:'Choose the action that demonstrates responsibility, not just a background fact.'},
  {passage:'Tara wanted to improve her reading speed. She read for fifteen minutes every night and recorded the number of pages she finished. After three weeks, she was reading more pages in the same amount of time.',claim:'Tara used a consistent strategy to improve.',q:'Which evidence gives the best support?',choices:['Tara wanted to read faster.','She read for fifteen minutes every night and tracked her pages.','Three weeks passed.','She liked books.'],answer:1,explain:'Her repeated practice and tracking show a consistent strategy, while the later result shows improvement.',hint:'Look for a repeated action and a way she monitored it.'},
  {passage:'The class was preparing for a presentation. Instead of letting one person do all the work, the group divided the tasks. Mia researched, Paolo designed the slides, and Kim practiced the introduction.',claim:'The group worked cooperatively.',q:'Which evidence is most relevant?',choices:['The class had a presentation.','There were three students.','The group divided the tasks among members.','Mia liked researching.'],answer:2,explain:'Dividing responsibilities among members is direct evidence of cooperation.',hint:'Which detail shows members working together by sharing responsibilities?'},
  {passage:'When the power went out, the family used flashlights, checked that everyone was safe, and stayed together until the lights returned.',claim:'The family responded calmly to the problem.',q:'Which evidence best supports this inference?',choices:['The power went out.','They owned flashlights.','They checked that everyone was safe and stayed together until the lights returned.','The lights eventually returned.'],answer:2,explain:'Their organized actions and staying together support the inference that they responded calmly.',hint:'Choose the evidence that shows how they behaved during the problem.'},
  {passage:'Ava had three choices for a project topic. She read two articles about each topic, compared the information, and chose the topic with enough reliable sources.',claim:'Ava made an informed decision.',q:'Why is the selected evidence strong?',choices:['It says Ava had choices.','It shows she compared information before deciding.','It tells us there were articles.','It says she completed a project.'],answer:1,explain:'The evidence explains the process Ava used to make her decision, not merely the final choice.',hint:'Strong evidence should show the thinking behind the decision.'},
  {passage:'The river rose after heavy rain. Residents moved important belongings to higher shelves and followed the community alert to leave the area when instructed.',claim:'Residents took the warning seriously.',q:'Which evidence most directly proves the claim?',choices:['The river was a river.','It rained heavily.','Residents moved belongings higher and followed the alert to leave when instructed.','The area had residents.'],answer:2,explain:'Both actions show residents responding to the warning rather than ignoring it.',hint:'Look for actions that demonstrate a response to a warning.'}
 ]},
 difficult:{title:'Evidence Escape Room',label:'DIFFICULT MISSION',type:'quiz',questions:[
  {passage:'Although the library was crowded, Sofia chose a quiet corner, turned off her phone notifications, and placed her notes beside her. She had a research report due the next morning. After an hour, she had completed the outline and two sections.',claim:'Sofia created conditions that helped her focus.',q:'Which evidence BEST supports the claim?',choices:['The library was crowded.','Her report was due the next morning.','She chose a quiet corner, turned off notifications, and prepared her notes.','She completed two sections.'],answer:2,explain:'These are deliberate actions Sofia took to reduce distractions and organize her work.',hint:'The strongest evidence shows the choices she made to improve focus.'},
  {passage:'Eli first believed the old bridge was unsafe because it looked damaged. Before crossing, he read the posted notice, saw that engineers had inspected it that morning, and noticed a sign explaining that the visible marks were part of a recent repair.',claim:'Eli revised his initial belief after considering evidence.',q:'Which evidence BEST demonstrates this?',choices:['The bridge looked damaged.','Eli wanted to cross the bridge.','He read the notice and learned that engineers had inspected it and the marks were from a repair.','There was a sign near the bridge.'],answer:2,explain:'This detail shows Eli gathering new information that changed how he understood what he saw.',hint:'Look for evidence of new information that challenged his first belief.'},
  {passage:'The coach told the team that effort would matter more than the final score. During practice, the players kept working after several drills went badly, asked for feedback, and tried the drills again.',claim:'The players demonstrated perseverance.',q:'Which combination is strongest?',choices:['The coach spoke to the team.','Several drills went badly.','They kept working, asked for feedback, and tried again.','They were practicing a sport.'],answer:2,explain:'Continuing after difficulty, seeking feedback, and trying again are connected actions that demonstrate perseverance.',hint:'Choose the evidence that shows continuing despite difficulty.'},
  {passage:'A town meeting considered whether to add more trees to a busy street. One speaker claimed trees would make the street safer. Another presented data showing that shaded sidewalks had more pedestrians and lower surface temperatures. The council requested additional evidence before deciding.',claim:'The council wanted evidence before making a decision.',q:'Which detail most directly supports the claim?',choices:['The meeting was in a town.','One speaker made a claim.','Another speaker presented data.','The council requested additional evidence before deciding.'],answer:3,explain:'This is a direct statement of the council asking for evidence before deciding.',hint:'Choose the detail that describes the council’s action.'},
  {passage:'Rina\'s first draft said, “The character is brave.” Her teacher asked her to prove it. Rina returned to the story, found a scene where the character entered a dangerous building to rescue a neighbor, and revised her paragraph to explain how the action demonstrated courage.',claim:'Rina strengthened her response by connecting evidence to her claim.',q:'Which evidence best supports this?',choices:['Her first draft was short.','Her teacher asked her to prove it.','She found the rescue scene and explained how the action demonstrated courage.','The story had a dangerous building.'],answer:2,explain:'Rina did more than locate a detail; she connected the detail to her claim through an explanation.',hint:'Look for the part showing both evidence and explanation.'},
  {passage:'A student argues that a character is generous because he gives away a pencil once. Later, the story shows the character regularly sharing supplies, tutoring younger students, and donating books to a community center.',claim:'The later details provide stronger evidence of generosity than the single pencil example.',q:'Why are the later details stronger?',choices:['They are longer sentences.','They show a repeated pattern of generous actions across different situations.','They mention books.','They happen later in the story.'],answer:1,explain:'A repeated pattern across situations gives stronger support than one isolated action.',hint:'Think about repetition and variety of supporting examples.'}
 ]},
 boss:{title:'Evidence Master Challenge',label:'🏆 FINAL BOSS BATTLE',type:'quiz',questions:[
  {passage:'Mara wanted to enter the school art contest. Her first drawing did not turn out as planned. Instead of quitting, she asked her art teacher for feedback, practiced the difficult technique, and submitted a revised drawing two weeks later.',claim:'Mara responds to setbacks by learning and trying again.',q:'Which evidence is strongest?',choices:['Mara entered an art contest.','Her first drawing did not turn out as planned.','She asked for feedback, practiced the difficult technique, and submitted a revised drawing.','The contest was at school.'],answer:2,explain:'The sequence of feedback, practice, and revision directly demonstrates learning from a setback.',hint:'The strongest evidence shows what Mara did after the setback.'},
  {passage:'A class survey found that students who read at home often reported feeling more confident discussing books. The teacher reminded the class that the survey showed a relationship, not proof that reading at home caused confidence.',claim:'The teacher carefully distinguished evidence from a conclusion that goes beyond the evidence.',q:'Which detail best supports the claim?',choices:['The class took a survey.','Students discussed books.','The teacher explained that the survey showed a relationship, not proof of causation.','Some students read at home.'],answer:2,explain:'The teacher explicitly limits the conclusion to what the survey can support.',hint:'Look for the statement about what the evidence can and cannot prove.'},
  {passage:'Jon says the article is trustworthy because it has many pictures. However, the article also names its sources, gives dates for its information, and explains where the data came from.',claim:'The article has stronger evidence of reliability than Jon first identifies.',q:'Which evidence best supports the claim?',choices:['It has many pictures.','It has a title.','It names sources, gives dates, and explains where the data came from.','Jon read the article.'],answer:2,explain:'Named sources, dates, and transparent data origins are more relevant to reliability than pictures.',hint:'Choose evidence directly related to whether information can be checked.'},
  {passage:'When asked whether the new playground design would help everyone, the student council did not rely on one student’s opinion. They surveyed students from different grade levels, reviewed accessibility guidelines, and compared two designs before making a recommendation.',claim:'The council used multiple sources of evidence to make a thoughtful recommendation.',q:'Which evidence BEST supports this claim?',choices:['They had a playground project.','One student gave an opinion.','They surveyed different grades, reviewed guidelines, and compared two designs.','They made a recommendation.'],answer:2,explain:'The council combined several relevant sources and comparison methods before deciding.',hint:'Look for multiple kinds of evidence gathered before the recommendation.'},
  {passage:'Lea claims that the character is lonely. The strongest clues are that the character eats lunch alone, watches other students form groups, and writes in a journal that she wishes she had someone to talk to.',claim:'Which evidence most strongly supports Lea’s claim?',q:'Choose the strongest combination.',choices:['The character eats lunch alone and watches other students form groups.','The character goes to school.','The character owns a journal.','The story takes place at school.'],answer:0,explain:'The selected details directly show social isolation and wanting connection, which support loneliness.',hint:'Choose details that reveal both the character’s situation and feelings.'},
  {passage:'A strong response to a reading question should not merely repeat the claim. It should use a specific detail from the text and explain the connection.',claim:'What makes evidence strong?',q:'Which answer best states the lesson?',choices:['Evidence should be as long as possible.','Evidence should come from the text, be relevant to the claim, and be explained.','Evidence is only a personal opinion.','Any detail from the passage is equally strong.'],answer:1,explain:'Strong textual evidence is text-based, relevant, and connected to the claim through reasoning.',hint:'Remember the three-part structure: claim, evidence, explanation.'}
 ]}
};
let state=JSON.parse(localStorage.getItem('jg_textual_evidence')||'null')||{score:0,streak:0,bestStreak:0,completed:{},accuracy:{}};
let current={level:null,index:0,score:0,correct:0,streak:0,lockedChoice:false};
const $=s=>document.querySelector(s);
function save(){localStorage.setItem('jg_textual_evidence',JSON.stringify(state));updateUI()}
function updateUI(){ $('#headerScore').textContent=state.score; $('#heroStreak').textContent=state.bestStreak||0; const done=LEVELS.filter(x=>state.completed[x]).length; const pct=Math.round(done/4*100); $('#overallPercent').textContent=pct+'%'; $('.progress-ring').style.setProperty('--progress',pct+'%'); $('#progressTitle').textContent=done===4?'Lesson mastered!':done?`${done} of 4 missions complete`:'Ready to begin?'; $('#progressMessage').textContent=done===4?'Excellent! You completed every challenge.':done?'Keep going — your next mission is waiting.':'Complete Easy to unlock your next challenge.'; LEVELS.forEach((l,i)=>{const card=document.querySelector(`[data-level="${l}"]`),lock=$(`#lock-${l}`); if(i===0||state.completed[LEVELS[i-1]]){card.classList.remove('locked');lock.textContent=state.completed[l]?'✓':'🔓';card.querySelector('.play-btn').textContent=state.completed[l]?'Play Again':'Start Mission'}})}
function openGame(level){const idx=LEVELS.indexOf(level); if(idx>0&&!state.completed[LEVELS[idx-1]]){toast('Complete the previous mission to unlock this level.');return} current={level,index:0,score:0,correct:0,streak:0,lockedChoice:false}; $('#gameModal').classList.add('open');$('#gameModal').setAttribute('aria-hidden','false');renderQuestion()}
function closeGame(){ $('#gameModal').classList.remove('open');$('#gameModal').setAttribute('aria-hidden','true') }
function renderQuestion(){const g=games[current.level],q=g.questions[current.index];$('#gameLevel').textContent=g.label;$('#gameTitle').textContent=g.title;$('#gameScore').textContent=current.score;$('#questionCounter').textContent=`Question ${current.index+1} of ${g.questions.length}`;$('#streakText').textContent=`🔥 ${current.streak} streak`;$('#gameProgressBar').style.width=((current.index)/g.questions.length*100)+'%';let html='';if(current.level==='boss')html+='<div class="boss-wrap"><div class="boss-character">👑</div><div class="hearts">❤️ ❤️ ❤️</div></div>';html+=`<div class="question-card"><div class="passage">${q.passage}</div><div class="claim-box"><b>CLAIM:</b> ${q.claim}</div><h3>${q.q}</h3><div class="choices">${q.choices.map((c,i)=>`<button class="choice" data-i="${i}"><span class="letter">${String.fromCharCode(65+i)}.</span><span>${c}</span></button>`).join('')}</div><div id="feedback"></div></div>`;$('#gameArea').innerHTML=html;document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>answer(+b.dataset.i)));}
function answer(i){if(current.lockedChoice)return;current.lockedChoice=true;const q=games[current.level].questions[current.index],buttons=[...document.querySelectorAll('.choice')];buttons.forEach(b=>b.classList.add('disabled'));const chosen=buttons[i];if(i===q.answer){chosen.classList.add('correct');current.correct++;current.streak++;current.score+=10+Math.max(0,current.streak-1)*2;state.bestStreak=Math.max(state.bestStreak,current.streak);showFeedback(true,q);pulseScore();if(current.streak>=3)toast(`🔥 ${current.streak} answer streak!`);if(current.streak>=3)smallConfetti(8)}else{chosen.classList.add('wrong');current.streak=0;buttons[q.answer].classList.add('correct');showFeedback(false,q)}$('#gameScore').textContent=current.score;$('#streakText').textContent=`🔥 ${current.streak} streak`;$('#gameProgressBar').style.width=((current.index+1)/games[current.level].questions.length*100)+'%';}
function showFeedback(ok,q){const f=$('#feedback');f.innerHTML=`<div class="feedback"><strong>${ok?'🎉 Correct! Great detective work.':'💡 Not quite — let’s learn from the clue.'}</strong><p>${q.explain}</p><div class="hint">💡 Hint: ${q.hint}</div><div class="game-actions"><button class="btn ghost" id="retryQ">${ok?'Review':'Try Again'}</button><button class="btn primary" id="nextQ">${current.index===games[current.level].questions.length-1?'Finish Mission':'Next Question →'}</button></div></div>`;$('#retryQ').addEventListener('click',()=>{current.lockedChoice=false;renderQuestion()});$('#nextQ').addEventListener('click',nextQuestion)}
function nextQuestion(){if(current.index<games[current.level].questions.length-1){current.index++;current.lockedChoice=false;renderQuestion()}else finishLevel()}
function finishLevel(){const g=games[current.level],total=g.questions.length,accuracy=Math.round(current.correct/total*100);state.score+=current.score;state.completed[current.level]=true;state.accuracy[current.level]=accuracy;save();if(current.level!=='boss'){unlockToast(LEVELS[LEVELS.indexOf(current.level)+1])}else{smallConfetti(70)}$('#gameArea').innerHTML=`<div class="final-screen"><div class="final-trophy">${current.level==='boss'?'👑':'🏆'}</div><span class="eyebrow">MISSION COMPLETE</span><h2>${g.title} Complete!</h2><p>You found evidence, connected ideas, and practiced explaining your thinking.</p><div class="result-grid"><div class="result-stat"><b>${current.score}</b><span>MISSION SCORE</span></div><div class="result-stat"><b>${accuracy}%</b><span>ACCURACY</span></div><div class="result-stat"><b>${current.streak}</b><span>FINAL STREAK</span></div></div><button class="btn primary" id="continueBtn">${current.level==='boss'?'🎉 Finish Lesson':'🔓 Continue Journey'}</button><button class="btn ghost" id="againBtn">Play Again</button></div>`;$('#continueBtn').addEventListener('click',()=>{closeGame();document.querySelector(`[data-level="${current.level==='boss'?'boss':LEVELS[LEVELS.indexOf(current.level)+1]}"]`).scrollIntoView({behavior:'smooth',block:'center'})});$('#againBtn').addEventListener('click',()=>openGame(current.level));}
function pulseScore(){const e=$('#gameScore');e.animate([{transform:'scale(1)'},{transform:'scale(1.3)'},{transform:'scale(1)'}],{duration:350})}
function unlockToast(level){const names={average:'AVERAGE',difficult:'DIFFICULT',boss:'FINAL CHALLENGE'};toast(`🔓 ${names[level]} UNLOCKED!`)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function smallConfetti(n=20){const c=$('#confetti');for(let i=0;i<n;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.left=Math.random()*100+'%';p.style.setProperty('--x',(Math.random()*240-120)+'px');p.style.animationDelay=(Math.random()*.35)+'s';p.style.background=['#d6a21f','#092d61','#5c8fc9','#e8c65c'][i%4];c.appendChild(p);setTimeout(()=>p.remove(),2200)}}
document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.scroll).scrollIntoView({behavior:'smooth'})));
document.querySelectorAll('.play-btn').forEach(b=>b.addEventListener('click',()=>openGame(b.dataset.game)));
$('#closeGame').addEventListener('click',closeGame);$('#gameModal').addEventListener('click',e=>{if(e.target.id==='gameModal')closeGame()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeGame()});updateUI();
