const LEVELS=["easy","average","difficult","boss"];
const games={
easy:{label:"🟢 EASY MISSION",title:"Clue Finder",questions:[
{passage:"Mia was famished after the long hike. She had not eaten since breakfast, so she quickly finished two sandwiches and a banana.",word:"famished",q:"What does “famished” most likely mean?",choices:["very hungry","very tired","very angry","very happy"],answer:0,explain:"The details about not eating and quickly finishing food show that Mia was very hungry.",hint:"Look at what Mia does after the hike."},
{passage:"The lake was tranquil. There were no waves, the birds were quiet, and the water barely moved.",word:"tranquil",q:"What does “tranquil” mean?",choices:["crowded","peaceful","dangerous","deep"],answer:1,explain:"The quiet birds, still water, and lack of waves all point to a peaceful setting.",hint:"Which choice matches a quiet, still place?"},
{passage:"Unlike the timid kitten that hid under the bed, the bold puppy ran toward every visitor.",word:"timid",q:"What does “timid” most likely mean?",choices:["brave","playful","shy","noisy"],answer:2,explain:"The sentence contrasts timid with bold. Hiding under the bed shows that timid means shy or easily frightened.",hint:"Look at the contrast with “bold.”"},
{passage:"The teacher gave a concise explanation. It was brief, clear, and easy for the class to understand.",word:"concise",q:"What does “concise” mean?",choices:["long and confusing","brief and clear","funny and loud","detailed and difficult"],answer:1,explain:"The sentence restates concise as brief and clear.",hint:"The clue comes right after the word."},
{passage:"Many nocturnal animals, such as owls, bats, and raccoons, are most active at night.",word:"nocturnal",q:"What does “nocturnal” mean?",choices:["active at night","active in winter","living in water","very small"],answer:0,explain:"The examples and the phrase “active at night” directly define nocturnal.",hint:"Look for the phrase that tells when they are active."}
]},
average:{label:"🟡 AVERAGE MISSION",title:"Context Clue Puzzle",questions:[
{passage:"The scientist was meticulous when recording the results. She checked every number twice and carefully labeled each sample.",word:"meticulous",q:"Which meaning is best supported?",choices:["careless","very careful","impatient","confused"],answer:1,explain:"Checking every number twice and labeling each sample show careful attention to detail.",hint:"What do her actions show about how she works?"},
{passage:"The old bridge was dilapidated. Cracked boards, rusty bolts, and broken rails made it unsafe to cross.",word:"dilapidated",q:"What does the word most likely mean?",choices:["newly built","decorated","in poor condition","very wide"],answer:2,explain:"Cracked, rusty, and broken parts indicate that the bridge is in poor condition.",hint:"Focus on the physical details of the bridge."},
{passage:"Jon was reluctant to speak in front of the class. He looked at the floor and quietly shook his head when the teacher called on him.",word:"reluctant",q:"What does “reluctant” mean here?",choices:["unwilling or hesitant","excited","prepared","proud"],answer:0,explain:"Jon's actions show that he was hesitant and did not want to speak.",hint:"How does Jon respond when he is called on?"},
{passage:"The trail was treacherous. The hikers moved slowly because loose rocks and steep drops made the path dangerous.",word:"treacherous",q:"Which meaning fits best?",choices:["beautiful","dangerous","short","crowded"],answer:1,explain:"Loose rocks and steep drops make the trail dangerous.",hint:"Which answer matches the danger described?"},
{passage:"The coach praised the player's tenacity. Even after missing several shots, she continued practicing until she improved.",word:"tenacity",q:"What does “tenacity” mean?",choices:["persistence","speed","humor","fear"],answer:0,explain:"Continuing to practice after mistakes demonstrates persistence or determination.",hint:"Think about what she does after missing shots."},
{passage:"The room was austere: it contained only a plain table, two chairs, and an empty shelf. There were no decorations.",word:"austere",q:"What does “austere” most likely mean?",choices:["luxurious","plain and simple","colorful","crowded"],answer:1,explain:"The room has only basic furniture and no decorations, so it is plain and simple.",hint:"What is missing from the room?"}
]},
difficult:{label:"🔴 DIFFICULT MISSION",title:"Vocabulary Escape",questions:[
{passage:"The author's argument was ambiguous. One paragraph suggested that the policy would help families, while another seemed to suggest the opposite. Readers could not tell exactly what the author believed.",word:"ambiguous",q:"What does “ambiguous” mean?",choices:["easy to understand","having more than one possible meaning","completely false","very emotional"],answer:1,explain:"The conflicting suggestions make the author's position unclear or open to more than one interpretation.",hint:"Why can't readers tell exactly what the author believes?"},
{passage:"After the storm, the streets were inundated. Water covered the sidewalks, filled the drains, and reached the steps of nearby houses.",word:"inundated",q:"Which meaning is best supported?",choices:["covered or flooded with water","completely dry","blocked by traffic","covered with snow"],answer:0,explain:"Water covering streets and reaching houses shows flooding.",hint:"What happened to the streets after the storm?"},
{passage:"The new student was gregarious. She introduced herself to everyone, joined several groups at lunch, and enjoyed talking with classmates.",word:"gregarious",q:"What does the context suggest?",choices:["very social","easily frightened","extremely quiet","often confused"],answer:0,explain:"Introducing herself, joining groups, and enjoying conversation show that she is very social.",hint:"Focus on how she interacts with people."},
{passage:"The manager's response was pragmatic. Instead of arguing about what should have happened, she focused on a practical solution that could be completed that afternoon.",word:"pragmatic",q:"Which meaning best fits the context?",choices:["focused on practical action","focused on imagination","angry and emotional","uncertain and hesitant"],answer:0,explain:"The manager focuses on a practical solution that can actually be completed.",hint:"Which option matches “practical solution”?"},
{passage:"The child's explanation was plausible. It was not proven, but the timeline and details made it seem reasonable enough to consider.",word:"plausible",q:"What does “plausible” mean?",choices:["impossible","reasonable or believable","secret","unrelated"],answer:1,explain:"The explanation is not proven, but the details make it seem reasonable or believable.",hint:"The passage says it seemed “reasonable.”"},
{passage:"The reporter remained skeptical of the claim. Although the speaker sounded confident, the reporter asked for documents and independent evidence before accepting it.",word:"skeptical",q:"What does “skeptical” most likely mean?",choices:["ready to believe without proof","doubtful and requiring evidence","completely uninterested","certain the claim is true"],answer:1,explain:"Asking for documents and independent evidence shows doubt and a desire for proof.",hint:"Why does the reporter ask for evidence?"}
]},
boss:{label:"🏆 FINAL CHALLENGE",title:"Context Clue Master",questions:[
{passage:"The museum guide was knowledgeable; she could answer detailed questions about ancient tools, explain their uses, and connect them to daily life in the past.",word:"knowledgeable",q:"Which meaning is best supported?",choices:["having a lot of knowledge","being easily confused","being very young","having no experience"],answer:0,explain:"Her ability to answer detailed questions and explain connections shows that she has a lot of knowledge.",hint:"Look at what she can explain."},
{passage:"The path was meandering rather than straight. It curved around trees, crossed a small stream, and changed direction several times before reaching the cabin.",word:"meandering",q:"What does “meandering” mean?",choices:["moving in a winding way","moving very quickly","completely blocked","perfectly straight"],answer:0,explain:"The path curves and changes direction several times, so it is winding rather than straight.",hint:"Compare the path with the word “straight.”"},
{passage:"The speaker's tone was jovial. He smiled, told a few jokes, and made the audience laugh during his introduction.",word:"jovial",q:"Which meaning fits the evidence?",choices:["cheerful and friendly","serious and angry","sad and worried","quiet and nervous"],answer:0,explain:"Smiling, joking, and making people laugh suggest a cheerful and friendly tone.",hint:"What feeling do the jokes create?"},
{passage:"The evidence was scant. The researchers had only two small samples and very few observations, so they could not make a strong conclusion.",word:"scant",q:"What does “scant” mean?",choices:["abundant","limited or insufficient","perfectly accurate","expensive"],answer:1,explain:"Only two samples and very few observations mean the evidence is limited or insufficient.",hint:"Think about how much evidence they actually have."},
{passage:"The instructions were explicit: place the red card on the left, write your name at the top, and submit the form before leaving.",word:"explicit",q:"What does “explicit” mean?",choices:["clearly stated","hidden","optional","confusing"],answer:0,explain:"The instructions give clear, specific directions, so they are explicit.",hint:"Are the directions clear or hidden?"},
{passage:"Although the athlete felt exhausted, her determination was unwavering. She kept training each morning and refused to give up when practice became difficult.",word:"unwavering",q:"Which meaning is best supported?",choices:["changing often","steady and not weakening","careless","secretive"],answer:1,explain:"She continues training and refuses to give up, showing that her determination stays steady.",hint:"Does her determination change when training gets hard?"}
]}
};
let state=JSON.parse(localStorage.getItem("jg_context_clue")||"null")||{score:0,bestStreak:0,completed:{}};
let current={level:null,index:0,score:0,correct:0,streak:0,locked:false};
const $=s=>document.querySelector(s);
function save(){localStorage.setItem("jg_context_clue",JSON.stringify(state));updateUI()}
function updateUI(){
  $("#totalScore").textContent=state.score; $("#streakDisplay").textContent=state.bestStreak||0;
  const done=LEVELS.filter(x=>state.completed[x]).length, pct=Math.round(done/4*100);
  $("#percent").textContent=pct+"%"; $("#ring").style.setProperty("--p",pct+"%");
  $("#progressTitle").textContent=done===4?"Lesson mastered!":done?`${done} of 4 missions complete`:"Ready to begin?";
  $("#progressText").textContent=done===4?"Excellent! You completed every context clue challenge.":done?"Keep going — your next mission is waiting.":"Complete Clue Finder to unlock your next challenge.";
  LEVELS.forEach((l,i)=>{const card=document.querySelector(`[data-level="${l}"]`),lock=$(`#lock-${l}`);if(i===0||state.completed[LEVELS[i-1]]){card.classList.remove("locked");lock.textContent=state.completed[l]?"✓":"🔓";card.querySelector(".play").textContent=state.completed[l]?"Play Again":"Start Mission"}});
}
function openGame(level){const idx=LEVELS.indexOf(level);if(idx>0&&!state.completed[LEVELS[idx-1]]){toast("🔒 Complete the previous mission first.");return}current={level,index:0,score:0,correct:0,streak:0,locked:false};$("#modal").classList.add("open");render()}
function closeGame(){$("#modal").classList.remove("open")}
function render(){
 const g=games[current.level],q=g.questions[current.index];
 $("#gameLevel").textContent=g.label;$("#gameTitle").textContent=g.title;$("#gameScore").textContent=current.score;
 $("#counter").textContent=`Question ${current.index+1} of ${g.questions.length}`;$("#streak").textContent=`🔥 ${current.streak} streak`;
 $("#bar").style.width=(current.index/g.questions.length*100)+"%";
 let boss=current.level==="boss"?`<div class="boss-box"><div class="boss">👑</div><div class="hearts" id="hearts">❤️ ❤️ ❤️</div><small>Final Mastery Challenge</small></div>`:"";
 $("#gameArea").innerHTML=boss+`<div class="question-card"><div class="passage">${q.passage.replace(q.word,`<span class="word-highlight">${q.word}</span>`)}</div><h3 class="prompt">${q.q}</h3><div class="choices">${q.choices.map((c,i)=>`<button class="choice" data-i="${i}"><span class="letter">${String.fromCharCode(65+i)}.</span><span>${c}</span></button>`).join("")}</div><div id="feedback"></div></div>`;
 document.querySelectorAll(".choice").forEach(b=>b.addEventListener("click",()=>answer(+b.dataset.i)));
}
function answer(i){
 if(current.locked)return;current.locked=true;
 const q=games[current.level].questions[current.index],buttons=[...document.querySelectorAll(".choice")];
 buttons.forEach(b=>b.classList.add("disabled"));
 if(i===q.answer){buttons[i].classList.add("correct");current.correct++;current.streak++;current.score+=10+Math.max(0,current.streak-1)*2;state.bestStreak=Math.max(state.bestStreak,current.streak);pulseScore();if(current.streak>=3)toast(`🔥 ${current.streak} answer streak!`);if(current.streak>=3)confetti(8)}
 else{buttons[i].classList.add("wrong");buttons[q.answer].classList.add("correct");current.streak=0}
 $("#gameScore").textContent=current.score;$("#streak").textContent=`🔥 ${current.streak} streak`;$("#bar").style.width=((current.index+1)/games[current.level].questions.length*100)+"%";
 if(current.level==="boss"){const hearts=Math.max(0,3-Math.floor((current.index+1)/2));$("#hearts").textContent="❤️ ".repeat(hearts)+"♡ ".repeat(3-hearts)}
 const f=$("#feedback");f.innerHTML=`<div class="feedback"><strong>${i===q.answer?"🎉 Correct! Great clue work.":"💡 Not quite — let's learn from the clue."}</strong><p>${q.explain}</p><div class="hint">💡 Hint: ${q.hint}</div><div class="game-actions"><button class="btn ghost" id="retry">${i===q.answer?"Review":"Try Again"}</button><button class="btn primary" id="next">${current.index===games[current.level].questions.length-1?"Finish Mission":"Next Question →"}</button></div></div>`;
 $("#retry").addEventListener("click",()=>{current.locked=false;render()});$("#next").addEventListener("click",next);
}
function next(){if(current.index<games[current.level].questions.length-1){current.index++;current.locked=false;render()}else finish()}
function finish(){
 const g=games[current.level],total=g.questions.length,acc=Math.round(current.correct/total*100);
 state.score+=current.score;state.completed[current.level]=true;save();
 if(current.level!=="boss")toast(`🔓 ${["","AVERAGE","DIFFICULT","FINAL CHALLENGE"][LEVELS.indexOf(current.level)+1]} UNLOCKED!`);else confetti(55);
 $("#gameArea").innerHTML=`<div class="final"><div class="trophy">${current.level==="boss"?"👑":"🏆"}</div><span class="eyebrow">MISSION COMPLETE</span><h2>${g.title} Complete!</h2><p>You used context clues to reason about unfamiliar words.</p><div class="result-grid"><div class="result-stat"><b>${current.score}</b><span>MISSION SCORE</span></div><div class="result-stat"><b>${acc}%</b><span>ACCURACY</span></div><div class="result-stat"><b>${current.streak}</b><span>FINAL STREAK</span></div></div><button class="btn primary" id="continue">${current.level==="boss"?"🎉 Finish Lesson":"🔓 Continue Journey"}</button><button class="btn ghost" id="again">Play Again</button></div>`;
 $("#continue").addEventListener("click",()=>{closeGame();if(current.level!=="boss")document.querySelector(`[data-level="${LEVELS[LEVELS.indexOf(current.level)+1]}"]`).scrollIntoView({behavior:"smooth",block:"center"});else{confetti(45);}});
 $("#again").addEventListener("click",()=>openGame(current.level));
}
function pulseScore(){const e=$("#gameScore");e.animate([{transform:"scale(1)"},{transform:"scale(1.35)"},{transform:"scale(1)"}],{duration:350})}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),2200)}
function confetti(n=20){const box=$("#confetti");for(let i=0;i<n;i++){const p=document.createElement("i");p.className="confetti-piece";p.style.left=Math.random()*100+"%";p.style.setProperty("--x",(Math.random()*240-120)+"px");p.style.background=["#d6a21f","#092d61","#5c8fc9","#e8c65c"][i%4];p.style.animationDelay=Math.random()*.3+"s";box.appendChild(p);setTimeout(()=>p.remove(),2000)}}
document.querySelectorAll("[data-scroll]").forEach(b=>b.addEventListener("click",()=>document.querySelector(b.dataset.scroll).scrollIntoView({behavior:"smooth"})));
document.querySelectorAll(".play").forEach(b=>b.addEventListener("click",()=>openGame(b.dataset.game)));
$("#close").addEventListener("click",closeGame);$("#modal").addEventListener("click",e=>{if(e.target.id==="modal")closeGame()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeGame()});updateUI();
