const $=id=>document.getElementById(id);
const sections=[...document.querySelectorAll('.screen')];
function openScreen(id){sections.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='quiz')renderQuestion();}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openScreen(b.dataset.open)));
$('beginBtn').addEventListener('click',()=>openScreen('study'));
$('englishBtn').addEventListener('click',()=>{const on=document.body.classList.toggle('show-english');$('englishBtn').textContent=`EN Support: ${on?'ON':'OFF'}`;document.querySelectorAll('.en').forEach(e=>e.classList.toggle('hidden',!on));});
document.querySelectorAll('.en').forEach(e=>e.classList.add('hidden'));
$('fullBtn').addEventListener('click',async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch(e){alert('Hindi suportado ang fullscreen sa browser na ito.');}});
let sound=false;$('soundBtn').addEventListener('click',()=>{sound=!sound;$('soundBtn').textContent=`Sound: ${sound?'ON':'OFF'}`;});
function ping(ok){if(!sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?660:220;g.gain.value=.04;o.start();o.stop(c.currentTime+.12);}catch(e){}}
const questions=[
{type:'MULTIPLE CHOICE',topic:'sayaw',q:'Alin sa mga sumusunod ang kabilang sa Aralin 9: Mga Katutubong Sayaw?',en:'Which is included in Lesson 9: Traditional Dances?',a:['Dandansoy','Sayaw sa Bangko','Pasyon'],c:1,h:'Hanapin ang pamagat na nasa listahan ng limang sayaw.',why:'Ang Sayaw sa Bangko ay isa sa limang sayaw sa pointer.'},
{type:'MULTIPLE CHOICE',topic:'sayaw',q:'Aling sayaw ang karaniwang gumagamit ng kawayan sa pagsasagawa nito?',en:'Which dance commonly uses bamboo in its performance?',a:['Tinikling','Pangalay','Pandanggo sa Ilaw'],c:0,h:'Isipin ang sayaw na kilala sa pag-iwas sa gumagalaw na kawayan.',why:'Ang Tinikling ay kilala sa paggamit ng mga kawayan.'},
{type:'MULTIPLE CHOICE',topic:'sayaw',q:'Aling sayaw ang gumagamit ng bao ng niyog?',en:'Which dance uses coconut shells?',a:['Maglalatik','Sayaw sa Bangko','Pangalay'],c:0,h:'Ang sagot ay ang sayaw na may kaugnayan sa salitang “latik.”',why:'Ang Maglalatik ay gumagamit ng bao ng niyog sa pagtatanghal.'},
{type:'MULTIPLE CHOICE',topic:'sayaw',q:'Aling sayaw ang may kaugnayan sa pagbalanse ng mga ilaw o kandila?',en:'Which dance is associated with balancing lights or candles?',a:['Tinikling','Pandanggo sa Ilaw','Sayaw sa Bangko'],c:1,h:'Nasa mismong pamagat ang salitang “Ilaw.”',why:'Ang Pandanggo sa Ilaw ay kaugnay ng pagbalanse ng mga ilaw o kandila.'},
{type:'MULTIPLE CHOICE',topic:'sayaw',q:'Alin ang kumpletong pangkat ng mga katutubong sayaw sa pointer?',en:'Which is the complete group of dances listed in the pointers?',a:['Dandansoy, Pasyon, Ti-Ti Tulong Anay','Tinikling, Maglalatik, Pangalay','Dandansoy, Atin Cu Pung Singsing, Pasyon'],c:1,h:'Pumili ng pangkat na puro sayaw, hindi kanta.',why:'Tinikling, Maglalatik, at Pangalay ay pawang nasa listahan ng sayaw.'},
{type:'MULTIPLE CHOICE',topic:'kanta',q:'Alin ang katutubong kanta na inilalarawan sa pahina 153 bilang awit ng mga taga-Pampanga na naglalahad ng kuwento?',en:'Which song is described on page 153 as a Kapampangan song that tells a story?',a:['Atin Cu Pung Singsing','Pasyon','Ti-Ti Tulong Anay'],c:0,h:'Ang pamagat ay may salitang “Singsing.”',why:'Ayon sa pahina 153, ang Atin Cu Pung Singsing ay awit ng mga taga-Pampanga na naglalahad ng kuwento.'},
{type:'MULTIPLE CHOICE',topic:'kanta',q:'Ayon sa pahina 156, ano ang kinukuwento ng Pasyon?',en:'According to page 156, what does the Pasyon narrate?',a:['Mga larong pambata','Buhay, pagpapakasakit, pagkamatay, at muling pagkabuhay ni Hesukristo','Mga hakbang sa isang katutubong sayaw'],c:1,h:'Tingnan ang paliwanag sa pahina 156 tungkol sa Mahal na Araw.',why:'Ito ang paliwanag na ibinigay sa pahina 156 ng aklat.'},
{type:'MULTIPLE CHOICE',topic:'kanta',q:'Ano ang tawag sa pag-awit ng Pasyon na isinasagawa tuwing Mahal na Araw?',en:'What is the chanting of the Pasyon during Holy Week called?',a:['Pabasa','Pangalay','Tinikling'],c:0,h:'Ang sagot ay nakasulat sa paliwanag sa pahina 156.',why:'Tinatawag itong “pabasa,” ayon sa aklat.'},
{type:'MULTIPLE CHOICE',topic:'kanta',q:'Alin ang tamang pangkat ng apat na katutubong kanta sa iyong pointer?',en:'Which group contains the four folk songs from your pointers?',a:['Sayaw sa Bangko, Maglalatik, Tinikling, Pangalay','Dandansoy, Atin Cu Pung Singsing, Ti-Ti Tulong Anay, Pasyon','Pandanggo sa Ilaw, Pasyon, Maglalatik, Dandansoy'],c:1,h:'Tandaan: apat ang kanta sa listahan.',why:'Ito ang apat na pamagat na nakalista sa pointer para sa Aralin 10.'},
{type:'MULTIPLE CHOICE',topic:'kultura',q:'Ano ang pangunahing layunin ng pag-aaral ng mga katutubong sayaw at kanta ayon sa mga panimula ng aralin?',en:'What is a key purpose of studying traditional dances and songs?',a:['Makilala at mapahalagahan ang lokal na sining at kultura','Palitan ang lahat ng makabagong sining','Isaulo lamang ang mga pamagat'],c:0,h:'Balikan ang “Panimula sa Aralin” sa mga pahina 142 at 152.',why:'Binibigyang-diin ng mga panimula ang pagkilala at pagpapahalaga sa lokal na sining at kultura.'},
{type:'PAG-UURI',topic:'sayaw',q:'Pag-uuri: Sayaw o Kanta? “Pangalay”',en:'Classify: Dance or Song? “Pangalay”',a:['Katutubong Sayaw','Katutubong Kanta','Hindi kabilang sa pointer'],c:0,h:'Ito ay nasa listahan ng Aralin 9.',why:'Ang Pangalay ay nakalista sa Aralin 9: Mga Katutubong Sayaw.'},
{type:'PAG-UURI',topic:'kanta',q:'Pag-uuri: Sayaw o Kanta? “Dandansoy”',en:'Classify: Dance or Song? “Dandansoy”',a:['Katutubong Sayaw','Katutubong Kanta','Hindi kabilang sa pointer'],c:1,h:'Ito ang awit na ipapakinggan at tatalakayin sa pahina 153.',why:'Ang Dandansoy ay nasa listahan ng Aralin 10: Mga Katutubong Kanta.'},
{type:'PAG-UURI',topic:'sayaw',q:'Pag-uuri: Sayaw o Kanta? “Pandanggo sa Ilaw”',en:'Classify: Dance or Song? “Pandanggo sa Ilaw”',a:['Katutubong Kanta','Katutubong Sayaw','Hindi kabilang sa pointer'],c:1,h:'Makikita ito sa listahan ng Aralin 9.',why:'Ang Pandanggo sa Ilaw ay kabilang sa mga katutubong sayaw sa pointer.'},
{type:'PAG-UURI',topic:'kanta',q:'Pag-uuri: Sayaw o Kanta? “Ti-Ti Tulong Anay”',en:'Classify: Dance or Song? “Ti-Ti Tulong Anay”',a:['Katutubong Sayaw','Katutubong Kanta','Hindi kabilang sa pointer'],c:1,h:'Ito ay nasa listahan ng Aralin 10.',why:'Ang Ti-Ti Tulong Anay ay isa sa apat na kantang nakalista sa pointer.'},
{type:'PAG-UURI',topic:'sayaw',q:'Pag-uuri: Sayaw o Kanta? “Sayaw sa Bangko”',en:'Classify: Dance or Song? “Sayaw sa Bangko”',a:['Katutubong Sayaw','Katutubong Kanta','Hindi kabilang sa pointer'],c:0,h:'Ang unang salita sa pamagat ay pahiwatig.',why:'Ang Sayaw sa Bangko ay kabilang sa Aralin 9.'},
{type:'TAMA O MALI',topic:'kanta',q:'Ayon sa pahina 157, ang mga katutubong awit ay maaaring magpahayag ng damdamin o maglahad ng kuwento.',en:'According to page 157, folk songs may express feelings or tell a story.',a:['Tama','Mali','Hindi matutukoy'],c:0,h:'Balikan ang mga bullet sa “Alalahanin Natin” sa pahina 157.',why:'Ito mismo ang ideyang binibigyang-diin sa pahina 157.'},
{type:'TAMA O MALI',topic:'kanta',q:'Ayon sa pahina 157, walang katutubong awit na kinakanta sa takdang panahon o okasyon.',en:'Page 157 says no folk songs are sung on particular occasions.',a:['Tama','Mali','Hindi matutukoy'],c:1,h:'May pahayag ang pahina 157 tungkol sa ilang awit at takdang panahon.',why:'Mali. Sinasabi ng pahina 157 na may mga awit na kinakanta sa takdang panahon o okasyon.'},
{type:'TAMA O MALI',topic:'sayaw',q:'Ang Aralin 9 ay naglalayong makilala ang ilang katutubong sayaw at mapahalagahan ang lokal na sining at kultura.',en:'Lesson 9 aims to identify traditional dances and value local art and culture.',a:['Tama','Mali','Hindi matutukoy'],c:0,h:'Balikan ang mga layunin sa pahina 142.',why:'Ito ang mga layuning nakasaad sa panimula ng Aralin 9.'},
{type:'TAMA O MALI',topic:'kanta',q:'Ayon sa pahina 153, ang Atin Cu Pung Singsing ay awit ng mga taga-Pampanga na naglalahad ng kuwento.',en:'Page 153 says Atin Cu Pung Singsing is a Kapampangan song that tells a story.',a:['Tama','Mali','Hindi matutukoy'],c:0,h:'Tingnan ang huling talata sa pahina 153.',why:'Tama. Ito ang nakasulat sa pahina 153.'},
{type:'TAMA O MALI',topic:'kanta',q:'Ang “pabasa” ay tawag sa isang katutubong sayaw na nasa Aralin 9.',en:'“Pabasa” is the name of a traditional dance in Lesson 9.',a:['Tama','Mali','Hindi matutukoy'],c:1,h:'Ang salitang ito ay ipinaliwanag sa bahagi tungkol sa Pasyon.',why:'Mali. Sa pahina 156, ang “pabasa” ay tumutukoy sa pag-awit ng Pasyon.'},
{type:'PAGKILALA',topic:'sayaw',q:'Anong sayaw ang may salitang “Bangko” sa pamagat?',en:'Which dance has “Bangko” in its title?',a:['Sayaw sa Bangko','Maglalatik','Tinikling'],c:0,h:'Makikita mismo ang sagot sa pamagat.',why:'Ang sagot ay Sayaw sa Bangko.'},
{type:'PAGKILALA',topic:'kanta',q:'Anong kanta ang may salitang “Singsing” sa pamagat?',en:'Which song has “Singsing” in its title?',a:['Dandansoy','Atin Cu Pung Singsing','Pasyon'],c:1,h:'Ang pamagat ay may tatlong salitang Kapampangan bago ang “Singsing.”',why:'Ang sagot ay Atin Cu Pung Singsing.'},
{type:'PAGKILALA',topic:'sayaw',q:'Alin sa mga sayaw ang may salitang “Ilaw” sa pamagat?',en:'Which dance has “Ilaw” in its title?',a:['Pangalay','Pandanggo sa Ilaw','Maglalatik'],c:1,h:'Basahin nang mabuti ang buong pamagat.',why:'Ang sagot ay Pandanggo sa Ilaw.'},
{type:'PAGKILALA',topic:'kanta',q:'Aling kanta ang iniuugnay sa “pabasa” tuwing Mahal na Araw?',en:'Which song is associated with the “pabasa” during Holy Week?',a:['Ti-Ti Tulong Anay','Dandansoy','Pasyon'],c:2,h:'Tingnan ang paliwanag sa pahina 156.',why:'Ang Pasyon ay inaawit sa gawaing tinatawag na pabasa.'},
{type:'HOTS • PAGLALAPAT',topic:'sayaw',q:'Gumagawa ang klase ng poster para sa Aralin 9. Aling pangkat ang dapat ilagay upang manatili sa mga pamagat ng pointer?',en:'Your class is making a poster for Lesson 9. Which group matches the pointers?',a:['Tinikling, Maglalatik, Pangalay','Dandansoy, Pasyon, Ti-Ti Tulong Anay','Atin Cu Pung Singsing, Dandansoy, Sayaw sa Bangko'],c:0,h:'Pumili ng tatlong pangalan na pawang sayaw.',why:'Ang Tinikling, Maglalatik, at Pangalay ay pawang nasa listahan ng Aralin 9.'},
{type:'HOTS • PAGLALAPAT',topic:'kanta',q:'Gagawa ka ng presentasyon tungkol sa Aralin 10. Aling pangkat ang angkop?',en:'You are making a presentation about Lesson 10. Which group is appropriate?',a:['Pandanggo sa Ilaw, Tinikling, Maglalatik','Dandansoy, Atin Cu Pung Singsing, Ti-Ti Tulong Anay, Pasyon','Sayaw sa Bangko, Pangalay, Tinikling'],c:1,h:'Ang Aralin 10 ay tungkol sa mga katutubong kanta.',why:'Ito ang apat na pamagat ng kanta sa pointer.'},
{type:'HOTS • PAGSUSURI',topic:'kultura',q:'May kaklase kang nagpalit ng mga pamagat ng sayaw at kanta sa kaniyang exhibit. Ano ang pinakamainam mong gawin?',en:'A classmate mixed up dance and song titles in an exhibit. What should you do?',a:['Hayaan dahil pare-pareho lang ang mga ito.','Tulungan siyang uriin ang mga pamagat at tiyakin ang detalye sa aklat.','Burahin ang buong proyekto.'],c:1,h:'Piliin ang sagot na tumutulong at sumusuri sa sanggunian.',why:'Ang tamang pag-uuri at pagtiyak sa aklat ay nakatutulong sa pagiging wasto ng exhibit.'},
{type:'HOTS • PAGSUSURI',topic:'kultura',q:'Bakit mahalagang alamin ang damdamin o kuwentong ipinahahayag ng isang katutubong awit?',en:'Why is it important to understand the feelings or story expressed in a folk song?',a:['Upang maunawaan ang kahulugan nito at ang kaugnayan sa pamayanan.','Upang mapalitan ang mga salita ng awit.','Upang hindi na kailangang makinig sa awit.'],c:0,h:'Balikan ang mga tanong sa pakikinig sa Dandansoy sa pahina 153.',why:'Tinatanong ng aklat ang tungkol sa kahulugan ng mga salita, paksa, at damdaming nararamdaman habang nakikinig.'},
{type:'HOTS • PAGPAPASYA',topic:'kultura',q:'Nais ng paaralan na magpakilala ng katutubong sayaw at kanta. Aling plano ang may pinakamalalim na pagkatuto?',en:'The school wants to introduce traditional dances and songs. Which plan supports deeper learning?',a:['Ipakita lamang ang mga pangalan.','Gumamit ng mapagkakatiwalaang sanggunian, ipaliwanag ang kahulugan, at hayaang magtanong ang mga mag-aaral.','Pumili ng mga detalye nang hindi sinusuri.'],c:1,h:'Piliin ang planong nagtuturo, nagpapaliwanag, at nagtataguyod ng mapanuring pagkatuto.',why:'Mas makabuluhan ang programang gumagamit ng sanggunian at nagpapalalim ng pag-unawa.'},
{type:'HOTS • PAGPAPAHALAGA',topic:'kultura',q:'May nagsabi na hindi na kailangang pag-aralan ang katutubong sining dahil may makabagong libangan. Ano ang pinakamainam na sagot?',en:'Someone says traditional arts no longer need to be studied because modern entertainment exists. What is the best response?',a:['Kalimutan na ang tradisyon.','Maaari nating tangkilikin ang makabago habang pinahahalagahan ang kulturang pamana.','Ang isang uri lamang ng sining ang mahalaga.'],c:1,h:'Isipin kung paano maaaring magsabay ang makabago at ang pagpapahalaga sa pamana.',why:'Maaaring pahalagahan ang mga bagong anyo ng libangan habang pinangangalagaan ang lokal na kultura.'},
{type:'HOTS • PAGPAPLANO',topic:'kultura',q:'Ikaw ang mamumuno sa proyektong pangkultura. Alin ang pinakamabisang hakbang?',en:'You lead a cultural project. Which action is most effective?',a:['Gumawa ng listahan nang walang pananaliksik.','Palitan ang mga pamagat upang madaling tandaan.','Magsaliksik sa aklat, maghanda ng presentasyon, at hikayatin ang paggalang sa lokal na sining.'],c:2,h:'Pumili ng hakbang na gumagamit ng sanggunian at aktibong pakikilahok.',why:'Ang pananaliksik, wastong presentasyon, at pagpapahalaga ay tumutulong sa pagpapanatili ng kultura.'},
{type:'HOTS • PAGLALAHAT',topic:'kultura',q:'Batay sa pahina 157, ano ang pinakamainam na paglalahat tungkol sa katutubong awit?',en:'Based on page 157, what is the best summary about folk songs?',a:['Wala itong kaugnayan sa wika o sining.','Maaari itong magpahayag ng damdamin, magkuwento, at magpakita ng sining at mga wikang Pilipino.','Lahat ng awit ay para sa iisang okasyon lamang.'],c:1,h:'Balikan ang apat na punto sa “Alalahanin Natin.”',why:'Ito ang buod ng mga ideya sa pahina 157.'},
{type:'HOTS • PAG-UUGNAY',topic:'kultura',q:'Paano mo maipakikita ang pagpapahalaga sa lokal na katutubong awit?',en:'How can you show appreciation for local folk songs?',a:['Makinig, alamin ang kahulugan, at ibahagi nang may paggalang ang natutuhan.','Gawing biro ang wika ng awit.','Huwag pansinin ang mga awit sa pamayanan.'],c:0,h:'Iugnay ang sagot sa layunin ng aralin na pahalagahan ang lokal na awit.',why:'Ang pakikinig, pag-unawa, at magalang na pagbabahagi ay paraan ng pagpapahalaga.'}
];
let current=0,answers=Array(questions.length).fill(null),revealed=new Set(),showHints=false;
function renderMap(){const map=$('questionMap');map.innerHTML='';questions.forEach((q,i)=>{const b=document.createElement('button');b.className='qmap'+(answers[i]!==null?' answered':'')+(i===current?' current':'');b.textContent=i+1;b.title=`Tanong ${i+1}`;b.addEventListener('click',()=>{current=i;renderQuestion()});map.appendChild(b)});const done=answers.filter(x=>x!==null).length;$('progressText').textContent=`${done} / ${questions.length}`;$('progressBar').style.width=`${done/questions.length*100}%`;}
function renderQuestion(){if(!$('questionText'))return;const q=questions[current];$('sectionTag').textContent=q.type;$('questionNum').textContent=`TANONG ${current+1} / ${questions.length}`;$('questionText').textContent=q.q;$('questionEn').textContent=q.en;$('questionEn').classList.toggle('hidden',!document.body.classList.contains('show-english'));$('feedback').className='feedback';$('feedback').textContent='';$('hintText').classList.add('hidden');$('hintText').textContent='💡 '+q.h;$('prevBtn').disabled=current===0;$('prevBtn').style.opacity=current===0?'.45':'1';$('nextBtn').textContent=current===questions.length-1?'Tingnan ang Resulta →':'Susunod →';const area=$('answerArea');area.innerHTML='';q.a.forEach((txt,i)=>{const b=document.createElement('button');b.className='answer-option';if(answers[current]===i)b.classList.add('selected');if(revealed.has(current)){if(i===q.c)b.classList.add('correct');else if(answers[current]===i)b.classList.add('wrong')}const letter=document.createElement('span');letter.className='letter';letter.textContent=String.fromCharCode(65+i);const text=document.createElement('span');text.textContent=txt;b.append(letter,text);b.addEventListener('click',()=>selectAnswer(i));area.appendChild(b)});if(revealed.has(current))showFeedback();renderMap();}
function selectAnswer(i){if(revealed.has(current))return;answers[current]=i;revealed.add(current);renderQuestion();const q=questions[current];const ok=i===q.c;ping(ok);}
function showFeedback(){const q=questions[current],ok=answers[current]===q.c;const fb=$('feedback');fb.className='feedback show '+(ok?'good':'bad');fb.textContent=(ok?'Tama! ':'Balikan natin. ')+q.why;}
$('prevBtn').addEventListener('click',()=>{if(current>0){current--;renderQuestion()}});$('nextBtn').addEventListener('click',()=>{if(current<questions.length-1){current++;renderQuestion()}else showResults()});$('hintBtn').addEventListener('click',()=>{$('hintText').classList.toggle('hidden')});$('finishBtn').addEventListener('click',showResults);$('retryBtn').addEventListener('click',resetQuiz);$('printBtn').addEventListener('click',()=>window.print());$('resetBtn').addEventListener('click',()=>{if(confirm('I-reset ang sagot at progress ng reviewer?'))resetQuiz(true)});$('resetBtn').title='I-reset ang reviewer';
function showResults(){const done=answers.filter(x=>x!==null).length;if(done<questions.length&&!confirm(`Nasagutan mo ang ${done} sa ${questions.length} tanong. Ipakita pa rin ang resulta?`)){return}const score=answers.reduce((s,a,i)=>s+(a===questions[i].c?1:0),0);const danceIds=questions.map((q,i)=>q.topic==='sayaw'?i:-1).filter(i=>i>=0),songIds=questions.map((q,i)=>q.topic==='kanta'?i:-1).filter(i=>i>=0);const d=danceIds.filter(i=>answers[i]===questions[i].c).length,s=songIds.filter(i=>answers[i]===questions[i].c).length;$('finalScore').textContent=score;$('finalPercent').textContent=Math.round(score/questions.length*100)+'%';$('danceCorrect').textContent=`${d}/${danceIds.length}`;$('songCorrect').textContent=`${s}/${songIds.length}`;$('resultMessage').textContent=score>=27?'Napakahusay! Balikan pa rin ang mga tanong na hindi nasagot nang tama.':score>=22?'Mahusay! Suriin ang mga item na kailangan pang balikan.':score>=16?'Magandang simula. Gamitin ang Memory Booster at subukan muli.':'Balikan muna ang mahahalagang ideya sa Memory Booster, pagkatapos ay subukan muli.';const misses=$('reviewMisses');misses.innerHTML='';questions.forEach((q,i)=>{if(answers[i]!==q.c){const div=document.createElement('div');div.className='miss-item';const strong=document.createElement('b');strong.textContent=`#${i+1} • ${q.type}`;const p=document.createElement('div');p.textContent=q.q;const ans=document.createElement('div');ans.textContent=`Tamang sagot: ${q.a[q.c]}`;ans.style.color='#14734f';div.append(strong,p,ans);misses.appendChild(div)}});if(!misses.children.length)misses.textContent='Walang maling sagot. Mahusay!';openScreen('results');try{localStorage.setItem('ap3_culturequest_latest',JSON.stringify({score,answers,at:new Date().toISOString()}))}catch(e){}}
function resetQuiz(goStudy=false){current=0;answers=Array(questions.length).fill(null);revealed.clear();renderQuestion();openScreen(goStudy?'home':'quiz')}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tabcontent').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));}));
// Restore progress safely in the same browser session only; scores are not used as a formal grade.
renderMap();
