const state={explore:0,quizScore:0,q:0};
const quiz=[
{q:"Alin ang halimbawa ng MATERIAL na kultura?",o:["Pagmamano","Barong Tagalog","Paggalang","Awiting-bayan"],a:1,e:"Ang Barong Tagalog ay isang bagay na nakikita at nahahawakan."},
{q:"Alin ang DI-MATERYAL na kultura?",o:["Bahay Kubo","Adobo","Pagmamano","Kasuotan"],a:2,e:"Ang pagmamano ay isang kaugalian na nagpapakita ng paggalang."},
{q:"Ano ang tawag sa kulturang makikita sa maraming lugar sa buong bansa?",o:["Lokal na kultura","Pambansang kultura","Personal na kultura","Pribadong kultura"],a:1,e:"Ang pambansang kultura ay makikita sa maraming lugar sa buong bansa."},
{q:"Alin ang maaaring makaimpluwensiya sa kultura?",o:["Kapaligiran","Kasaysayan","Pangkat ng tao","Lahat ng nabanggit"],a:3,e:"Lahat ng ito ay maaaring humubog sa kultura."},
{q:"Ang Buko Pie ay halimbawa ng lokal na kulturang nauugnay sa ______.",o:["Laguna","Sulu","Cebu","Davao"],a:0,e:"Kilala ang Laguna sa buko pie."},
{q:"Anong sayaw ang kilala sa Pangasinan?",o:["Pangalay","Sayaw sa Bangko","Sinulog","Tinikling"],a:1,e:"Ang Sayaw sa Bangko ay kilalang sayaw mula sa Pangasinan."},
{q:"Alin ang halimbawa ng di-materyal na kultura?",o:["Musika","Bahay","Pagkain","Kasuotan"],a:0,e:"Ang musika ay kabilang sa di-materyal na kultura."},
{q:"Bakit mahalagang pahalagahan ang kultura?",o:["Para makilala ang ating pagkakakilanlan","Para makalimutan ang nakaraan","Para maging pare-pareho ang lahat","Para mawala ang lokal na tradisyon"],a:0,e:"Ang kultura ay mahalagang bahagi ng ating pagkakakilanlan."}];
function startQuest(){document.getElementById('lesson').scrollIntoView({behavior:'smooth'});burst()}
function motivate(btn,type){document.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const t={pagkain:"🍚 Ang pagkain ay bahagi ng kultura dahil ipinapakita nito ang mga sangkap, paraan ng pagluluto at tradisyong minana natin.",damit:"👕 Ang kasuotan ay material na kultura. Maaari itong magpakita ng pagkakakilanlan at tradisyon ng isang pangkat.",kaugalian:"🤝 Ang mga kaugalian tulad ng pagmamano ay di-materyal na kultura at nagpapakita ng pagpapahalaga sa kapwa.",sining:"🎨 Ang sining, musika at sayaw ay mahalagang bahagi ng kultura at pagkakakilanlan ng pamayanan."};show('motivationResult',t[type])}
function classify(btn,type){if(btn.dataset.done)return;btn.dataset.done=true;if(btn.dataset.answer===type){btn.classList.add('correct');state.explore++;showToast("🎉 Tama!")}else{btn.classList.add('wrong');showToast("💡 Balikan ang dalawang uri ng kultura.")}document.getElementById('exploreScore').textContent=state.explore;if(state.explore===6){burst();showToast("🏆 Napakahusay! Natapos mo ang Explore!")}}
const places={"Laguna":"🥥 <strong>Laguna</strong> — Kilala sa buko pie. Ipinapakita nito kung paano nakaaapekto ang likas na yaman at mga produkto ng lugar sa kultura.","Negros Occidental":"🍠 <strong>Negros Occidental</strong> — Kilala sa tubo at mga produktong tulad ng piaya. Ang kapaligiran at agrikultura ay may malaking impluwensiya sa kultura.","Pangasinan":"💃 <strong>Pangasinan</strong> — Ang Sayaw sa Bangko ay isang halimbawa ng di-materyal na kultura na nagpapakita ng sining at tradisyon.","Sulu":"🕺 <strong>Sulu</strong> — Ang Pangalay ay isang katutubong sayaw ng mga Tausug at bahagi ng kanilang tradisyong pangkultura.","Cebu":"🎉 <strong>Cebu</strong> — Ang Sinulog ay isang pagdiriwang na may material at di-materyal na kultura gaya ng kasuotan, sayaw, musika at simbolo.","Davao":"🎵 <strong>Davao</strong> — May opisyal na awit na “Tayo ay Dabawenyo,” isang halimbawa ng sagisag ng lokal na pagkakakilanlan."};
function showPlace(p){document.getElementById('placeInfo').innerHTML=places[p]}
function loadQuiz(){const x=quiz[state.q];document.getElementById('qNum').textContent=state.q+1;document.getElementById('quizQuestion').textContent=x.q;const box=document.getElementById('quizOptions');box.innerHTML='';x.o.forEach((opt,i)=>{const b=document.createElement('button');b.textContent=String.fromCharCode(65+i)+". "+opt;b.onclick=()=>answerQuiz(b,i);box.appendChild(b)});document.getElementById('quizFeedback').textContent='';document.getElementById('nextBtn').classList.add('hidden')}
function answerQuiz(btn,i){const x=quiz[state.q],all=[...document.querySelectorAll('#quizOptions button')];all.forEach(b=>b.disabled=true);if(i===x.a){btn.classList.add('correct');state.quizScore++;document.getElementById('quizFeedback').textContent="🎉 Tama! "+x.e;burst()}else{btn.classList.add('wrong');all[x.a].classList.add('correct');document.getElementById('quizFeedback').textContent="💡 Hindi pa. "+x.e}document.getElementById('quizScore').textContent=state.quizScore;document.getElementById('nextBtn').classList.remove('hidden')}
function nextQuestion(){state.q++;if(state.q<quiz.length)loadQuiz();else{document.getElementById('quizQuestion').textContent=`🏆 Natapos mo ang Kultura Detective! Score: ${state.quizScore}/${quiz.length}`;document.getElementById('quizOptions').innerHTML=state.quizScore>=6?"🌟 Napakahusay! Isa kang tunay na Kultura Detective.":"💪 Magaling! Balikan ang lesson at subukan muli.";document.getElementById('quizFeedback').textContent="Tandaan: Ang kultura ay bahagi ng ating pagkakakilanlan.";document.getElementById('nextBtn').classList.add('hidden');burst()}}
function showReflection(){const a=document.getElementById('localCulture').value.trim(),b=document.getElementById('proudCulture').value.trim();if(!a||!b){show('reflectionResult',"✏️ Kumpletuhin muna ang dalawang sagot para maibahagi ang iyong ideya.");return}show('reflectionResult',`🌟 Ang iyong kultura: <strong>${esc(a)}</strong><br>❤️ Ipinagmamalaki mo ito dahil: <strong>${esc(b)}</strong><br><br>Napakahusay! Ang pagkilala at pagpapahalaga sa lokal na kultura ay paraan ng paggalang sa ating pagkakakilanlan.`);burst()}
function checkExit(){const v=['e1','e2','e3'].map(id=>document.getElementById(id).value.trim().toLowerCase());let p=0;if(v[0].length>=15)p++;if(v[1].includes('material')&&v[1].includes('di'))p++;if(v[2].length>=15)p++;const m=p===3?"🏅 Excellent! Kumpleto ang iyong Exit Ticket.":p===2?"👏 Magaling! May kaunting bahagi pang dapat linawin.":"💡 Balikan ang lesson at subukang sagutin muli.";show('exitResult',`${m} Nakumpleto: ${p}/3`);if(p===3)burst()}
function show(id,html){const e=document.getElementById(id);e.innerHTML=html;e.classList.remove('hidden')}function showToast(msg){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';Object.assign(t.style,{position:'fixed',bottom:'22px',left:'50%',transform:'translateX(-50%)',background:'#173f34',color:'white',padding:'12px 18px',borderRadius:'999px',zIndex:300,fontWeight:'700',boxShadow:'0 8px 25px rgba(0,0,0,.2)'});document.body.appendChild(t)}t.textContent=msg;t.style.opacity=1;clearTimeout(t.timer);t.timer=setTimeout(()=>t.style.opacity=0,1800)}function burst(){const box=document.getElementById('confetti');for(let i=0;i<35;i++){const c=document.createElement('i');c.className='confetti-piece';c.style.left=Math.random()*100+'%';c.style.top='-20px';c.style.background=['#f6c453','#df6d70','#4e8fc4','#55a774','#ef8b43'][i%5];c.style.animationDelay=Math.random()*.3+'s';box.appendChild(c);setTimeout(()=>c.remove(),2200)}}function esc(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;document.getElementById('progressBar').style.width=(scrollY/h*100)+'%'});loadQuiz();
