const screens=["home","engage","connect","explore","learn","guided","practice","think","review","check","master","reflect","celebrate"];
let practiceIndex=0, practiceScore=0, checkIndex=0, checkScore=0;
const practiceQs=[
 {q:"8 + 4 = 4 + 8 shows which property?",a:["Commutative","Associative","Identity"],c:0,e:"The addends change order, but the sum stays 12."},
 {q:"(5 + 7) + 3 = 5 + (7 + 3) shows which property?",a:["Identity","Associative","Commutative"],c:1,e:"The grouping changes, but the sum stays 15."},
 {q:"3 + 0 = 3 shows which property?",a:["Commutative","Identity","Associative"],c:1,e:"Adding zero leaves the number unchanged."},
 {q:"Which is an easier form of 8 + 5 + 2 + 5?",a:["(8 + 2) + (5 + 5)","8 + 5 + 2 + 5","(8 + 5) + (2 + 5)"],c:0,e:"Use the properties to make 10s: 10 + 10 = 20."},
 {q:"Find N: (13 + 15) + (7 + 5) = N",a:["30","40","45"],c:1,e:"13 + 7 = 20 and 15 + 5 = 20, so N = 40."},
 {q:"Which statement is true?",a:["Changing order can change the sum.","Changing grouping can change the sum.","Adding zero gives the same number."],c:2,e:"That is the identity property."}
];
const checkQs=[
 {q:"9 + 6 = 6 + 9",a:["Commutative","Associative","Identity"],c:0},
 {q:"(9 + 8) + 2 = 9 + (8 + 2)",a:["Identity","Associative","Commutative"],c:1},
 {q:"100 + 0 = 100",a:["Associative","Commutative","Identity"],c:2},
 {q:"Which expression makes an easy pair in 7 + 2 + 8 + 3 + 5?",a:["(7 + 3) + (2 + 8) + 5","7 + 2 + 8 + 3 + 5","(7 + 2) + (8 + 3) + 5"],c:0},
 {q:"Using properties, 23 + (5 + 9) + (11 + 7) can be reorganized to 30 + 20 + 5. What is N?",a:["45","55","65"],c:1}
];
function go(id){screens.forEach(s=>document.getElementById(s)?.classList.remove('active'));document.getElementById(id)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(id==='explore')showProp('comm',document.querySelector('.tab'));if(id==='practice')renderPractice();if(id==='check')renderCheck();if(id==='celebrate'){document.getElementById('finalPractice').textContent=practiceScore+'/'+practiceQs.length;document.getElementById('finalCheck').textContent=checkScore+'/'+checkQs.length}}
function pickEngage(btn,text){document.querySelectorAll('.equation-pair button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');const m=document.getElementById('engageMsg');m.className='feedback good';m.textContent='Both number sentences have the same sum: 12. Changing the order is the commutative property.'}
function feedback(btn,ok,id){const m=document.getElementById(id);m.className='feedback '+(ok?'good':'bad');m.textContent=ok?'Correct! You found the useful pair.':'Try again. Look for the pair that makes 10.'}
function showProp(type,btn){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');const p=document.getElementById('propPanel');const data={comm:{t:'Commutative Property',d:'Changing the order of the addends does not affect the sum.',f:'4 + 8 = 8 + 4',hint:'Order changes.'},assoc:{t:'Associative Property',d:'Changing the grouping of the addends does not affect the sum.',f:'(5 + 7) + 3 = 5 + (7 + 3)',hint:'Grouping changes.'},identity:{t:'Identity Property',d:'When zero is added to a number, the sum is the number itself.',f:'3 + 0 = 3',hint:'Zero changes nothing.'}}[type];p.innerHTML=`<h3>${data.t}</h3><p>${data.d}</p><div class="formula">${data.f}</div><div class="swap"><span>${data.hint}</span></div>`}
function guide(n,btn){document.querySelectorAll('.choice-wide').forEach(x=>x.disabled=true);const m=document.getElementById('guideMsg');if(n){m.className='feedback good';m.textContent='Excellent. The commutative property lets us change the order.';document.getElementById('guideReveal').classList.remove('hidden')}else{m.className='feedback bad';m.textContent='Not quite. We are changing the order/grouping, not the size of a number.';document.querySelectorAll('.choice-wide').forEach(x=>x.disabled=false);}}
function renderPractice(){const q=practiceQs[practiceIndex];const box=document.getElementById('practiceBox');box.innerHTML=`<div class="qnum">MISSION ${practiceIndex+1} OF ${practiceQs.length}</div><div class="question">${q.q}</div>${q.a.map((x,i)=>`<button class="option" onclick="answerPractice(${i})">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}<p id="practiceMsg" class="feedback"></p>`;document.getElementById('practiceProgress').style.width=(practiceIndex/practiceQs.length*100)+'%'}
function answerPractice(i){const q=practiceQs[practiceIndex];document.querySelectorAll('#practiceBox .option').forEach((b,j)=>{b.disabled=true;if(j===q.c)b.classList.add('correct');if(j===i&&i!==q.c)b.classList.add('wrong')});const m=document.getElementById('practiceMsg');if(i===q.c){practiceScore++;m.className='feedback good';m.textContent='Correct! '+q.e}else{m.className='feedback bad';m.textContent='Let’s learn: '+q.e}setTimeout(()=>{practiceIndex=(practiceIndex+1)%practiceQs.length;renderPractice()},900)}
function renderCheck(){const q=checkQs[checkIndex];document.getElementById('checkBox').innerHTML=`<div class="qnum">CHECK ${checkIndex+1} OF ${checkQs.length}</div><div class="question">${q.q}</div>${q.a.map((x,i)=>`<button class="option" onclick="answerCheck(${i})">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}<p id="checkMsg" class="feedback"></p>`;document.getElementById('checkProgress').style.width=(checkIndex/checkQs.length*100)+'%'}
function answerCheck(i){const q=checkQs[checkIndex];document.querySelectorAll('#checkBox .option').forEach((b,j)=>{b.disabled=true;if(j===q.c)b.classList.add('correct');if(j===i&&i!==q.c)b.classList.add('wrong')});const m=document.getElementById('checkMsg');m.className='feedback '+(i===q.c?'good':'bad');m.textContent=i===q.c?'Correct!':'Review the property map and try the next one.';if(i===q.c)checkScore++;setTimeout(()=>{if(checkIndex<checkQs.length-1){checkIndex++;renderCheck()}else{m.textContent=`Check complete: ${checkScore}/${checkQs.length}.`;document.getElementById('checkProgress').style.width='100%'}},900)}
function masterAnswer(btn,ok){const m=document.getElementById('masterMsg');m.className='feedback '+(ok?'good':'bad');m.textContent=ok?'Great grouping! You made 10 + 10 + 10 = 30.':'Look for pairs that make 10. Try grouping 6+4, 7+3, and 2+8.';if(ok)document.getElementById('master2').classList.remove('hidden')}
function master2(btn,ok){const m=document.getElementById('master2Msg');m.className='feedback '+(ok?'good':'bad');m.textContent=ok?'Correct! 13+15+7+5 = 40.':'Add the two groups: 28 + 12 = 40.'}
function reflect(btn){document.querySelectorAll('.reflect-grid button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');document.getElementById('reflectMsg').className='feedback good';document.getElementById('reflectMsg').textContent='Good reflection. Explaining your strategy helps make mathematical thinking visible.'}
function celebrate(){if(!document.querySelector('.reflect-grid button.selected')){document.getElementById('reflectMsg').className='feedback bad';document.getElementById('reflectMsg').textContent='Choose a property first, then complete the lesson.';return}go('celebrate')}
document.getElementById('fsBtn').addEventListener('click',async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(e){document.body.classList.toggle('pseudo-fullscreen')}});
showProp('comm',document.querySelector('.tab'));
