const dances=[
 {name:'Tinikling',place:'—',desc:'Ginagamit ang mga kawayan. Iniiwasan ng mananayaw ang paa ng kawayan habang sumasayaw.',img:'assets/lesson-page-1921.jpg'},
 {name:'Sayaw sa Bangko',place:'Pangasinan',desc:'Sinasayaw sa mga bangko. Pumapatong at sumasayaw ang mga mananayaw sa ibabaw ng bangko.',img:'assets/lesson-page-1922.jpg'},
 {name:'Maglalatik',place:'CALABARZON',desc:'Ginagamit ng mga lalaki ang bao ng niyog na isinusuot sa iba’t ibang bahagi ng katawan. Pinapalo ang mga bao upang makagawa ng tunog.',img:'assets/lesson-page-1922.jpg'},
 {name:'Pandanggo sa Ilaw',place:'—',desc:'Gumagamit ang mga mananayaw ng mga basong nilagyan ng kandila at binabalanse ang mga ito habang gumagalaw.',img:'assets/lesson-page-1923.jpg'},
 {name:'Pangalay',place:'—',desc:'Isa sa mga pangalang kabilang sa mga katutubong sayaw na dapat makilala at mapahalagahan.',img:null}
];
const qs={quick:[['Ang mga katutubong sayaw ay mahalagang bahagi ng ____ ng isang pamayanan.',['pagkakakilanlan','trapiko','panahon'],0]],
guided:[['May kawayan na pinagdadaanan ng mga mananayaw. Anong sayaw?',['Tinikling','Maglalatik','Pangalay'],0],['May mga bangko at umaapak/sumasayaw dito ang mga mananayaw.',['Sayaw sa Bangko','Pandanggo sa Ilaw','Tinikling'],0],['May bao ng niyog na ginagamit upang makagawa ng tunog.',['Maglalatik','Pangalay','Sayaw sa Bangko'],0]],
your:[['Anong sayaw ang kilala sa Pangasinan?',['Sayaw sa Bangko','Tinikling','Pangalay'],0],['Anong sayaw ang iniuugnay sa CALABARZON sa aralin?',['Maglalatik','Pandanggo sa Ilaw','Tinikling'],0],['Anong sayaw ang gumagamit ng basong may kandila?',['Pandanggo sa Ilaw','Maglalatik','Tinikling'],0],['Alin ang halimbawa ng katutubong sayaw?',['Tinikling','Basketball','Swimming'],0]],
challenge:[['Si Ana ay naghahanda para sa pista. May kawayan na ginagamit sa sayaw. Ano ang dapat niyang kilalanin?',['Tinikling','Pangalay','Maglalatik'],0],['Bakit mahalagang mapanatili ang mga katutubong sayaw?',['Bahagi sila ng kultura at pagkakakilanlan ng pamayanan.','Para palitan ang lahat ng tradisyon.','Dahil laro lamang sila.'],0],['Alin ang pinakamahusay na halimbawa ng pagpapahalaga sa katutubong sayaw?',['Pag-aaral at paggalang sa tradisyon ng pamayanan.','Pagtawa sa mga mananayaw.','Paglimot sa pangalan ng sayaw.'],0],['May sayaw na bahagi ng pista ng isang bayan. Ano ang ipinapakita nito?',['Ang sayaw ay maaaring bahagi ng pagdiriwang ng pamayanan.','Walang kaugnayan ang sayaw sa kultura.','Ang lahat ng sayaw ay pare-pareho.'],0]]};
const finalQs=[...qs.your,...qs.challenge,['Ang Sayaw sa Bangko ay iniuugnay sa anong lalawigan sa aralin?',['Pangasinan','Leyte','Sulu'],0],['Ang Tinikling ay gumagamit ng anong kagamitan?',['Kawayan','Bangko','Bao ng niyog'],0]];
let stars=Number(localStorage.getItem('ap3l9stars')||0), sound=true, currentGuided=0,currentYT=0,currentCh=0,currentFinal=0, finalScore=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('ap3l9stars',stars);$('#starsTop').textContent='⭐ '+stars}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function go(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'}); if(id==='games')renderGame(); if(id==='master')updateMaster()}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
$('#soundBtn').addEventListener('click',()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇'});
$('#fsBtn').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.());
function addStar(n=1){stars+=n;save();toast('⭐ +'+n+' Star!')}
function renderChoices(container, question, onAnswer){container.innerHTML='';question[1].forEach((txt,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=String.fromCharCode(65+i)+'. '+txt;b.addEventListener('click',()=>onAnswer(i,b));container.appendChild(b)})}
function lock(container){container.querySelectorAll('button').forEach(b=>b.disabled=true)}
function setupQuick(){const q=qs.quick[0];renderChoices($('#quickCheck'),q,(i,b)=>{lock($('#quickCheck'));if(i===q[2]){b.classList.add('correct');$('#quickFeedback').textContent='🎉 Tama! Ang katutubong sayaw ay bahagi ng kultura at pagkakakilanlan.';$('#quickFeedback').className='feedback good';addStar()}else{b.classList.add('wrong');$('#quickFeedback').textContent='💡 Isipin: ang sayaw ay nagpapakita ng kultura at pagkakakilanlan.';$('#quickFeedback').className='feedback try'}})}
function renderDances(){$('#danceCards').innerHTML=dances.map(d=>`<article class="dance-card">${d.img?`<img src="${d.img}" alt="Larawan mula sa aralin: ${d.name}">`:`<div class="dance-placeholder">💃</div>`}<span class="tag">${d.place==='—'?'🇵🇭 Katutubong sayaw':'📍 '+d.place}</span><h3>${d.name}</h3><p>${d.desc}</p><p class="english">English support: A traditional dance named <b>${d.name}</b>.</p></article>`).join('')}
function guided(){const q=qs.guided[currentGuided];$('#guidedQuestion').textContent=q[0];$('#guidedFeedback').textContent='';$('#guidedFeedback').className='feedback';$('#guidedNext').classList.add('hidden');renderChoices($('#guidedChoices'),q,(i,b)=>{if(i===q[2]){b.classList.add('correct');lock($('#guidedChoices'));$('#guidedFeedback').textContent='🌟 Good thinking! Tama ang sagot.';$('#guidedFeedback').className='feedback good';addStar();$('#guidedNext').classList.remove('hidden')}else{b.classList.add('wrong');$('#guidedFeedback').textContent='💡 Balikan ang clue. Tingnan ang kagamitan o lugar na binanggit.';$('#guidedFeedback').className='feedback try';b.classList.remove('wrong')}})}
$('#guidedNext').addEventListener('click',()=>{currentGuided++;if(currentGuided<qs.guided.length)guided();else{$('#guidedQuestion').textContent='🎉 Natapos natin ang guided practice!';$('#guidedChoices').innerHTML='';$('#guidedFeedback').textContent='Handa ka na para sa independent practice.';$('#guidedNext').classList.add('hidden');$('#toYourTurn').disabled=false}});
$('#toYourTurn').addEventListener('click',()=>go('yourTurn'));
function your(){const q=qs.your[currentYT];$('#ytQuestion').textContent=q[0];$('#ytFeedback').textContent='';$('#ytFeedback').className='feedback';$('#hintText').textContent='';$('#hintBtn').disabled=false;$('#ytNext').classList.add('hidden');renderChoices($('#ytChoices'),q,(i,b)=>{if(i===q[2]){b.classList.add('correct');lock($('#ytChoices'));$('#ytFeedback').textContent='🎯 Excellent!';$('#ytFeedback').className='feedback good';$('#ytScore').textContent=Number($('#ytScore').textContent)+1;addStar();$('#ytNext').classList.remove('hidden')}else{b.classList.add('wrong');$('#ytFeedback').textContent='💡 Try again. Use the clue from the lesson.';$('#ytFeedback').className='feedback try';b.classList.remove('wrong')}})}
$('#hintBtn').addEventListener('click',()=>{$('#hintText').textContent= currentYT===0?'Hint: Isipin ang lalawigang binanggit sa Watch Me.':currentYT===1?'Hint: Ang sayaw na ito ay may bao ng niyog.':currentYT===2?'Hint: May ilaw/kandila sa pangalan at paraan ng sayaw.':'Hint: Isa ito sa limang sayaw na pinag-aralan natin.';$('#hintBtn').disabled=true});
$('#ytNext').addEventListener('click',()=>{currentYT++;if(currentYT<qs.your.length)your();else go('games')});
function renderGame(){renderIdentify()}
$$('.game-tab').forEach(b=>b.addEventListener('click',()=>{$$('.game-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.game==='identify')renderIdentify();if(b.dataset.game==='match')renderMatch();if(b.dataset.game==='sort')renderSort();if(b.dataset.game==='memory')renderMemory()}));
let identifyIndex=0,matchSelected=null,matchDone=0;
function renderIdentify(){const d=dances[identifyIndex%5];$('#gameArea').innerHTML=`<div class="game-panel"><div class="question-tag">🔎 IDENTIFY IT</div><h3>Aling sayaw ang inilalarawan?</h3><p>${d.desc}</p><div class="choices" id="idChoices"></div><div id="idFeedback" class="feedback"></div></div>`;const opts=[d.name,...dances.filter(x=>x.name!==d.name).sort(()=>Math.random()-.5).slice(0,2).map(x=>x.name)].sort(()=>Math.random()-.5);opts.forEach(t=>{const b=document.createElement('button');b.className='choice';b.textContent=t;b.addEventListener('click',()=>{if(t===d.name){b.classList.add('correct');$('#idFeedback').textContent='🎉 Tama!';$('#idFeedback').className='feedback good';addStar();identifyIndex++;setTimeout(renderIdentify,650)}else{b.classList.add('wrong');$('#idFeedback').textContent='💡 Basahin muli ang clue.';$('#idFeedback').className='feedback try'}});$('#idChoices').appendChild(b)})}
function renderMatch(){matchSelected=null;matchDone=0;const shuffled=[...dances].sort(()=>Math.random()-.5);$('#gameArea').innerHTML=`<div class="game-panel"><div class="question-tag">🧩 MATCH IT</div><p>Tap ang sayaw, pagkatapos tap ang tamang clue.</p><div class="match-grid"><div id="matchNames"></div><div id="matchClues"></div></div><div id="matchFeedback" class="feedback"></div></div>`;const n=$('#matchNames'),c=$('#matchClues');dances.forEach(d=>{const b=document.createElement('button');b.className='match-item';b.textContent=d.name;b.dataset.name=d.name;b.addEventListener('click',()=>{if(b.classList.contains('matched'))return;$$('.match-item').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');matchSelected=d.name});n.appendChild(b)});shuffled.forEach(d=>{const b=document.createElement('button');b.className='match-item';b.textContent=d.place+' — '+d.desc;b.dataset.name=d.name;b.addEventListener('click',()=>{if(!matchSelected)return toast('Pumili muna ng sayaw.');if(b.dataset.name===matchSelected){b.classList.add('matched');const nb=n.querySelector(`[data-name="${CSS.escape(matchSelected)}"]`);nb.classList.add('matched');nb.classList.remove('selected');matchSelected=null;matchDone++;addStar();$('#matchFeedback').textContent='✅ Match!';if(matchDone===5){$('#matchFeedback').textContent='🏆 Perfect! Natapos mo ang Match It.';toast('🏆 Match It complete!')}}else{$('#matchFeedback').textContent='💡 Hindi pa tugma. Tingnan ang lugar at clue.';$('#matchFeedback').className='feedback try'}});c.appendChild(b)})}
function renderSort(){const items=[{t:'Tinikling',cat:'Katutubong sayaw'},{t:'Sayaw sa Bangko',cat:'Katutubong sayaw'},{t:'Pangalay',cat:'Katutubong sayaw'},{t:'Basketball',cat:'Hindi katutubong sayaw'},{t:'Swimming',cat:'Hindi katutubong sayaw'}].sort(()=>Math.random()-.5);$('#gameArea').innerHTML=`<div class="game-panel"><div class="question-tag">🗂️ SORT IT</div><p>Tap ang item, pagkatapos tap ang tamang pangkat.</p><div class="sort-grid"><div><h3>Items</h3><div id="sortItems"></div></div><div><h3>Mga Pangkat</h3><button class="drop-zone" data-cat="Katutubong sayaw">🇵🇭 Katutubong Sayaw</button><button class="drop-zone" data-cat="Hindi katutubong sayaw" style="margin-top:10px">📦 Hindi Katutubong Sayaw</button></div></div><div id="sortFeedback" class="feedback"></div></div>`;let selected=null;items.forEach(x=>{const b=document.createElement('button');b.className='sort-item';b.textContent=x.t;b.dataset.cat=x.cat;b.addEventListener('click',()=>{if(b.disabled)return;document.querySelectorAll('.sort-item').forEach(z=>z.classList.remove('selected'));b.classList.add('selected');selected=b});$('#sortItems').appendChild(b)});document.querySelectorAll('.drop-zone').forEach(z=>z.addEventListener('click',()=>{if(!selected){toast('Pumili muna ng item.');return}if(selected.dataset.cat===z.dataset.cat){selected.disabled=true;selected.classList.remove('selected');selected.style.opacity='.4';addStar();$('#sortFeedback').textContent='✅ Tama! '+selected.textContent+' ay nasa tamang pangkat.';$('#sortFeedback').className='feedback good';selected=null}else{$('#sortFeedback').textContent='💡 Hindi pa tama. Isipin kung ang item ay katutubong sayaw.';$('#sortFeedback').className='feedback try'}}))} 
function renderMemory(){const pairs=[['Tinikling','Kawayan'],['Sayaw sa Bangko','Pangasinan'],['Maglalatik','Bao ng niyog'],['Pandanggo sa Ilaw','Kandila']];const cards=[];pairs.forEach((p,i)=>{cards.push({id:i,text:p[0]});cards.push({id:i,text:p[1]})});cards.sort(()=>Math.random()-.5);$('#gameArea').innerHTML=`<div class="game-panel"><div class="question-tag">🧠 MEMORY MATCH</div><p>Hanapin ang pares: sayaw + kaugnay na clue.</p><div class="memory-grid" id="memoryGrid"></div><div id="memoryFeedback" class="feedback"></div></div>`;let first=null,busy=false,done=0;cards.forEach(c=>{const b=document.createElement('button');b.className='memory-card';b.textContent='❓';b.dataset.id=c.id;b.dataset.text=c.text;b.addEventListener('click',()=>{if(busy||b.classList.contains('done')||b===first)return;b.classList.add('revealed');b.textContent=c.text;if(!first){first=b;return}busy=true;if(first.dataset.id===b.dataset.id){first.classList.add('done');b.classList.add('done');done++;addStar();$('#memoryFeedback').textContent='🎉 Magkapareha!';first=null;busy=false;if(done===pairs.length)$('#memoryFeedback').textContent='🏆 Memory Master!'}else{setTimeout(()=>{first.classList.remove('revealed');b.classList.remove('revealed');first.textContent='❓';b.textContent='❓';first=null;busy=false},700)}});$('#memoryGrid').appendChild(b)})}
function challenge(){const q=qs.challenge[currentCh];$('#challengeQuestion').textContent=q[0];$('#challengeFeedback').textContent='';$('#challengeFeedback').className='feedback';$('#challengeNext').classList.add('hidden');renderChoices($('#challengeChoices'),q,(i,b)=>{if(i===q[2]){b.classList.add('correct');lock($('#challengeChoices'));$('#challengeFeedback').textContent='🧠 Great application!';$('#challengeFeedback').className='feedback good';addStar();$('#challengeNext').classList.remove('hidden')}else{b.classList.add('wrong');$('#challengeFeedback').textContent='💡 Balikan ang ideya: kultura, pamayanan, at katutubong sayaw.';$('#challengeFeedback').className='feedback try'}})}
$('#challengeNext').addEventListener('click',()=>{currentCh++;if(currentCh<qs.challenge.length)challenge();else go('master')});
function updateMaster(){$('#finalStars').textContent=stars;$('#finalPercent').textContent=finalScore?Math.round(finalScore/finalQs.length*100)+'%':'0%'}
$('#startFinal').addEventListener('click',()=>{currentFinal=0;finalScore=0;$('#startFinal').classList.add('hidden');$('#finalArea').classList.remove('hidden');$('#results').classList.add('hidden');finalQuestion()});
function finalQuestion(){const q=finalQs[currentFinal];$('#finalQuestion').textContent=(currentFinal+1)+'. '+q[0];$('#finalFeedback').textContent='';$('#finalFeedback').className='feedback';$('#finalNext').classList.add('hidden');renderChoices($('#finalChoices'),q,(i,b)=>{lock($('#finalChoices'));if(i===q[2]){b.classList.add('correct');finalScore++;addStar();$('#finalFeedback').textContent='🌟 Tama!';$('#finalFeedback').className='feedback good'}else{b.classList.add('wrong');$('#finalFeedback').textContent='💡 Review the clue and remember what you learned.';$('#finalFeedback').className='feedback try'}$('#finalNext').classList.remove('hidden')})}
$('#finalNext').addEventListener('click',()=>{currentFinal++;if(currentFinal<finalQs.length)finalQuestion();else finishFinal()});
function finishFinal(){const pct=Math.round(finalScore/finalQs.length*100);$('#finalArea').classList.add('hidden');$('#results').classList.remove('hidden');let title=pct>=90?'🏆 Lesson Master!':pct>=80?'🌟 Almost There!':pct>=70?'👍 Good Progress!':'🌱 Keep Practicing!';$('#results').innerHTML=`<div class="result-score">${finalScore} / ${finalQs.length}</div><h2>${title}</h2><p>You scored <b>${pct}%</b>. ${pct>=80?'Mahusay! I-review pa ang mga clue para mas tumibay ang iyong kaalaman.':'Balikan ang Learn at Watch Me, pagkatapos subukan muli.'}</p>`;$('#retryFinal').classList.remove('hidden');updateMaster();toast('🎉 Final Challenge complete!')}
$('#retryFinal').addEventListener('click',()=>{$('#retryFinal').classList.add('hidden');$('#results').classList.add('hidden');$('#startFinal').classList.remove('hidden');$('#startFinal').click()});
setupQuick();renderDances();guided();your();challenge();save();
