const stations = [
 {id:'food',name:'Mystery Food',icon:'🍎',short:'Investigate food using more than one sense.',question:'You are eating a fruit. Which sense organs can work together to help you notice its color, smell, and taste?',choices:['Eyes + Nose + Tongue','Ears + Skin','Eyes + Ears'],answer:0,clue:'Your eyes see the food, your nose smells it, and your tongue tastes it.'},
 {id:'read',name:'Read & Listen',icon:'📖',short:'See words and hear a reader.',question:'A teacher reads a story while you look at the book. Which sense organs work together?',choices:['Eyes + Ears','Nose + Tongue','Skin + Tongue'],answer:0,clue:"Your eyes see the words and pictures. Your ears hear the teacher's voice."},
 {id:'touch',name:'Touch Detective',icon:'🧸',short:'Discover an object by feeling it.',question:'You place your hand on a covered object and feel that it is rough. Which sense organ gives you this touch information?',choices:['Skin','Nose','Tongue'],answer:0,clue:'The skin helps you feel textures such as rough and smooth. In the real activity, use safe objects.'},
 {id:'sound',name:'Sound Detective',icon:'🔊',short:'Listen and connect the sound to what you see.',question:'You see a musical instrument and hear its sound. Which sense organs work together?',choices:['Eyes + Ears','Nose + Tongue','Skin + Nose'],answer:0,clue:'Your eyes help you see the instrument, while your ears hear the sound.'},
 {id:'safety',name:'Safety Mission',icon:'🚦',short:'Use your senses to stay safe.',question:'When crossing a street, which two sense organs work together to help you notice vehicles?',choices:['Eyes + Ears','Nose + Tongue','Skin + Nose'],answer:0,clue:'Your eyes see vehicles and your ears hear vehicle sounds. These warning signals can help keep you safe.'}
];
let state=JSON.parse(localStorage.getItem('senseDetectivesState')||'null')||{score:0,done:[],sound:true,name:'',section:''};
let current=null, locked=false;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('senseDetectivesState',JSON.stringify(state));}
function tone(freq=650,duration=.08){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.08,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+duration);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+duration+.02)}catch(e){}}
function renderStations(){
 $('stationGrid').innerHTML=stations.map((s,i)=>{const done=state.done.includes(s.id);return `<article class="station ${done?'done':''}"><div class="emoji">${s.icon}</div><h3>Station ${i+1}: ${s.name}</h3><p>${s.short}</p><button data-open="${s.id}">${done?'✓ Completed — Replay':'Start Mission →'}</button></article>`}).join('');
 document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openStation(b.dataset.open)));
 updateProgress();renderRecord();
}
function updateProgress(){const n=state.done.length; $('score').textContent=state.score; $('progressText').textContent=`${n} of 5 stations complete`; $('progressBar').style.width=`${n*20}%`; if(n===5){$('finalMessage').textContent='Amazing work! You completed every station and investigated how sense organs work together.';$('badgeArea').innerHTML='<span class="badge">🏆 Sense Organ Super Detective</span>';$('finalSection').classList.add('final-complete')}else{$('finalMessage').textContent='Complete all five stations to unlock your final badge.';$('badgeArea').innerHTML='';$('finalSection').classList.remove('final-complete')}}
function renderRecord(){const name=state.name||'________________';const rows=stations.map((s,i)=>`<tr><td>${i+1}. ${s.name}</td><td>${state.done.includes(s.id)?'<span class="done-dot">⭐</span> Complete':'☐ Mission not yet complete'}</td></tr>`).join('');$('recordTable').innerHTML=`<table><thead><tr><th>Mission</th><th>Detective Record</th></tr></thead><tbody>${rows}</tbody></table>`}
function openStation(id){current=stations.find(s=>s.id===id);locked=false;$('stationTag').textContent=`STATION ${stations.indexOf(current)+1} OF 5`;$('stationTitle').textContent=`${current.icon} ${current.name}`;renderQuestion();$('workspace').hidden=false;$('workspace').scrollIntoView({behavior:'smooth',block:'start'})}
function renderQuestion(){const c=current; $('stationContent').innerHTML=`<div class="activity-card"><div class="visual"><span class="sense-chip">👀 Eyes</span><span class="sense-chip">👂 Ears</span><span class="sense-chip">👃 Nose</span><span class="sense-chip">👅 Tongue</span><span class="sense-chip">🖐️ Skin</span></div><p class="scenario"><b>Detective Case:</b> ${c.question}</p><div class="choices">${c.choices.map((x,i)=>`<button class="choice" data-choice="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}</div><div id="feedback"></div></div>`;document.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.choice))));}
function answer(index){if(locked)return;locked=true;const ok=index===current.answer;document.querySelectorAll('[data-choice]').forEach((b,i)=>{if(i===current.answer)b.classList.add('correct');if(i===index&&!ok)b.classList.add('wrong')});const f=$('feedback');f.className='feedback '+(ok?'good':'bad');if(ok){state.score+=20;if(!state.done.includes(current.id))state.done.push(current.id);tone(880,.13);f.innerHTML=`🎉 <b>Correct, Detective!</b> ${current.clue}`;}else{tone(220,.15);f.innerHTML=`💡 <b>Good try!</b> The answer is <b>${current.choices[current.answer]}</b>. ${current.clue}`}save();renderStations();setTimeout(()=>{f.innerHTML+=`<div class="next-row"><button class="next" id="nextBtn">${state.done.length===5?'View My Badge 🏆':'Next Mission →'}</button></div>`;$('nextBtn').addEventListener('click',()=>{const next=stations.find(s=>!state.done.includes(s.id));if(next)openStation(next.id);else{$('finalSection').scrollIntoView({behavior:'smooth'});$('workspace').hidden=true;}})},350)}
$('startBtn').addEventListener('click',()=>{$('stations').scrollIntoView({behavior:'smooth'})});$('howBtn').addEventListener('click',()=>{$('howPanel').hidden=false;$('howPanel').scrollIntoView({behavior:'smooth'})});$('closeHow').addEventListener('click',()=>{$('howPanel').hidden=true});$('closeStation').addEventListener('click',()=>{$('workspace').hidden=true});$('soundBtn').addEventListener('click',()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'🔊 Sound':'🔇 Sound Off';save()});$('resetBtn').addEventListener('click',()=>{if(confirm('Reset your detective progress?')){state={score:0,done:[],sound:state.sound,name:'',section:''};save();$('studentName').value='';$('studentSection').value='';renderStations()}});$('printBtn').addEventListener('click',()=>window.print());$('studentName').addEventListener('input',e=>{state.name=e.target.value;save()});$('studentSection').addEventListener('input',e=>{state.section=e.target.value;save()});
$('studentName').value=state.name||'';$('studentSection').value=state.section||'';if(!state.sound)$('soundBtn').textContent='🔇 Sound Off';renderStations();
