let matchIndex=0, matchScore=0, sentenceScore=0, sentenceDone=0;
const matchItems=[
 {q:"You see the color of a leaf.",a:"eyes",opts:["eyes","ears","nose"]},
 {q:"You hear a bell.",a:"ears",opts:["nose","ears","fingers"]},
 {q:"You smell a flower.",a:"nose",opts:["mouth","nose","eyes"]},
 {q:"You taste a lemon.",a:"mouth",opts:["mouth","ears","eyes"]},
 {q:"You feel a rough rock.",a:"fingers",opts:["eyes","fingers","nose"]}
];
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'});}
function speakText(text){if(!text)return;if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.rate=.9;speechSynthesis.speak(u)}}
function chooseRoutine(btn,type){document.querySelectorAll('[data-answer] button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');document.getElementById(type+'Msg').textContent="Great! You shared your answer. 🌟"}
function emotion(e){document.getElementById('emotionMsg').textContent="You feel "+e+" today. Thank you for sharing! 😊"}
function renderMatch(){let x=matchItems[matchIndex];document.getElementById('matchGame').innerHTML=`<h3>${x.q}</h3><div class="game-options">${x.opts.map(o=>`<button onclick="matchAnswer(this,'${o}','${x.a}')">${o}</button>`).join('')}</div>`}
function matchAnswer(btn,ans,correct){let all=document.querySelectorAll('#matchGame button');all.forEach(b=>b.disabled=true);if(ans===correct){matchScore++;btn.textContent="✅ "+ans}else{btn.textContent="❌ Try again";all.forEach(b=>{if(b.textContent.trim()===correct)b.textContent="✅ "+correct})}document.getElementById('matchScore').textContent=`Score: ${matchScore} / 5`;matchIndex++;setTimeout(()=>{if(matchIndex<matchItems.length)renderMatch();else document.getElementById('matchGame').innerHTML=`<h3>🌟 Amazing! You finished the Sense Match.</h3><p>You matched ${matchScore} out of 5 correctly.</p><button class="primary" onclick="matchIndex=0;matchScore=0;renderMatch();document.getElementById('matchScore').textContent='Score: 0 / 5'">Play Again</button>`},750)}
function observeAnswer(btn,correct,item){let key=btn.innerText.toLowerCase();let ok=(correct==="eyes"&&key.includes("apple"))||(correct==="nose"&&key.includes("flower"))||(correct==="ears"&&key.includes("music"))||(correct==="fingers"&&key.includes("eraser"))||(correct==="mouth"&&key.includes("food"));document.getElementById('observeMsg').textContent=ok?"✅ Excellent observation! You chose the sense that helps you answer the question.":"Think again. Read the question and ask: Which sense gives me that information?";document.getElementById('observeMsg').style.background=ok?"#e8f3e8":"#fff0d8"}
function showObject(o){const prompts={leaf:"A dry leaf may look brown or green. It may feel dry or rough and can make a sound when moved.",'fresh leaf':"A fresh leaf may be green. It can feel smooth or soft. Observe it carefully.",eraser:"An eraser can have a shape and color. Touch it safely and describe its texture.",'scented marker':"A scented marker has a color and may have a smell. Smell it gently; never taste it."};document.getElementById('objectPrompt').innerHTML=`🔎 <b>${o[0].toUpperCase()+o.slice(1)}:</b> ${prompts[o]}`}
function answerQuestion(btn,correct){btn.parentElement.querySelectorAll('button').forEach(b=>b.disabled=true);btn.textContent=(correct?"✅ ":"❌ ")+btn.textContent}
function vocabQuiz(btn,correct){document.querySelectorAll('.mini-quiz button').forEach(b=>b.disabled=true);document.getElementById('vocabMsg').textContent=correct?"🌟 Correct! OBSERVE means to look closely and notice information.":"Not quite. Try to remember: a scientist looks closely to OBSERVE."}
function sentenceAnswer(btn,correct){btn.parentElement.querySelectorAll('button').forEach(b=>b.disabled=true);btn.textContent=(correct?"✅ ":"❌ ")+btn.textContent;if(correct)sentenceScore++;sentenceDone++;document.getElementById('sentenceScore').textContent=`Score: ${sentenceScore} / 5`}
function chooseCommunicate(btn){document.querySelectorAll('.choices.large button').forEach(b=>b.classList.remove('chosen'));btn.classList.add('chosen');document.getElementById('commMsg').textContent=`Say it aloud: “In science, we ${btn.textContent}.”`;speakText(`In science, we ${btn.textContent}.`)}
const prompts={1:"Draw an object. Write or copy: “I see a ______.”",2:"Write two sentences using I see / I hear / I smell / I feel.",3:"Describe an object using two senses. Example: “I see a green leaf. I feel a soft leaf.”",4:"Explain how two senses help you observe one object.",5:"Write 3–4 sentences explaining how your senses help you learn in science."};
function setGrade(g){document.getElementById('gradePrompt').textContent=prompts[g]}
function saveWriting(){let v=document.getElementById('writingArea').value.trim();if(v){localStorage.setItem('learningJungleScienceWriting',v);document.getElementById('saveMsg').textContent="💾 Your writing is saved on this device."; }else document.getElementById('saveMsg').textContent="Write something first!"}
function clearWriting(){document.getElementById('writingArea').value="";document.getElementById('saveMsg').textContent=""}
function completeMission(){localStorage.setItem('scienceMissionComplete','yes');document.getElementById('missionMsg').innerHTML="<p>🎉 Fantastic work, Young Scientist! Your mission is complete!</p>"} 
window.addEventListener('load',()=>{renderMatch();let saved=localStorage.getItem('learningJungleScienceWriting');if(saved)document.getElementById('writingArea').value=saved;if(localStorage.getItem('scienceMissionComplete'))document.getElementById('missionMsg').innerHTML="<p>🌟 Mission badge earned on this device!</p>"});
