const lessons={
1:{title:"Day 1 — Meet the Pyramid",phase:"I — INTRODUCE + L — LEARN",target:"Identify the parts of a pyramid and distinguish its base, apex, perpendicular height, and slant edges.",intro:"A pyramid is a solid with one polygonal base and triangular faces that meet at one common point called the apex. The base does not have to be a square or rectangle. It may be a triangle, pentagon, hexagon, or another polygon. The volume tells us how much three-dimensional space is inside the solid.",steps:["Identify the polygon at the bottom: this is the base.","Find the single point where the triangular faces meet: this is the apex.","Measure the perpendicular distance from the apex to the base: this is the height h.","Find the area of the base: call it B.","Use V = ⅓Bh once B and h are known."],examples:[["Triangular pyramid","The base is a triangle.","A triangular pyramid has 4 triangular faces in total: one base and three side faces."],["Pentagonal pyramid","The base is a pentagon.","Its side faces are triangles meeting at the apex."],["Height vs. slant edge","Use perpendicular height h.","The formula requires the perpendicular height, not a sloping edge."],["Base area","B means area of the base.","If the base is a triangle, use B = ½bh for that triangle." ]],tasks:[["The point where the triangular faces meet is the:",["base","apex","height"],1],["The height h is the:",["slant edge","perimeter","perpendicular distance to the base"],2],["A pyramid with a triangular base is called a:",["triangular pyramid","rectangular prism","cylinder"],0],["In V = ⅓Bh, B represents:",["base area","base perimeter","side length"],0]]},
2:{title:"Day 2 — Discover and Derive the Formula",phase:"I — INTRODUCE + L — LEARN",target:"Explain inductively why the volume of a pyramid is one-third of the volume of a matching prism and derive V = ⅓Bh.",intro:"Think of a prism and a pyramid that have the same base area B and the same perpendicular height h. The prism fills the entire column. A pyramid tapers from its base toward one apex. A classical decomposition of a prism shows that three congruent pyramidal regions can account for the prism's volume. Therefore one such pyramid has one-third of the prism's volume.",steps:["Start with the prism formula V = Bh.","Relate the pyramid to a matching prism with the same base area and height.","Use the one-third relationship: pyramid volume = ⅓ × prism volume.","Substitute Bh for prism volume.","Simplify to obtain V = ⅓Bh."],examples:[["Prism volume","B = 30 cm², h = 9 cm","Vprism = Bh = 30(9) = 270 cm³."],["One-third relationship","Same B and h","Vpyramid = ⅓(270) = 90 cm³."],["Direct derivation","Vpyramid = ⅓Vprism","= ⅓(Bh) = ⅓Bh."],["Meaning of ⅓","The pyramid has one-third the volume of its matching prism.","The factor ⅓ is not optional; it is part of the formula." ]],tasks:[["Which formula is correct?",["V = Bh","V = ⅓Bh","V = 3Bh"],1],["If a matching prism has volume 300 cm³, the pyramid volume is:",["100 cm³","150 cm³","900 cm³"],0],["In the derivation, the prism volume is:",["Bh","⅓Bh","B+h"],0],["The factor ⅓ tells us the pyramid is what fraction of the matching prism?",["one-half","one-third","three-fourths"],1]]},
3:{title:"Day 3 — Find the Area of the Base",phase:"L — LEARN + A — APPLY",target:"Calculate the base area B for triangular, parallelogram, and regular polygon bases before finding pyramid volume.",intro:"The formula V = ⅓Bh has two important measurements: B and h. B is not a side length—it is an AREA. So before finding volume, you may need to calculate the area of the polygon that forms the base. The correct base-area formula depends on the shape.",steps:["Identify the shape of the base.","Write the appropriate area formula.","Substitute the base measurements.","Calculate B with square units.","Use B and the pyramid's perpendicular height in V = ⅓Bh."],examples:[["Triangle base","base = 12 cm, triangle height = 5 cm","B = ½(12)(5) = 30 cm²."],["Parallelogram base","base = 8 m, perpendicular height = 6 m","B = 8(6) = 48 m²."],["Regular pentagon base","perimeter = 30 cm, apothem = 4 cm","B = ½Pa = ½(30)(4) = 60 cm²."],["Composite workflow","Triangle base area = 24 cm²; pyramid height = 10 cm","V = ⅓(24)(10) = 80 cm³." ]],tasks:[["A triangular base has b=10 cm and h=6 cm. B =",["30 cm²","60 cm²","16 cm²"],0],["A parallelogram base is 7 m by 4 m. B =",["11 m²","28 m²","56 m²"],1],["If B = 25 cm² and h = 12 cm, V =",["100 cm³","300 cm³","⅓00 cm³"],0],["Which unit belongs to base area?",["cm","cm²","cm³"],1]]},
4:{title:"Day 4 — Find the Volume",phase:"A — APPLY",target:"Find the volume of pyramids with different polygonal bases and show complete solutions with correct cubic units.",intro:"Now combine the skills. First find the area of the base. Then identify the perpendicular height. Finally substitute into V = ⅓Bh. Keep the units consistent throughout the solution and report volume in cubic units.",steps:["Write the formula V = ⅓Bh.","Calculate or identify B.","Identify the perpendicular height h.","Substitute the values.","Multiply B and h, divide by 3, and write cubic units."],examples:[["Example 1 — triangular base","B = 36 cm², h = 15 cm","V = ⅓(36)(15) = 180 cm³."],["Example 2 — pentagonal base","B = 50 m², h = 9 m","V = ⅓(50)(9) = 150 m³."],["Example 3 — hexagonal base","B = 72 cm², h = 10 cm","V = ⅓(72)(10) = 240 cm³."],["Example 4 — reverse thinking","V = 120 cm³, B = 30 cm²","120 = ⅓(30)h → 120 = 10h → h = 12 cm." ]],tasks:[["B=45 cm² and h=8 cm. V =",["120 cm³","360 cm³","53 cm³"],0],["B=60 m² and h=12 m. V =",["240 m³","720 m³","180 m³"],0],["B=27 cm² and h=9 cm. V =",["81 cm³","27 cm³","243 cm³"],1],["If B=24 cm², h=15 cm, V =",["120 cm³","180 cm³","360 cm³"],0]]},
5:{title:"Day 5 — Solve Real-Life Pyramid Problems",phase:"A — APPLY + W — WRAP-UP",target:"Solve multi-step and real-life problems involving the volumes of pyramids and explain the solution.",intro:"Real problems may not give B directly. You may first need to find the area of a triangular, pentagonal, or other polygonal base. Read carefully, identify what is known, and choose the correct formula. A strong solution includes the formula, substitution, calculation, units, and a sentence answering the question.",steps:["Read the problem and identify the solid.","List the known measurements and units.","Find the base area B if it is not given.","Use the perpendicular height h.","Apply V = ⅓Bh and state the answer with cubic units."],examples:[["Roof model","A pyramid-shaped roof has base area 84 m² and height 6 m.","V = ⅓(84)(6) = 168 m³."],["Display monument","Base area = 120 ft² and height = 15 ft.","V = ⅓(120)(15) = 600 ft³."],["Triangular base first","Triangle base = 10 cm, triangle height = 8 cm; pyramid h = 12 cm.","B = ½(10)(8)=40 cm²; V=⅓(40)(12)=160 cm³."],["Check your answer","If the matching prism would be 900 cm³, pyramid volume should be one-third.","900 ÷ 3 = 300 cm³. This is a useful reasonableness check." ]],tasks:[["A pyramid has B=90 m² and h=12 m. Volume?",["360 m³","1,080 m³","270 m³"],0],["A triangular base has b=14 cm, triangle height=6 cm, pyramid h=15 cm. Volume?",["210 cm³","420 cm³","630 cm³"],0],["A matching prism has V=1,200 cm³. Pyramid V =",["400 cm³","600 cm³","3,600 cm³"],0],["Best final unit for pyramid volume:",["m","m²","m³"],2],["Which height should be used?",["perpendicular height","any slant edge","base perimeter"],0]]}
};

let completed=new Set(JSON.parse(localStorage.getItem("g8PyramidWeek1")||"[]"));
const area=document.getElementById("lessonArea");
const tabs=[...document.querySelectorAll(".day-tab")];

function renderDay(day){
 const l=lessons[day];
 area.innerHTML=`<article class="lesson-card">
 <div class="lesson-head"><div><span class="phase">${l.phase}</span><h3>${l.title}</h3></div><b>Day ${day} of 5 • Week 1</b></div>
 <div class="progress"><i style="width:${completed.has(day)?100:0}%"></i></div>
 <div class="target"><b>🎯 Learning Target:</b> ${l.target}</div>
 <div class="explain"><b>Teacher Ed explains:</b><br>${l.intro}</div>
 <h3>🪜 Step-by-Step Method</h3><div class="step-list">${l.steps.map(s=>`<div>${s}</div>`).join("")}</div>
 <div class="number-box"><b>🔎 Remember the structure</b><div class="base-demo"><div><div class="shape2"></div><small>Polygonal base → area B</small></div><div class="arrowbig">× h ÷ 3 →</div><div><div class="pyr-small"></div><small>Pyramid → volume V</small></div></div></div>
 <h3>📚 Worked Examples</h3><div class="example-grid">${l.examples.map(e=>`<div class="example"><h4>${e[0]}</h4><div class="math">${e[1]}</div><p class="why">${e[2]}</p></div>`).join("")}</div>
 <div class="mistake"><b>⭐ Common mistake:</b> Do not use a slant edge as h unless the problem explicitly shows that it is the perpendicular height. Also remember: area uses square units; volume uses cubic units.</div>
 <div class="practice"><h3>🎮 Interactive Practice</h3>${l.tasks.map((t,i)=>`<div class="task"><p class="question">${i+1}. ${t[0]}</p><div class="choices">${t[1].map((c,j)=>`<button type="button" class="choice" data-q="${day}-${i}" data-correct="${j===t[2]}">${c}</button>`).join("")}</div><div class="feedback" id="fb-${day}-${i}"></div></div>`).join("")}
 <button type="button" class="complete" id="completeDay">✓ Mark Day ${day} Complete</button></div></article>`;
 area.querySelectorAll(".choice").forEach(btn=>btn.addEventListener("click",()=>{
  const key=btn.dataset.q, fb=document.getElementById("fb-"+key);
  area.querySelectorAll(`[data-q="${key}"]`).forEach(b=>b.classList.remove("correct","wrong"));
  if(btn.dataset.correct==="true"){btn.classList.add("correct");fb.textContent="✅ Correct! Nice mathematical thinking."}
  else{btn.classList.add("wrong");fb.textContent="❌ Try again. Check the formula, base area, or number-line-style reasoning shown in the examples."}
 }));
 document.getElementById("completeDay").addEventListener("click",()=>{completed.add(day);localStorage.setItem("g8PyramidWeek1",JSON.stringify([...completed]));renderDay(day)});
 tabs.forEach(t=>t.classList.toggle("active",+t.dataset.day===day));
}
tabs.forEach(t=>t.addEventListener("click",()=>renderDay(+t.dataset.day)));
renderDay(1);

const quizData=[
["A pyramid has base area 42 cm² and height 9 cm. What is its volume?",["126 cm³","378 cm³","14 cm³"],0],
["What does B mean in V = ⅓Bh?",["base area","base length","base perimeter"],0],
["What does h represent?",["slant edge","perpendicular height","base area"],1],
["A matching prism has volume 600 m³. The pyramid volume is:",["200 m³","300 m³","1,800 m³"],0],
["A triangular base has b=12 cm and triangle height=7 cm. Its area is:",["42 cm²","84 cm²","19 cm²"],0],
["If B=48 cm² and h=15 cm, V =",["240 cm³","720 cm³","360 cm³"],0],
["If V=150 cm³ and B=30 cm², h =",["5 cm","10 cm","15 cm"],1],
["Which unit is appropriate for volume?",["cm","cm²","cm³"],2],
["A pentagonal pyramid has B=80 m² and h=6 m. V =",["160 m³","480 m³","240 m³"],0],
["Why is there a ⅓ in the formula?",["A pyramid is one-third the volume of a matching prism.","The base is one-third of a triangle.","Height is always divided by three."],0],
["A pyramid has B=100 ft² and h=12 ft. V =",["400 ft³","1,200 ft³","300 ft³"],0],
["A student uses a slant edge instead of perpendicular height. What should be corrected?",["Use the perpendicular height.","Multiply by 3.","Use base perimeter."],0]
];
function renderQuiz(){
 const q=document.getElementById("quiz");
 q.innerHTML=`<div class="quiz-card"><form id="quizForm">${quizData.map((x,i)=>`<div class="quiz-item"><b>${i+1}. ${x[0]}</b>${x[1].map((c,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${c}</label>`).join("")}</div>`).join("")}<button class="check" type="submit">Check My Week 1 Score</button><div id="quizResult" class="quiz-result"></div></form></div>`;
 document.getElementById("quizForm").addEventListener("submit",e=>{e.preventDefault();let s=0;quizData.forEach((x,i)=>{let a=document.querySelector(`input[name="q${i}"]:checked`);if(a&&+a.value===x[2])s++});let msg=s>=10?"🏆 Excellent! You are ready for more challenging pyramid problems.":s>=8?"🌟 Great job! Review any items you missed.":s>=6?"👍 Good progress! Revisit the formula derivation and worked examples.":"💪 Keep practicing! Work through Days 1–5 again, then retry.";document.getElementById("quizResult").textContent=`Score: ${s}/12 — ${msg}`});
}
renderQuiz();

const fs=document.getElementById("fullscreenBtn");
fs.addEventListener("click",async()=>{try{if(!document.fullscreenElement){await document.documentElement.requestFullscreen();document.body.classList.add("fullscreen-mode");fs.innerHTML="⛶ <span>Exit Full Screen</span>"}else{await document.exitFullscreen()}}catch(e){alert("Full Screen could not be activated. Please use a modern browser or allow full-screen access.")}});
document.addEventListener("fullscreenchange",()=>{if(!document.fullscreenElement){document.body.classList.remove("fullscreen-mode");fs.innerHTML="⛶ <span>Full Screen</span>"}});
document.getElementById("menuBtn").addEventListener("click",()=>document.querySelector(".nav").classList.toggle("open"));
