const KEY='teacherEd_AP3_L5_resources_v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state=JSON.parse(localStorage.getItem(KEY)||'{}');
state.stars??=0; state.badges??=[]; state.bestScore??=0; state.completed??=[]; state.missed??=[];
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state)); updateStats(); updateProgress()};
function updateStats(){$('#starCount').textContent=state.stars;$('#badgeCount').textContent=state.badges.length;$('#bestScore').textContent=state.bestScore+'%'}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function award(n){state.stars+=n;save()}
function complete(id){if(!state.completed.includes(id)){state.completed.push(id);award(1)}else save()}
function updateProgress(){const total=10, done=Math.min(total,state.completed.length);const pct=Math.round(done/total*100);$('#progressBar').style.width=pct+'%';$('#progressText').textContent=pct+'% complete';$$('.journey-step').forEach((b,i)=>{b.classList.toggle('done',i<Math.ceil(done/2));})}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.go)?.scrollIntoView({behavior:'smooth'})));
$('#menuBtn').addEventListener('click',()=>{let n=$('#mainNav');n.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',n.classList.contains('open'))});
$('#continueBtn').addEventListener('click',()=>document.querySelector('#'+(state.completed.at(-1)||'connect')).scrollIntoView({behavior:'smooth'}));
updateStats();updateProgress();

function choiceButtons(container,items,onPick){container.innerHTML='';items.forEach((x,i)=>{let b=document.createElement('button');b.className='choice';b.textContent=x.label??x;b.addEventListener('click',()=>onPick(x,i,b));container.appendChild(b)})}
choiceButtons($('#connectChoices'),['Yamang Lupa','Yamang Tubig','Yamang Mineral'],(x,_,b)=>{const ok=x==='Yamang Tubig';$('#connectFeedback').textContent=ok?'⭐ Tama! Ang likas na yaman ay maaaring mula sa lupa o tubig.':'💡 Mag-isip muli: ang likas na yaman ay mga produktong nakukuha mula sa anyong lupa at anyong tubig.';$('#connectFeedback').className='feedback '+(ok?'good':'try');if(ok){complete('connect');b.disabled=true}});
choiceButtons($('#guidedChoices'),['Yamang Lupa','Yamang Gubat','Yamang Tubig'],(x,_,b)=>{const ok=x==='Yamang Tubig';$('#guidedFeedback').textContent=ok?'🎉 Tama! Ang isda ay yamang tubig.':'💡 Balikan ang clue: dagat, ilog, o lawa.';$('#guidedFeedback').className='feedback '+(ok?'good':'try');if(ok){complete('model');b.disabled=true}});

const practice=[
 {q:'Alin ang halimbawa ng yamang lupa?',a:['Bigas','Isda','Ginto','Perlas'],c:0,h:'Isipin ang produktong mula sa sakahan.'},
 {q:'Alin ang halimbawa ng yamang gubat?',a:['Marmol','Agila','Perlas','Bigas'],c:1,h:'Ang gubat ay tahanan ng mga punongkahoy at hayop.'},
 {q:'Alin ang yamang mineral?',a:['Ginto','Isda','Gulay','Korales'],c:0,h:'Ang mga mineral ay matatagpuan sa ilalim ng lupa.'},
 {q:'Saan matatagpuan ang yamang tubig?',a:['Sa dagat, ilog, at lawa','Sa sakahan lamang','Sa ilalim ng lupa lamang','Sa bundok lamang'],c:0,h:'Hanapin ang clue tungkol sa mga anyong tubig.'},
 {q:'Alin ang tamang pangangalaga sa tubig?',a:['Gamitin ang baso kapag nagsesepilyo','Hayaan ang gripo na bukas','Magsayang ng tubig','Itapon ang basura sa ilog'],c:0,h:'Isang simpleng paraan ng pagtitipid ang paggamit ng baso sa pagsesepilyo.'},
 {q:'Alin ang HINDI halimbawa ng yamang mineral?',a:['Diyamante','Bakal','Marmol','Isda'],c:3,h:'Ang isda ay nakukuha sa anyong tubig.'}
];
let pi=0,ps=0,answered=false;
function renderPractice(){let q=practice[pi];$('#practiceNum').textContent=(pi+1)+' / '+practice.length;$('#practiceScore').textContent=ps+' / '+pi;$('#practiceQuestion').textContent=q.q;$('#practiceChoices').innerHTML='';$('#practiceFeedback').textContent='';$('#practiceFeedback').className='feedback';$('#practiceHintText').classList.add('hidden');$('#nextPractice').classList.add('hidden');answered=false;q.a.forEach((a,i)=>{let b=document.createElement('button');b.className='answer';b.textContent=a;b.onclick=()=>answerPractice(i,b);$('#practiceChoices').appendChild(b)})}
function answerPractice(i,b){if(answered)return;answered=true;let q=practice[pi];$$('#practiceChoices .answer').forEach(x=>x.disabled=true);if(i===q.c){b.classList.add('correct');ps++;award(1);$('#practiceFeedback').textContent='🌟 Excellent! Tama ang iyong pag-iisip.';$('#practiceFeedback').className='feedback good'}else{b.classList.add('incorrect');state.missed.push(q.q);save();$('#practiceFeedback').textContent='💡 Let’s think again. '+q.h;$('#practiceFeedback').className='feedback try'}$('#practiceScore').textContent=ps+' / '+(pi+1);$('#nextPractice').classList.remove('hidden');complete('practice')}
$('#practiceHint').onclick=()=>{$('#practiceHintText').textContent='💡 '+practice[pi].h;$('#practiceHintText').classList.remove('hidden')};$('#nextPractice').onclick=()=>{pi++;if(pi<practice.length)renderPractice();else{$('#practiceQuestion').textContent='🎉 Natapos mo ang guided independent practice!';$('#practiceChoices').innerHTML='';$('#nextPractice').classList.add('hidden')}};renderPractice();

const quick=[
 {q:'Ginto ay kabilang sa…',a:['Yamang mineral','Yamang tubig','Yamang lupa','Yamang gubat'],c:0},
 {q:'Isda ay kabilang sa…',a:['Yamang gubat','Yamang tubig','Yamang mineral','Yamang lupa'],c:1},
 {q:'Bigas ay halimbawa ng…',a:['Yamang lupa','Yamang tubig','Yamang gubat','Yamang mineral'],c:0},
 {q:'Agila ay halimbawa ng hayop na matatagpuan sa…',a:['Yamang tubig','Yamang gubat','Yamang mineral','Yamang lupa'],c:1}
];let qi=0,qgScore=0;
function renderQuick(){let q=quick[qi%quick.length];$('#quickGameQ').innerHTML='<div class="question">'+q.q+'</div>';$('#quickGameChoices').innerHTML='';$('#quickGameFeedback').textContent='';q.a.forEach((a,i)=>{let b=document.createElement('button');b.className='answer';b.textContent=a;b.onclick=()=>{if(i===q.c){b.classList.add('correct');qgScore++;award(1);$('#quickGameFeedback').textContent='🎯 Tama!';$('#quickGameFeedback').className='feedback good';}else{$('#quickGameFeedback').textContent='💡 '+q.a[q.c]+' ang tamang sagot.';$('#quickGameFeedback').className='feedback try'}setTimeout(()=>{qi++;renderQuick()},650);complete('quickGame')}});}
renderQuick();

let matchCards=[],first=null,lock=false,matched=0;
function initMemory(){const pairs=[['🌾','Bigas'],['🌳','Agila'],['💎','Ginto'],['🐟','Isda']];matchCards=[...pairs.flatMap((p,i)=>[{id:i,text:p[0],type:'icon'},{id:i,text:p[1],type:'word'}])].sort(()=>Math.random()-.5);first=null;lock=false;matched=0;let g=$('#memoryGrid');g.innerHTML='';matchCards.forEach((c,i)=>{let b=document.createElement('button');b.className='memory-card';b.textContent='?';b.onclick=()=>flipMemory(i,b);g.appendChild(b)})}
function flipMemory(i,b){if(lock||b.classList.contains('flipped')||b.classList.contains('matched'))return;b.textContent=matchCards[i].text;b.classList.add('flipped');if(first===null){first=i;return}let j=first;lock=true;if(matchCards[j].id===matchCards[i].id&&matchCards[j].type!==matchCards[i].type){setTimeout(()=>{$$('#memoryGrid .memory-card')[j].classList.add('matched');b.classList.add('matched');matched++;award(1);$('#memoryFeedback').textContent='🧠 Match!';$('#memoryFeedback').className='feedback good';first=null;lock=false;if(matched===4){complete('memory');toast('Memory Master!')}} ,350)}else{setTimeout(()=>{$$('#memoryGrid .memory-card')[j].textContent='?';b.textContent='?';$$('#memoryGrid .memory-card')[j].classList.remove('flipped');b.classList.remove('flipped');$('#memoryFeedback').textContent='💡 Hindi magkapareha. Subukan muli.';$('#memoryFeedback').className='feedback try';first=null;lock=false},650)}}
$('#resetMemory').onclick=initMemory;initMemory();

const sortData=[['Yamang Lupa',['Bigas','Gulay']],['Yamang Gubat',['Agila','Usa']],['Yamang Mineral',['Ginto','Bakal']],['Yamang Tubig',['Isda','Perlas']]];let selectedGroup=null,placed={};
function initSort(){selectedGroup=null;placed={};$('#sortGroups').innerHTML='';$('#sortItems').innerHTML='';sortData.forEach((g,i)=>{let b=document.createElement('button');b.className='sort-group';b.textContent=g[0];b.onclick=()=>{$$('.sort-group').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedGroup=g[0]};$('#sortGroups').appendChild(b);g[1].forEach(item=>{let x=document.createElement('button');x.className='sort-item';x.textContent=item;x.dataset.group=g[0];x.onclick=()=>{if(!selectedGroup){$('#sortFeedback').textContent='💡 Piliin muna ang grupo.';return}if(selectedGroup===x.dataset.group){x.classList.add('placed');x.disabled=true;placed[item]=true;award(1);$('#sortFeedback').textContent='✅ Tama! '+item+' → '+selectedGroup;$('#sortFeedback').className='feedback good';if(Object.keys(placed).length===8){complete('sort');toast('Sorting Star!')}}else{$('#sortFeedback').textContent='💡 Tingnan kung saan ito nagmumula.';$('#sortFeedback').className='feedback try'}};$('#sortItems').appendChild(x)})})}
$('#resetSort').onclick=initSort;initSort();

const orderCorrect=['I-save ang tubig','Gamitin muli ang maaari pang gamitin','I-segregate ang basura','Makilahok sa paglilinis o pagtatanim ng puno'];
function initOrder(){let arr=[...orderCorrect].sort(()=>Math.random()-.5);$('#orderItems').innerHTML='';arr.forEach((t,i)=>{let row=document.createElement('div');row.className='order-item';row.dataset.val=t;row.innerHTML='<strong class="ord-num">'+(i+1)+'</strong><span style="flex:1">'+t+'</span><button aria-label="Up">↑</button><button aria-label="Down">↓</button>';row.querySelectorAll('button')[0].onclick=()=>moveOrder(row,-1);row.querySelectorAll('button')[1].onclick=()=>moveOrder(row,1);$('#orderItems').appendChild(row)});$('#orderFeedback').textContent=''}
function moveOrder(row,dir){let sib=dir<0?row.previousElementSibling:row.nextElementSibling;if(!sib)return;dir<0?row.parentNode.insertBefore(row,sib):row.parentNode.insertBefore(sib,row);$$('#orderItems .order-item').forEach((x,i)=>x.querySelector('.ord-num').textContent=i+1)}
$('#checkOrder').onclick=()=>{let arr=$$('#orderItems .order-item').map(x=>x.dataset.val);let ok=arr.every((x,i)=>x===orderCorrect[i]);$('#orderFeedback').textContent=ok?'🏆 Perfect! Naayos mo ang wastong pagkakasunod-sunod.':'💡 Halos! Isipin ang sunod-sunod na hakbang at subukan muli.';$('#orderFeedback').className='feedback '+(ok?'good':'try');if(ok){award(3);complete('order')}};$('#resetOrder').onclick=initOrder;initOrder();

const spiral=[['Alin ang yamang tubig?',['Isda','Ginto','Agila','Bigas'],0],['Alin ang yamang mineral?',['Gulay','Perlas','Bakal','Usa'],2],['Alin ang mula sa sakahan?',['Bigas','Korales','Ginto','Agila'],0],['Alin ang tamang pangangalaga?',['Magsayang ng tubig','Mag-recycle','Magtapon sa ilog','Sayangin ang pagkain'],1]];
$('#spiralGrid').innerHTML=spiral.map((x,i)=>`<article class="spiral-item card"><h3>${i+1}. ${x[0]}</h3><div class="answer-grid">${x[1].map((a,j)=>`<button class="choice spiral-choice" data-i="${i}" data-j="${j}">${a}</button>`).join('')}</div><div class="feedback spiral-feedback"></div></article>`).join('');$$('.spiral-choice').forEach(b=>b.onclick=()=>{let q=spiral[+b.dataset.i],fb=b.parentElement.nextElementSibling;if(+b.dataset.j===q[2]){fb.textContent='🌟 Tama!';fb.className='feedback good';b.disabled=true;award(1);complete('spiral')}else{fb.textContent='💡 Balikan ang aralin.';fb.className='feedback try'}});

$$('.scenario').forEach(b=>b.onclick=()=>{let good=b.dataset.good==='true';$('#scenarioFeedback').textContent=good?'🌱 Magandang halimbawa! Ipinapakita nito ang wastong pangangalaga sa likas na yaman.':'💡 Subukan ang gawaing hindi nagsasayang at nakatutulong sa pangangalaga.';$('#scenarioFeedback').className='feedback '+(good?'good':'try');if(good){award(1);complete('apply')}});
$$('.reflect').forEach(b=>b.onclick=()=>{$$('.reflect').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#reflectionFeedback').textContent='💛 Salamat sa iyong reflection!';$('#reflectionFeedback').className='feedback good';complete('reflection')});

const final=[
 ['Alin ang kabilang sa yamang lupa?',['Bigas','Perlas','Agila','Ginto'],0,'Ang bigas ay produkto mula sa sakahan.'],
 ['Alin ang kabilang sa yamang gubat?',['Bakal','Agila','Perlas','Bigas'],1,'Ang agila ay isa sa mga hayop na binanggit sa kagubatan.'],
 ['Alin ang yamang mineral?',['Ginto','Isda','Gulay','Korales'],0,'Ang ginto ay mineral.'],
 ['Alin ang yamang tubig?',['Marmol','Usa','Isda','Bigas'],2,'Ang isda ay nakukuha sa dagat, ilog, at lawa.'],
 ['Saan matatagpuan ang mga yamang mineral?',['Sa ilalim ng lupa','Sa dagat lamang','Sa sakahan lamang','Sa bahay'],0,'Ang mga mineral ay matatagpuan sa ilalim ng lupa.'],
 ['Alin ang halimbawa ng yamang tubig ayon sa aralin?',['Perlas','Bakal','Gulay','Agila'],0,'Ang perlas ay nakukuha sa dagat.'],
 ['Ano ang isang paraan ng pagtitipid ng tubig sa bahay?',['Gumamit ng baso sa pagsesepilyo','Buksan ang gripo palagi','Magsayang ng tubig','Iwanang umaagos ang tubig'],0,'Gumamit ng baso kapag nagsesepilyo.'],
 ['Ano ang maaaring gawin sa lumang kagamitang maaari pang gamitin?',['Itapon agad','I-recycle','Iwan sa ilog','Sunugin'],1,'Maaaring i-recycle ang lumang kagamitang maaari pang gamitin.'],
 ['Alin ang HINDI yamang mineral?',['Diyamante','Marmol','Bakal','Isda'],3,'Ang isda ay yamang tubig.'],
 ['Bakit mahalaga ang wastong paggamit at pangangalaga?',['Limitado ang likas na yaman','Walang silbi ang likas na yaman','Hindi kailangan ang tubig','Lahat ay walang hanggan'],0,'Ayon sa aralin, limitado ang dami ng likas na yaman at hindi ito madaling napapalitan.']
];let fi=0,fc=0,finalMiss=[];
function renderFinal(){if(fi>=final.length){showResults();return}let q=final[fi];$('#finalNum').textContent=(fi+1)+' / '+final.length;$('#finalScore').textContent=fc+' correct';$('#finalQuestion').textContent=q[0];$('#finalChoices').innerHTML='';$('#finalFeedback').textContent='';$('#finalFeedback').className='feedback';$('#finalHintText').classList.add('hidden');$('#finalNext').classList.add('hidden');q[1].forEach((a,i)=>{let b=document.createElement('button');b.className='answer';b.textContent=a;b.onclick=()=>answerFinal(i,b);$('#finalChoices').appendChild(b)})}
function answerFinal(i,b){let q=final[fi];$$('#finalChoices .answer').forEach(x=>x.disabled=true);if(i===q[2]){b.classList.add('correct');fc++;award(2);$('#finalFeedback').textContent='🎉 Excellent! '+q[3];$('#finalFeedback').className='feedback good'}else{b.classList.add('incorrect');finalMiss.push({q:q[0],answer:q[1][q[2]],why:q[3]});$('#finalFeedback').textContent='💡 Let’s think again. '+q[3];$('#finalFeedback').className='feedback try'}$('#finalScore').textContent=fc+' correct';$('#finalNext').classList.remove('hidden');}
$('#finalHint').onclick=()=>{let q=final[fi];$('#finalHintText').textContent='💡 Hint: '+q[3];$('#finalHintText').classList.remove('hidden')};$('#finalNext').onclick=()=>{fi++;renderFinal()};
function showResults(){let pct=Math.round(fc/final.length*100);state.bestScore=Math.max(state.bestScore,pct);complete('mastery');save();$('#mastery .mastery-card').classList.add('hidden');$('#results').classList.remove('hidden');$('#resultScore').textContent=pct+'%';$('#resultDetail').textContent=`Nakuha mo ang ${fc} / ${final.length} na tamang sagot.`;let ach=pct>=90?'🏆 Lesson Master':pct>=80?'🎯 Practice Pro':pct>=70?'⭐ Great Effort':'💡 Keep Practicing';$('#resultAchievement').textContent=ach;$('#mistakesArea').classList.add('hidden');}
function resetFinal(){fi=0;fc=0;finalMiss=[];$('#mastery .mastery-card').classList.remove('hidden');$('#results').classList.add('hidden');renderFinal()}
$('#retryFinal').onclick=resetFinal;$('#mistakesBtn').onclick=()=>{let a=$('#mistakesArea');a.classList.toggle('hidden');a.innerHTML=finalMiss.length?'<h3>🔄 Practice My Mistakes</h3>'+finalMiss.map((m,i)=>`<div style="padding:12px;border-bottom:1px solid #dce8f2"><b>${i+1}. ${m.q}</b><br>Correct answer: <strong>${m.answer}</strong><br><small>${m.why}</small></div>`).join(''):'<h3>🌟 Great work!</h3><p>Wala kang namiss na tanong sa final challenge.</p>'};renderFinal();

$('#resetProgress').onclick=()=>{if(confirm('I-reset ang iyong progress, stars, badges, at best score?')){localStorage.removeItem(KEY);location.reload()}};
