const slides = [
["Simula", `
<div class="hero"><div class="eyebrow">FILIPINO 3 • PART 2</div><h1>Magagalang na Pananalita at Pang-angkop</h1><span class="en">Polite Expressions and Pang-angkop</span><p>Sa araling ito, matututuhan natin ang wastong paggamit ng <b>magagalang na pananalita</b> at ang wastong paggamit ng <b>pang-angkop na na at -ng</b>.</p><span class="en">In this lesson, we will learn polite expressions and how to use the pang-angkop na and -ng.</span><div class="call gold"><b>Mga Layunin:</b><br>• Makagamit ng magagalang na pananalita sa iba't ibang sitwasyon.<br>• Makapili ng wastong <b>na</b> o <b>-ng</b>.<br>• Magamit ang natutuhan sa tunay na pakikipag-usap.</div><button class="btn goldbtn" onclick="go(1)">Simulan ang Aralin →</button></div><div class="teacher">👨‍🏫 <b>Teacher Guide:</b> “Makinig, tumingin sa mga larawan, sumagot sa mga activity, at ipaliwanag kung bakit iyon ang iyong sagot.”</div>`],
["Larawan • Pahina 129–131", `
<div class="card"><div class="eyebrow">LOOK • OBSERVE</div><h2>👀 Unang Hakbang: Tingnan ang mga Larawan</h2><p>Gamitin natin ang mga larawan mula sa aklat bilang pangunahing batayan. Basahin ang mga halimbawa at pansinin kung paano ginagamit ang magagalang na pananalita.</p><span class="en">Use the textbook images as our main reference. Observe the examples and notice how polite expressions are used.</span></div><div class="grid"><div class="card"><img class="source" src="source-page-129.jpg" alt="Source page 129" onclick="zoom(this)"><div class="caption">Pahina 129 • Paggamit ng Magagalang na Pananalita</div></div><div class="card"><img class="source" src="source-page-130.jpg" alt="Source page 130" onclick="zoom(this)"><div class="caption">Pahina 130 • Mga Paraan 3–4</div></div></div><div class="card"><img class="source" src="source-page-131.jpg" alt="Source page 131" onclick="zoom(this)"><div class="caption">Pahina 131 • Mga sitwasyon para sa paggamit ng magagalang na pananalita</div></div><div class="activity"><b>🎯 ACTIVITY 1 — Hanapin sa Larawan!</b><p>Tukuyin ang mga salitang nagpapakita ng paggalang na nakita mo sa mga pahina.</p><div class="choices"><button class="choice" onclick="markActivity(this,true,'Tama! Makikita sa aralin ang mga halimbawa tulad ng po, opo, ho, pagbati, at paumanhin.')">po / opo / ho</button><button class="choice" onclick="markActivity(this,false,'Balikan ang larawan. Hanapin ang mga salitang ginagamit upang magpakita ng paggalang.')">Hoy!</button><button class="choice" onclick="markActivity(this,true,'Tama! Ang pagbati ay kabilang sa magagalang na pormulasyong panlipunan.')">Magandang umaga</button></div><div class="feedback"></div></div>`],
["Pag-unawa", `
<div class="card"><div class="eyebrow">TEACH • UNDERSTAND</div><h2>🌟 Bakit Mahalaga ang Magagalang na Pananalita?</h2><p>Ang isang mabuting pakikipagtalastasan at pakikipag-ugnayan ay napapanatili sa pamamagitan ng mahusay na paggamit ng <b>magagalang na pananalita</b>. Sa pamamagitan nito, naipakikita natin ang buong paggalang at pagsasaalang-alang sa ating kausap.</p><p>Sa paggamit ng magagalang na pananalita, napapanatili ang maayos at makataong pakikipagkapuwa-tao. Nakatutulong din ito upang maiwasan ang hindi pagkakasundo at hindi pagkakaunawaan.</p><span class="en">Polite expressions show respect, help maintain good relationships, and can prevent misunderstanding.</span></div><div class="grid3"><div class="card"><div class="big">🤝</div><h3>Paggalang</h3><span class="en">Respect</span></div><div class="card"><div class="big">💬</div><h3>Maayos na usapan</h3><span class="en">Good communication</span></div><div class="card"><div class="big">❤️</div><h3>Pakikipagkapuwa</h3><span class="en">Respectful relationship</span></div></div><div class="activity"><b>💭 ACTIVITY 2 — Ano ang Mararamdaman?</b><p>Kapag sinabi mo sa iyong guro, “Magandang umaga po,” ano ang ipinakikita mo?</p><div class="choices"><button class="choice" onclick="markActivity(this,true,'Tama! Ipinakikita mo ang paggalang sa kausap.')">Paggalang</button><button class="choice" onclick="markActivity(this,false,'Subukan muli. Ang paggamit ng po sa pagbati ay nagpapakita ng paggalang.')">Pang-aasar</button><button class="choice" onclick="markActivity(this,false,'Hindi. Ang layunin ng magalang na pananalita ay maayos na pakikipag-ugnayan.')">Kawalang-galang</button></div><div class="feedback"></div></div>`],
["Paraan 1–2", `
<div class="card"><div class="eyebrow">TEACH • MODEL</div><h2>💬 Paraan 1 at 2</h2><p><b>1. Paggamit ng pagbati at iba pang pormulasyong panlipunan</b></p><div class="call">“Magandang umaga!”<br>“Paumanhin po.”<br>“Maraming salamat sa iyong pakikibahagi.”</div><p><b>2. Paggamit ng po at opo; o kaya naman ay ho at oho</b></p><div class="call green">“Tuloy po kayo sa aming munting tahanan.”<br>“Kumusta ho kayo, Tiya Remy?”<br>“Opo, sila ang mga kaibigan ko.”</div><span class="en">Use greetings, social formulas, and respectful words such as po, opo, ho, and oho.</span></div><div class="activity"><b>🎯 ACTIVITY 3 — Piliin ang Magalang!</b><p>Piliin ang pahayag na angkop kapag binabati ang guro sa umaga.</p><div class="choices"><button class="choice" onclick="markActivity(this,true,'Tama! Ito ay pagbati na may magalang na pananalita.')">Magandang umaga po, Teacher!</button><button class="choice" onclick="markActivity(this,false,'Hindi ito angkop na magalang na pagbati sa guro.')">Uy, Teacher!</button></div><div class="feedback"></div></div><div class="teacher">👨‍🏫 <b>Teacher Modeling:</b> Ipaulit sa klase: “Magandang umaga po, Teacher!”</div>`],
["Paraan 3–4", `
<div class="card"><div class="eyebrow">TEACH • MODEL</div><h2>🗣️ Paraan 3 at 4</h2><p><b>3. Wastong paggamit ng mga katawagan</b></p><div class="call">“Magandang umaga po, Bb. Ventura.”<br>“Paolo po, Gng. Bilog.”<br>“Kausapin natin si G. Chua para sa ating proyekto.”</div><p><b>4. Pag-iwas sa mapanupya at walang galang na pananalita</b></p><div class="call gold">“Hindi natin nilalait ang ating kapuwa.”<br>“Hindi tayo gumagamit ng mga salitang masasakit at mura.”</div><span class="en">Use proper titles and avoid insulting, hurtful, or disrespectful language.</span></div><div class="activity"><b>🎯 ACTIVITY 4 — Wastong Katawagan</b><p>Ano ang wastong katawagan sa isang gurong babae na may-asawa?</p><div class="choices"><button class="choice" onclick="markActivity(this,true,'Tama! Gng. / Ginang ang halimbawang ginamit sa aralin para sa babaeng may-asawa.')">Gng. / Ginang</button><button class="choice" onclick="markActivity(this,false,'Balikan ang halimbawa sa larawan at aralin.')">Hoy, Teacher!</button></div><div class="feedback"></div></div>`],
["Activity • Magalang o Hindi?", `
<div class="card"><div class="eyebrow">🎮 ACTIVITY 5 • CLASSIFY</div><h2>🟢 Magalang o 🔴 Hindi?</h2><p>Basahin ang bawat pahayag. Piliin kung ito ay <b>MAGALANG</b> o <b>HINDI MAGALANG</b>.</p><span class="en">Classify each statement as polite or not polite.</span></div><div id="classify"></div>`],
["Activity • Ayusin ang Usapan", `
<div class="card"><div class="eyebrow">🎮 ACTIVITY 6 • CHOOSE</div><h2>💬 Piliin ang Tamang Sagot</h2><p>May sitwasyon. Piliin ang pinakaangkop na magalang na pahayag.</p><span class="en">Choose the most appropriate polite response.</span></div><div id="politeQuiz"></div>`],
["Activity • Role Play", `
<div class="card"><div class="eyebrow">🎭 ACTIVITY 7 • ROLE PLAY</div><h2>🎭 Gawin Natin!</h2><p>Pumili ng tamang pahayag. Pagkatapos, <b>ipagawa sa isang mag-aaral ang role-play</b> kasama ang kapareha.</p><span class="en">Choose the appropriate expression, then perform the situation with a partner.</span></div><div id="roleplay"></div>`],
["Activity • Pahina 131", `
<div class="card"><div class="eyebrow">✍️ ACTIVITY 8 • SOURCE-BASED</div><h2>📖 Gamitin ang Natutuhan</h2><p>Ang sumusunod na mga sitwasyon ay batay sa <b>pahina 131</b> ng aklat. Piliin ang angkop at magalang na pananalita.</p><span class="en">These situations are based on page 131.</span></div><div id="situations"></div>`],
["Pang-angkop", `
<div class="card"><div class="eyebrow">GRAMMAR • TEACH</div><h2>🔗 Ano ang Pang-angkop?</h2><p>Ang <b>pang-angkop</b> ay bahagi ng pananalita na ginagamit upang pag-ugnayin ang salitang panuring at salitang tinuturingan. Nakakatulong ito upang maging maayos, malinaw, at maganda ang daloy ng mga salita sa isang pahayag.</p><span class="en">Pang-angkop connects the describing word and the word it describes.</span></div><div class="grid3"><div class="card"><div class="big">🔗</div><h3>Nag-uugnay</h3></div><div class="card"><div class="big">🧩</div><h3>Nagpapalinaw</h3></div><div class="card"><div class="big">✨</div><h3>Nagpapaganda</h3></div></div><div class="activity"><b>🎯 ACTIVITY 9 — Tukuyin ang Pang-angkop</b><p>Sa <b>masipag na bata</b>, alin ang pang-angkop?</p><div class="choices"><button class="choice" onclick="markActivity(this,false,'Hindi. Ang masipag ay salitang panuring.')">masipag</button><button class="choice" onclick="markActivity(this,true,'Tama! Ang na ang nag-uugnay sa masipag at bata.')">na</button><button class="choice" onclick="markActivity(this,false,'Hindi. Ang bata ang salitang tinuturingan.')">bata</button></div><div class="feedback"></div></div>`],
["na", `
<div class="card"><div class="eyebrow">GRAMMAR • I DO</div><h2><b>na</b> — Kapag katinig ang hulihan</h2><div class="rule"><span class="term">na</span><div><p>Ginagamit ang <b>na</b> kapag ang nauunang salita ay nagtatapos sa <b>katinig</b>.</p><span class="en">Use <b>na</b> when the preceding word ends in a consonant.</span></div></div></div><div class="card"><h3>📖 Mga halimbawang nasa larawan</h3><div class="example"><div class="word">masipag</div><div class="conn">na</div><div class="word">bata</div></div><div class="example"><div class="word">mabait</div><div class="conn">na</div><div class="word">guro</div></div><div class="example"><div class="word">matamis</div><div class="conn">na</div><div class="word">mangga</div></div></div><div class="activity"><b>🎯 ACTIVITY 10 — Hanapin ang Hulihan</b><p>Ang salitang <b>mabait</b> ay nagtatapos sa anong tunog?</p><div class="choices"><button class="choice" onclick="markActivity(this,true,'Tama! Ang mabait ay nagtatapos sa katinig na t.')">Katinig</button><button class="choice" onclick="markActivity(this,false,'Hindi. Tingnan ang huling titik ng mabait: t.')">Patinig</button></div><div class="feedback"></div></div>`],
["-ng", `
<div class="card"><div class="eyebrow">GRAMMAR • I DO</div><h2><b>-ng</b> — Kapag patinig o /n/ ang hulihan</h2><div class="rule"><span class="term">-ng</span><div><p>Ginagamit ang <b>-ng</b> kapag ang nauunang salita ay nagtatapos sa <b>patinig o /n/</b>.</p><span class="en">Use <b>-ng</b> when the preceding word ends in a vowel or /n/.</span></div></div></div><div class="card"><h3>📖 Mga halimbawa mula sa larawan</h3><div class="example"><div class="word">masaya</div><div class="conn">-ng</div><div class="word">pag-aaral</div></div><div class="example"><div class="word">maganda</div><div class="conn">-ng</div><div class="word">umaga</div></div><div class="example"><div class="word">puso</div><div class="conn">-ng</div><div class="word">bato</div></div><div class="example"><div class="word">halaman</div><div class="conn">-ng</div><div class="word">malago</div></div><div class="example"><div class="word">bayan</div><div class="conn">-ng</div><div class="word">magiliw</div></div></div><div class="activity"><b>🎯 ACTIVITY 11 — Piliin ang Pang-angkop</b><p>Alin ang tama: <b>maganda ___ umaga</b>?</p><div class="choices"><button class="choice" onclick="markActivity(this,false,'Balikan ang tuntunin: nagtatapos sa patinig ang maganda.')">na</button><button class="choice" onclick="markActivity(this,true,'Tama! Maganda ay nagtatapos sa patinig, kaya -ng.')">-ng</button></div><div class="feedback"></div></div>`],
["Activity • Pang-angkop Detective", `
<div class="card"><div class="eyebrow">🎮 ACTIVITY 12 • PRACTICE</div><h2>🔎 Pang-angkop Detective</h2><p>Piliin ang <b>na</b> o <b>-ng</b>. Bago sumagot, sabihin kung ang unang salita ay nagtatapos sa katinig, patinig, o /n/.</p><span class="en">Choose na or -ng and explain why.</span></div><div id="pangQuiz"></div>`],
["Activity • Buuin ang Parirala", `
<div class="card"><div class="eyebrow">🎮 ACTIVITY 13 • BUILD</div><h2>🧩 Buuin ang Tamang Parirala</h2><p>Piliin ang tamang pang-angkop upang mabuo ang parirala.</p></div><div id="buildQuiz"></div>`],
["Mastery Challenge", `
<div class="card"><div class="eyebrow">🏆 ACTIVITY 14 • MASTERY</div><h2>🏆 Pangwakas na Hamon</h2><p>Pinagsamang pagsasanay sa <b>magagalang na pananalita</b> at <b>pang-angkop</b>.</p><span class="en">Final challenge: polite expressions and pang-angkop.</span></div><div id="mastery"></div><div class="score"><span>Mastery Score</span><strong id="ms">0 / 15</strong><span id="mm">Sagutin ang lahat ng item.</span></div>`],
["Tapos", `
<div class="hero" style="text-align:center"><div class="big">🎉</div><h2>Natapos Mo ang Aralin!</h2><p>Natutuhan mo ang dalawang mahalagang kasanayan:</p><div class="grid"><div class="card"><h3>💬 Magagalang na Pananalita</h3><p>Pagbati, po/opo/ho/oho, wastong katawagan, at pag-iwas sa mapanupya o walang galang na pananalita.</p></div><div class="card"><h3>🔗 Pang-angkop</h3><p><b>na</b> → katinig<br><b>-ng</b> → patinig o /n/</p></div></div><div class="score"><span>Mastery Score</span><strong id="finalScore">0 / 15</strong><span id="finalMsg">Patuloy na magsanay at gamitin ang natutuhan sa araw-araw.</span></div><button class="btn bluebtn" onclick="go(0)">↺ Balikan ang Aralin</button><button class="btn goldbtn" onclick="window.print()">🖨️ I-print</button></div>`]
];

const classify = [
["Magandang umaga po, Gng. Morales.",0],["Hoy, saan ang silid-aklatan?",1],["Paumanhin po.",0],["Akin na ang lapis mo!",1],["Maraming salamat po.",0],["Opo, Teacher.",0],["Huwag ka ngang tanga.",1],["Tuloy po kayo.",0]
];
const politeQuiz = [
["Binati mo ang iyong guro sa umaga.",["Magandang umaga po, Teacher!","Uy, Teacher!"],0],["May nais kang itanong sa isang nakatatanda.",["Ano ba 'yan?","Paumanhin po, maaari po ba akong magtanong?"],1],["May tumulong sa iyong kaklase.",["Maraming salamat sa iyong tulong.","O, salamat na lang."],0],["Dumarating ang isang bisita sa inyong tahanan.",["Tuloy po kayo.","Pasok ka."],0],["Hindi mo kilala ang kausap at kailangan mong magtanong.",["Hoy, saan ito?","Paumanhin po, maaari ko po bang itanong kung saan ito?"],1],["May nasabi kang hindi maganda sa kausap.",["Hindi ko na kailangan magsabi ng sorry.","Paumanhin po sa aking nasabi."],1]
];
const roleplay = [
["Binati mo ang iyong guro bago magsimula ang klase.",["Magandang umaga po, Teacher.","Uy, Teacher!"],0],["May gusto kang ipakiusap sa isang nakatatanda.",["Pakiabot nga.","Maaari po bang pakiabot nito?"],1],["Tinulungan ka ng isang kaklase.",["Salamat sa iyong tulong.","Bilis, gawin mo ulit."],0],["Hindi mo sinasadyang makasalubong ang isang tao.",["Paumanhin po.","Tabi!"],0],["Tinawag mo ang isang gurong babae na may-asawa.",["Gng. / Ginang","Hoy, Ma'am girl"],0]
];
const situations = [
["Binigyan ka ng regalo ng iyong tiyahin sa araw ng iyong kaarawan.",["Maraming salamat po, Tiya.","Akin na."],0],["Nahuli ka sa pagpasok sa silid-aralan at nakita ka ni Sir Jan.",["Paumanhin po, Sir Jan, nahuli po ako.","Hindi ko kasalanan."],0],["Tinanong mo ang sales lady sa department store kung saan makabibili ng medyas.",["Miss, saan po makakabili ng medyas?","Hoy, medyas saan?"],0],["Nasalubong mo sa koridor si Gng. Morales, ang inyong punong-guro, habang papasok kayo ng aklatan.",["Magandang araw po, Gng. Morales.","Uy, Principal!"],0],["Nadapa si Fe, ang iyong kamag-aral, habang naglalakad kayo pauwi.",["Ayos ka lang ba, Fe?","Ayan kasi."],0],["Sumakay ka ng jeepney at akma kang magbabayad ng iyong pamasahe sa katabing pasahero.",["Makikiraan po, salamat po.","Tabi nga."],0],["Inutusan ka ng iyong nanay na bumili sa tindahan ni Aling Nena ng isang bote ng suka.",["Magandang araw po, Aling Nena. Maaari po bang bumili ng isang bote ng suka?","Bote ng suka."],0],["May nagtanong sa iyo subalit hindi mo kilala.",["Paumanhin po, ano po ang inyong pangalan?","Ano pangalan mo?"],0],["Dumating ang iyong lola mula sa probinsiya at nasa tarangkahan siya ng inyong bahay.",["Tuloy po kayo, Lola!","Bakit ngayon ka lang?"],0],["Binati mo ang iyong kaklase mula sa pagwawagi niya sa patimpalak.",["Binabati kita! Mahusay ang iyong ginawa.","Ang dali lang naman."],0]
];
const pangQuiz = [["masipag ___ bata","na","masipag na bata"],["mabait ___ guro","na","mabait na guro"],["matamis ___ mangga","na","matamis na mangga"],["masaya ___ pag-aaral","-ng","masayang pag-aaral"],["maganda ___ umaga","-ng","magandang umaga"],["puso ___ bato","-ng","pusong bato"],["halaman ___ malago","-ng","halamang malago"],["bayan ___ magiliw","-ng","bayang magiliw"],["mayaman ___ kalikasan","-ng","mayamang kalikasan"]];
const buildQuiz = [["masipag + ? + bata",["na","-ng"],0,"masipag na bata"],["maganda + ? + umaga",["na","-ng"],1,"magandang umaga"],["mabait + ? + guro",["na","-ng"],0,"mabait na guro"],["puso + ? + bato",["na","-ng"],1,"pusong bato"],["bayan + ? + magiliw",["na","-ng"],1,"bayang magiliw"],["halaman + ? + malago",["na","-ng"],1,"halamang malago"]];
const mastery = [
["Binati mo ang iyong guro sa umaga.",["Magandang umaga po!","Hoy!"],0,"Magalang na pagbati."],["Humihingi ka ng paumanhin.",["Paumanhin po.","Kasalanan mo!"],0,"Magalang na paghingi ng paumanhin."],["Kumusta ang isang nakatatanda?",["Kumusta ho kayo?","Uy, ikaw!"],0,"Ginamit ang ho bilang magalang na pananalita."],["Tama: masipag ___ bata.",["na","-ng"],0,"Ang masipag ay nagtatapos sa katinig."],["Tama: maganda ___ umaga.",["na","-ng"],1,"Ang maganda ay nagtatapos sa patinig."],["Tama: bayan ___ magiliw.",["na","-ng"],1,"Ang bayan ay nagtatapos sa /n/."],["Dapat iwasan ang ___ pananalita.",["masasakit at mura","magalang"],0,"Ayon sa aralin, iwasan ang masasakit at murang salita."],["Wastong katawagan para sa gurong may-asawa.",["Gng.","Hoy"],0,"Ginagamit ang Gng. / Ginang."],["Tama: matamis ___ mangga.",["na","-ng"],0,"Ang matamis ay nagtatapos sa katinig."],["Tama: mayaman ___ kalikasan.",["na","-ng"],1,"Ang mayaman ay nagtatapos sa /n/."],["Tama: masaya ___ pag-aaral.",["na","-ng"],1,"Ang masaya ay nagtatapos sa patinig."],["Tama: halaman ___ malago.",["na","-ng"],1,"Ang halaman ay nagtatapos sa /n/."],["Tama: mabait ___ guro.",["na","-ng"],0,"Ang mabait ay nagtatapos sa katinig."],["Ano ang ipinakikita ng 'Maraming salamat po' ?",["Paggalang","Pang-aasar"],0,"Ito ay magalang na pagpapahayag."],["Ano ang dapat iwasan?",["Salitang masasakit at mura","Magalang na pananalita"],0,"Ayon sa aralin, iwasan ang masasakit at murang salita."]
];

let cur=Number(localStorage.teFilPart2Slide||0); if(cur>=slides.length)cur=0;
let scores=JSON.parse(localStorage.teFilPart2Scores||'{"mastery":0}');
function go(n){cur=Math.max(0,Math.min(slides.length-1,n));render();}
function save(){localStorage.teFilPart2Slide=cur;localStorage.teFilPart2Scores=JSON.stringify(scores);}
function render(){document.getElementById('app').innerHTML=slides.map((s,i)=>`<section class="slide ${i===cur?'active':''}">${s[1]}</section>`).join('');document.getElementById('where').textContent=(cur+1)+'. '+slides[cur][0];document.getElementById('pt').textContent=(cur+1)+' / '+slides.length;document.getElementById('bar').style.width=((cur+1)/slides.length*100)+'%';document.getElementById('prev').disabled=cur===0;document.getElementById('next').textContent=cur===slides.length-1?'Tapos ✓':'Susunod →';document.getElementById('nav').innerHTML=slides.map((s,i)=>`<button class="navbtn ${i===cur?'active':''}" onclick="go(${i})">${i+1}. ${s[0]}</button>`).join('');if(cur===5)renderClassify();if(cur===6)renderPoliteQuiz();if(cur===7)renderRoleplay();if(cur===8)renderSituations();if(cur===12)renderPangQuiz();if(cur===13)renderBuildQuiz();if(cur===14)renderMastery();if(cur===15)renderFinal();save();scrollTo({top:0,behavior:'smooth'});}
function markActivity(btn,ok,msg){const box=btn.closest('.activity');if(box.dataset.done)return;box.dataset.done=1;box.querySelectorAll('.choice').forEach(b=>b.disabled=true);btn.classList.add(ok?'correct':'wrong');const f=box.querySelector('.feedback');f.className='feedback show '+(ok?'ok':'no');f.textContent=(ok?'✅ ':'❌ ')+msg;}
function renderClassify(){document.getElementById('classify').innerHTML=classify.map((q,i)=>`<div class="card" data-c="${i}"><b>${i+1}. “${q[0]}”</b><div class="choices"><button class="choice" onclick="classifyAns(${i},0)">🟢 MAGALANG</button><button class="choice" onclick="classifyAns(${i},1)">🔴 HINDI MAGALANG</button></div><div id="cf${i}" class="feedback"></div></div>`).join('');}
function classifyAns(i,j){const c=document.querySelector(`[data-c="${i}"]`);if(c.dataset.done)return;c.dataset.done=1;c.querySelectorAll('.choice').forEach(b=>b.disabled=true);const f=document.getElementById('cf'+i);const ok=j===classify[i][1];c.querySelectorAll('.choice')[j].classList.add(ok?'correct':'wrong');f.className='feedback show '+(ok?'ok':'no');f.textContent=ok?'✅ Tama!':'❌ Balikan ang halimbawa at isipin kung magalang ang pananalita.';}
function renderPoliteQuiz(){document.getElementById('politeQuiz').innerHTML=politeQuiz.map((q,i)=>`<div class="card" data-p="${i}"><b>${i+1}. ${q[0]}</b><div class="choices">${q[1].map((o,j)=>`<button class="choice" onclick="politeAns(${i},${j})">${o}</button>`).join('')}</div><div id="pf${i}" class="feedback"></div></div>`).join('');}
function politeAns(i,j){const c=document.querySelector(`[data-p="${i}"]`);if(c.dataset.done)return;c.dataset.done=1;c.querySelectorAll('.choice').forEach(b=>b.disabled=true);const ok=j===politeQuiz[i][2],f=document.getElementById('pf'+i);c.querySelectorAll('.choice')[j].classList.add(ok?'correct':'wrong');f.className='feedback show '+(ok?'ok':'no');f.innerHTML=ok?'✅ Tama! Magalang at angkop ang pahayag.':'❌ Mas angkop: <b>'+politeQuiz[i][1][politeQuiz[i][2]]+'</b>'}
function renderRoleplay(){document.getElementById('roleplay').innerHTML=roleplay.map((q,i)=>`<div class="card" data-r="${i}"><b>${i+1}. ${q[0]}</b><div class="choices">${q[1].map((o,j)=>`<button class="choice" onclick="roleAns(${i},${j})">${o}</button>`).join('')}</div><div id="rf${i}" class="feedback"></div><div class="teacher">🎭 <b>Gawin pagkatapos:</b> I-role-play ang sitwasyon kasama ang kapareha.</div></div>`).join('');}
function roleAns(i,j){const c=document.querySelector(`[data-r="${i}"]`);if(c.dataset.done)return;c.dataset.done=1;c.querySelectorAll('.choice').forEach(b=>b.disabled=true);const ok=j===roleplay[i][2],f=document.getElementById('rf'+i);c.querySelectorAll('.choice')[j].classList.add(ok?'correct':'wrong');f.className='feedback show '+(ok?'ok':'no');f.textContent=ok?'✅ Tama! Ngayon, gawin ang role-play.':'❌ Piliin ang mas magalang na pahayag, saka gawin ang role-play.'}
function renderSituations(){document.getElementById('situations').innerHTML=situations.map((q,i)=>`<div class="card" data-s="${i}"><b>${i+1}. ${q[0]}</b><div class="choices">${q[1].map((o,j)=>`<button class="choice" onclick="sitAns(${i},${j})">${o}</button>`).join('')}</div><div id="sf${i}" class="feedback"></div></div>`).join('');}
function sitAns(i,j){const c=document.querySelector(`[data-s="${i}"]`);if(c.dataset.done)return;c.dataset.done=1;c.querySelectorAll('.choice').forEach(b=>b.disabled=true);const ok=j===situations[i][2],f=document.getElementById('sf'+i);c.querySelectorAll('.choice')[j].classList.add(ok?'correct':'wrong');f.className='feedback show '+(ok?'ok':'no');f.textContent=ok?'✅ Tama! Angkop at magalang ang pananalita.':'❌ Piliin ang mas magalang na pahayag.'}
function renderPangQuiz(){document.getElementById('pangQuiz').innerHTML=pangQuiz.map((q,i)=>`<div class="card" data-q="${i}"><div class="sentence">${i+1}. ${q[0].replace('___',`<select id="pq${i}"><option value="">?</option><option>na</option><option>-ng</option></select>`)}</div><button class="btn bluebtn" onclick="checkPang(${i})">Suriin</button><div id="qf${i}" class="feedback"></div></div>`).join('');}
function checkPang(i){const v=document.getElementById('pq'+i).value,f=document.getElementById('qf'+i),q=pangQuiz[i];if(!v){f.className='feedback show no';f.textContent='Pumili muna.';return}if(v===q[1]){f.className='feedback show ok';f.innerHTML='✅ Tama! <b>'+q[2]+'</b>.'}else{f.className='feedback show no';f.innerHTML='❌ Tamang sagot: <b>'+q[1]+'</b> → '+q[2]+'.'}}
function renderBuildQuiz(){document.getElementById('buildQuiz').innerHTML=buildQuiz.map((q,i)=>`<div class="card" data-b="${i}"><b>${i+1}. ${q[0]}</b><div class="choices">${q[1].map((o,j)=>`<button class="choice" onclick="buildAns(${i},${j})">${o}</button>`).join('')}</div><div id="bf${i}" class="feedback"></div></div>`).join('');}
function buildAns(i,j){const c=document.querySelector(`[data-b="${i}"]`);if(c.dataset.done)return;c.dataset.done=1;c.querySelectorAll('.choice').forEach(b=>b.disabled=true);const ok=j===buildQuiz[i][2],f=document.getElementById('bf'+i);c.querySelectorAll('.choice')[j].classList.add(ok?'correct':'wrong');f.className='feedback show '+(ok?'ok':'no');f.innerHTML=ok?'✅ Tama! <b>'+buildQuiz[i][3]+'</b>.':'❌ Subukan muli. Tamang sagot: <b>'+buildQuiz[i][3]+'</b>.'}
function renderMastery(){document.getElementById('mastery').innerHTML=mastery.map((q,i)=>`<div class="card" data-m="${i}"><b>${i+1}. ${q[0]}</b><div class="choices">${q[1].map((o,j)=>`<button class="choice" onclick="mAns(${i},${j})">${o}</button>`).join('')}</div><div id="mf${i}" class="feedback"></div></div>`).join('');updateMasteryScore();}
function mAns(i,j){const c=document.querySelector(`[data-m="${i}"]`);if(c.dataset.done)return;c.dataset.done=1;c.querySelectorAll('.choice').forEach(b=>b.disabled=true);const correct=mastery[i][2],ok=j===correct,f=document.getElementById('mf'+i);c.querySelectorAll('.choice')[j].classList.add(ok?'correct':'wrong');if(ok)scores.mastery=(scores.mastery||0)+1;f.className='feedback show '+(ok?'ok':'no');f.textContent=ok?'✅ Tama! '+mastery[i][3]:'❌ Tamang sagot: '+mastery[i][1][correct];updateMasteryScore();save();}
function updateMasteryScore(){const el=document.getElementById('ms');if(el)el.textContent=(scores.mastery||0)+' / 15';const mm=document.getElementById('mm');if(mm)mm.textContent=(scores.mastery||0)>=12?'🌟 Napakahusay! Naipakita mo ang mahusay na pag-unawa.':'Sagutin ang lahat ng item at balikan ang paliwanag kung kinakailangan.';}
function renderFinal(){document.getElementById('finalScore').textContent=(scores.mastery||0)+' / 15';document.getElementById('finalMsg').textContent=(scores.mastery||0)>=12?'Mahusay! Ipagpatuloy ang paggamit ng magagalang na pananalita at wastong pang-angkop.':'Patuloy na magsanay. Balikan ang mga larawan, halimbawa, at activities.';}
function zoom(img){const o=document.createElement('div');o.style='position:fixed;inset:0;background:#000d;z-index:100;display:grid;place-items:center;padding:15px;cursor:zoom-out';const x=new Image();x.src=img.src;x.alt=img.alt;x.style='max-width:96vw;max-height:94vh;object-fit:contain;border-radius:12px';o.append(x);o.onclick=()=>o.remove();document.body.append(o);}
document.getElementById('prev').onclick=()=>go(cur-1);document.getElementById('next').onclick=()=>go(cur+1);document.getElementById('fs').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')go(cur+1);if(e.key==='ArrowLeft')go(cur-1);if(e.key.toLowerCase()==='f')document.getElementById('fs').click()});render();
