const questions = [
 {cat:'KILALANIN',diff:'Madali',type:'open',q:'Ano ang tawag sa masayang pangyayaring kalimitang idinaraos kasama ang pamilya?',en:'What do we call a happy event usually celebrated with the family?',a:'Pagdiriwang',ae:'Celebration',hint:'Isipin ang kaarawan, Pasko, o Bagong Taon.'},
 {cat:'KILALANIN',diff:'Madali',type:'open',q:'Ano ang tradisyon?',en:'What is a tradition?',a:'Nakasanayang kaugalian o gawain na patuloy na isinasagawa at pinahahalagahan.',ae:'A customary practice or activity continued and valued over time.',hint:'Ito ay ginagawa mula noon hanggang ngayon.'},
 {cat:'KILALANIN',diff:'Madali',type:'open',q:'Ano ang tawag sa paggalang sa nakatatandang kasapi ng pamilya sa pamamagitan ng paghawak ng kamay sa noo?',en:'What do we call the Filipino practice of showing respect to elders by touching their hand to the forehead?',a:'Pagmamano',ae:'Pagmamano (a Filipino gesture of respect to elders)',hint:'Ginagawa ito bilang pagpapakita ng paggalang.'},
 {cat:'KILALANIN',diff:'Madali',type:'choice',q:'Alin ang pagdiriwang na ginaganap tuwing ika-25 ng Disyembre?',en:'Which celebration is held every December 25?',choices:['Pasko','Bagong Taon','Kaarawan'],a:'Pasko',ae:'Christmas',hint:'Ito ay paggunita sa kapanganakan ni Hesus.'},
 {cat:'KILALANIN',diff:'Madali',type:'choice',q:'Alin ang ipinagdiriwang tuwing gabi ng ika-31 ng Disyembre?',en:'Which celebration is held on the night of December 31?',choices:['Pasko','Bagong Taon','Araw ng mga Ina'],a:'Bagong Taon',ae:'New Year',hint:'May Media Noche at salubong.'},
 {cat:'KILALANIN',diff:'Madali',type:'choice',q:'Anong pagdiriwang ang nag-aalala sa araw ng kapanganakan ng isang kasapi ng pamilya?',en:'Which celebration remembers the birthday of a family member?',choices:['Kaarawan','Binyag','Araw ng mga Bata'],a:'Kaarawan',ae:'Birthday',hint:'May cake, pagbati, o regalo.'},
 {cat:'KILALANIN',diff:'Madali',type:'choice',q:'Alin ang pagdiriwang ng mga Muslim na binanggit sa aralin?',en:'Which Muslim celebrations are mentioned in the lesson?',choices:['Eid’l Fitr at Eid’l Adha','Pasko at Bagong Taon','Kaarawan at Binyag'],a:'Eid’l Fitr at Eid’l Adha',ae:'Eid’l Fitr and Eid’l Adha',hint:'Dalawang pangunahing pagdiriwang sa Islam.'},
 {cat:'KILALANIN',diff:'Madali',type:'choice',q:'Kailan ipinagdiriwang ang Araw ng mga Ina?',en:'When is Mother’s Day celebrated?',choices:['Ikalawang Linggo ng Mayo','Ikatlong Linggo ng Hunyo','Ika-20 ng Nobyembre'],a:'Ikalawang Linggo ng Mayo',ae:'Second Sunday of May',hint:'Mayo para sa mga Ina.'},
 {cat:'KILALANIN',diff:'Madali',type:'choice',q:'Kailan ipinagdiriwang ang Araw ng mga Ama?',en:'When is Father’s Day celebrated?',choices:['Ikatlong Linggo ng Hunyo','Ikalawang Linggo ng Mayo','Ika-25 ng Disyembre'],a:'Ikatlong Linggo ng Hunyo',ae:'Third Sunday of June',hint:'Hunyo para sa mga Ama.'},
 {cat:'KILALANIN',diff:'Madali',type:'choice',q:'Kailan ipinagdiriwang ang Pandaigdigang Araw ng mga Bata ayon sa aralin?',en:'When is International Children’s Day observed according to the lesson?',choices:['Ika-20 ng Nobyembre','Ika-1 ng Enero','Ika-25 ng Disyembre'],a:'Ika-20 ng Nobyembre',ae:'November 20',hint:'Nobyembre 20.'},
 {cat:'PILIIN',diff:'Katamtaman',type:'choice',q:'Alin ang halimbawa ng tradisyon ng pamilyang Pilipino?',en:'Which is an example of a Filipino family tradition?',choices:['Pagmamano sa nakatatanda','Pagtatapon ng pagkain','Hindi pakikinig sa pamilya'],a:'Pagmamano sa nakatatanda',ae:'Showing respect to elders through pagmamano',hint:'Tradisyon ito ng pagpapakita ng paggalang.'},
 {cat:'PILIIN',diff:'Katamtaman',type:'choice',q:'Ano ang karaniwang ginagawa ng pamilya kapag may bisita?',en:'What does a family commonly do when there are visitors?',choices:['Tinatanggap at pinaghahandaan sila','Pinapaalis agad','Hindi pinapansin'],a:'Tinatanggap at pinaghahandaan sila',ae:'They welcome and prepare for the visitors.',hint:'Kilalang kaugalian ang pagiging magiliw sa bisita.'},
 {cat:'PILIIN',diff:'Katamtaman',type:'choice',q:'Ano ang ginagawa ng ilang pamilya kapag dumadalaw sa libingan ng yumao?',en:'What do some families do when visiting the graves of loved ones?',choices:['Nagsisindi ng kandila, nagdadala ng bulaklak, at nananalangin','Naglalaro sa libingan','Nagtatapon ng basura'],a:'Nagsisindi ng kandila, nagdadala ng bulaklak, at nananalangin',ae:'They light candles, bring flowers, and pray.',hint:'Ito ay paraan ng pag-alala sa yumao.'},
 {cat:'PILIIN',diff:'Katamtaman',type:'choice',q:'Ano ang karaniwang ginagawa ng pamilya sa Media Noche?',en:'What do families commonly do during Media Noche?',choices:['Nagsasalo-salo sa pagsalubong sa Bagong Taon','Natutulog buong gabi','Pumapasok sa paaralan'],a:'Nagsasalo-salo sa pagsalubong sa Bagong Taon',ae:'They share a meal while welcoming the New Year.',hint:'Isipin ang gabi ng ika-31 ng Disyembre.'},
 {cat:'PILIIN',diff:'Katamtaman',type:'choice',q:'Ano ang karaniwang ginagawa ng mga pamilyang Kristiyano sa Pasko?',en:'What do Christian families commonly do at Christmas?',choices:['Nagsasalo-salo at maaaring dumalo sa Simbang Gabi o Misa de Gallo','Nagsasagawa ng Ramadan','Nag-aayuno para sa Eid'],a:'Nagsasalo-salo at maaaring dumalo sa Simbang Gabi o Misa de Gallo',ae:'They share meals and may attend Simbang Gabi or Misa de Gallo.',hint:'Pasko ay paggunita sa kapanganakan ni Hesus.'},
 {cat:'PILIIN',diff:'Katamtaman',type:'choice',q:'Ano ang binyag?',en:'What is baptism?',choices:['Isang pagdiriwang ng pagtanggap sa bagong silang na sanggol','Isang pagdiriwang ng Bagong Taon','Isang laro sa paaralan'],a:'Isang pagdiriwang ng pagtanggap sa bagong silang na sanggol',ae:'A celebration welcoming a newborn baby.',hint:'Madalas itong gawin para sa bagong silang na sanggol.'},
 {cat:'PILIIN',diff:'Katamtaman',type:'open',q:'Bakit mahalaga ang mga pagdiriwang at tradisyon sa pamilya?',en:'Why are family celebrations and traditions important?',a:'Nakatutulong ang mga ito upang magbuklod at magsama-sama ang pamilya.',ae:'They help families bond and spend time together.',hint:'Isipin kung paano nagiging mas malapit ang pamilya.'},
 {cat:'PILIIN',diff:'Katamtaman',type:'open',q:'Paano mo maipapakita na pinahahalagahan mo ang tradisyon ng inyong pamilya?',en:'How can you show that you value your family traditions?',a:'Makilahok, sumunod nang maayos, at igalang ang mga tradisyon ng pamilya.',ae:'Participate, follow appropriately, and respect the family traditions.',hint:'Maaaring makilahok at tumulong.'},
 {cat:'PILIIN',diff:'Katamtaman',type:'open',q:'Ano ang dapat mong gawin kapag may tradisyon ng ibang pamilya na naiiba sa inyong tradisyon?',en:'What should you do when another family has a tradition different from yours?',a:'Igalang ang pagkakaiba at huwag itong pagtawanan.',ae:'Respect the difference and do not make fun of it.',hint:'Magkakaiba man, dapat igalang ang bawat pamilya.'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'open',q:'May birthday ang iyong kapatid. Ano ang maaari mong gawin upang maging masaya ang pagdiriwang?',en:'It is your sibling’s birthday. What can you do to make the celebration happy?',a:'Batiin siya, tumulong sa paghahanda, at makisaya kasama ang pamilya.',ae:'Greet them, help prepare, and celebrate with the family.',hint:'Mag-isip ng isang mabuting paraan ng pagtulong.'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'open',q:'May dumating na bisita sa inyong bahay. Ano ang magalang na dapat mong gawin?',en:'A visitor arrives at your home. What should you politely do?',a:'Batiin at tanggapin ang bisita nang magalang.',ae:'Greet and welcome the visitor politely.',hint:'Ipakita ang pagiging magiliw.'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'open',q:'Nakikita mong nagmamano si Ate sa inyong lolo. Bakit niya ito ginagawa?',en:'You see your older sister doing pagmamano to your grandfather. Why does she do it?',a:'Upang magpakita ng paggalang sa nakatatanda.',ae:'To show respect to an elder.',hint:'Ito ay isang tradisyon ng paggalang.'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'open',q:'Bumisita ang inyong pamilya sa libingan ng isang mahal ninyo sa buhay. Ano ang maaari ninyong gawin?',en:'Your family visits the grave of a loved one. What can you do?',a:'Magdala ng bulaklak, magsindi ng kandila, at manalangin o magbigay-galang.',ae:'Bring flowers, light a candle, and pray or pay respects.',hint:'Ito ay paraan ng pag-alala sa yumao.'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'choice',q:'Si Liza ay Muslim. Ipinagdiriwang ng kaniyang pamilya ang Eid’l Fitr. Ano ang dapat nating gawin?',en:'Liza is Muslim. Her family celebrates Eid’l Fitr. What should we do?',choices:['Igalang ang kaniyang pagdiriwang','Tawanan ang kaniyang tradisyon','Sabihing mali ang kanilang pagdiriwang'],a:'Igalang ang kaniyang pagdiriwang',ae:'Respect her celebration.',hint:'Mahalaga ang paggalang sa iba’t ibang pamilya at tradisyon.'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'choice',q:'Sa Pasko, nagtitipon ang pamilya para sa Noche Buena. Ano ang ipinapakita nito?',en:'At Christmas, the family gathers for Noche Buena. What does this show?',choices:['Pagkakaisa at pagsasama ng pamilya','Pag-aaway','Pag-iwas sa pamilya'],a:'Pagkakaisa at pagsasama ng pamilya',ae:'Family unity and togetherness',hint:'Ang pagsasalo-salo ay nagbubuklod sa pamilya.'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'choice',q:'Alin ang nagpapakita ng pagpapahalaga sa tradisyon?',en:'Which shows appreciation for a tradition?',choices:['Nakikilahok at tumutulong','Nananadya at naninira','Tumatangging makinig sa lahat'],a:'Nakikilahok at tumutulong',ae:'Participating and helping',hint:'Ang mabuting pakikilahok ay nagpapakita ng pagpapahalaga.'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'open',q:'Ano ang isang tradisyon ng inyong pamilya na gusto mong ipagpatuloy? Bakit?',en:'What is one family tradition you want to continue? Why?',a:'Sariling sagot ng mag-aaral basta malinaw na tradisyon ito at may makatuwirang dahilan.',ae:'Student’s own answer, as long as it is a family tradition with a reasonable explanation.',hint:'Maaaring banggitin ang Pasko, kaarawan, pagmamano, pagsasalo-salo, o iba pa.'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'open',q:'Paano nakatutulong ang mga pagdiriwang sa pagbubuklod ng pamilya?',en:'How do celebrations help strengthen family bonds?',a:'Nagbibigay ito ng pagkakataon na magsama-sama, mag-usap, tumulong, at magsaya ang pamilya.',ae:'They give the family opportunities to be together, talk, help, and enjoy time together.',hint:'Ano ang ginagawa ng pamilya kapag nagsasama-sama?'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'open',q:'Kung may kaklase kang may ibang tradisyon, paano mo siya pakikitunguhan?',en:'If a classmate has a different tradition, how will you treat them?',a:'Igagalang ko siya at ang kaniyang tradisyon.',ae:'I will respect the classmate and their tradition.',hint:'Ang pagkakaiba ay dapat igalang.'},
 {cat:'ISIPIN AT SAGUTIN',diff:'Mahirap',type:'open',q:'Bakit dapat ipagpatuloy ang mabubuting tradisyon ng pamilya?',en:'Why should good family traditions be continued?',a:'Dahil pinahahalagahan nito ang pamilya, paggalang, pagmamahalan, at pagkakaisa.',ae:'Because they value family, respect, love, and unity.',hint:'Isipin ang mabuting naidudulot nito sa pamilya.'}
];

let index=0, score=0, streak=0, answered=false, soundOn=true;
const $=id=>document.getElementById(id);
const state={missed:[]};

function shuffle(arr){return [...arr].sort(()=>Math.random()-.5)}
function speak(text){if(!soundOn||!('speechSynthesis' in window))return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang='fil-PH';u.rate=.9;speechSynthesis.speak(u)}
function render(){
  const q=questions[index]; answered=false;
  $('questionNumber').textContent=String(index+1).padStart(2,'0');
  $('progressText').textContent=`Tanong ${index+1} sa ${questions.length}`;
  const pct=Math.round(((index+1)/questions.length)*100);$('percentText').textContent=pct+'%';$('progressFill').style.width=pct+'%';
  $('categoryPill').textContent=q.cat;$('difficulty').textContent=q.diff;$('roundBadge').textContent=index<10?'Round 1':index<20?'Round 2':'Round 3';
  $('questionText').textContent=q.q;$('questionEnglish').textContent=q.en;$('hintText').textContent=q.hint;$('hintEnglish').textContent='Hint: '+q.hint;$('answerText').textContent=q.a;$('answerEnglish').textContent=q.ae;
  $('answerBox').classList.add('hidden');
  const choices=$('choices');choices.innerHTML='';
  if(q.type==='choice'){
    shuffle(q.choices).forEach(c=>{const b=document.createElement('button');b.className='choice';b.type='button';b.textContent=c;b.onclick=()=>selectChoice(b,c);choices.appendChild(b)});
  } else {
    const note=document.createElement('div');note.className='open-note';note.innerHTML='<strong>🎤 Oral na Sagot</strong><p>Makinig sa sagot ng mag-aaral. Walang kailangang i-type.</p><p class="english-text">Oral answer: listen to the student’s response. No typing is needed.</p>';choices.appendChild(note);
  }
  document.querySelectorAll('.map-item').forEach((el,i)=>el.classList.toggle('active',(index<10&&i===0)||(index>=10&&index<20&&i===1)||(index>=20&&i<30&&i===2)));
}
function selectChoice(btn,c){if(answered)return; document.querySelectorAll('.choice').forEach(x=>x.disabled=true); if(c===questions[index].a){btn.classList.add('correct');showToast('Tamang sagot! Maaari nang markahan bilang Tama.','good');}else{btn.classList.add('wrong');showToast('Subukan munang pag-isipan ang clue.','warn');} reveal();}
function reveal(){ $('answerBox').classList.remove('hidden'); speak(questions[index].a); }
function mark(correct){
 if(answered){showToast('Na-markahan na ang tanong na ito.','warn');return}
 answered=true;
 if(correct){score++;streak++;showToast(streak>=3?'🔥 Mahusay! Tuloy-tuloy ang streak!':'✓ Tama!','good');}
 else{streak=0;if(!state.missed.includes(index))state.missed.push(index);showToast('💡 Ayos lang! Magpatuloy tayo.','warn');}
 $('scoreDisplay').textContent=`${score} / ${questions.length}`;$('streakDisplay').textContent=streak+' 🔥';reveal();
 setTimeout(()=>{if(index<questions.length-1){index++;render();}else finish();},650);
}
function finish(){
 $('questionCard').classList.add('hidden');$('celebrateCard').classList.remove('hidden');$('finalScore').textContent=`${score} / ${questions.length}`;
 const pct=Math.round(score/questions.length*100); $('finalTitle').textContent=pct>=90?'🏆 Recitation Master!':pct>=75?'⭐ Napakahusay!':pct>=60?'👏 Magaling!':'💪 Ipagpatuloy ang Pagsasanay!'; $('finalMessage').textContent=`Nakakuha ka ng ${pct}%. ${state.missed.length?`May ${state.missed.length} tanong na maaari pang sanayin.`:'Napakahusay—naipakita mo ang iyong pag-unawa sa aralin!'}`;
 const name=$('studentName').value.trim()||'Mag-aaral';saveScore(name,score);renderScores();
}
function resetGame(){index=0;score=0;streak=0;state.missed=[];$('scoreDisplay').textContent='0 / 30';$('streakDisplay').textContent='0 🔥';$('celebrateCard').classList.add('hidden');$('scoreboardCard').classList.add('hidden');$('questionCard').classList.remove('hidden');render();window.scrollTo({top:0,behavior:'smooth'})}
function randomQuestion(){let n=Math.floor(Math.random()*questions.length);if(n===index)n=(n+1)%questions.length;index=n;render();showToast('🎲 Bagong random na tanong!','good')}
function skip(){if(index<questions.length-1){index++;render();showToast('⏭ Nilaktawan. Walang puntos.','warn')}else finish()}
function saveScore(name,s){const data=JSON.parse(localStorage.getItem('teacherEdAP1Scores')||'[]');data.unshift({name,score:s,total:30,date:new Date().toLocaleString('fil-PH')});localStorage.setItem('teacherEdAP1Scores',JSON.stringify(data.slice(0,20)))}
function renderScores(){const data=JSON.parse(localStorage.getItem('teacherEdAP1Scores')||'[]');const box=$('scoreList');box.innerHTML='';if(!data.length){box.innerHTML='<div class="score-empty">Wala pang record.</div>';return}data.forEach(x=>{const row=document.createElement('div');row.className='score-row';row.innerHTML=`<strong>${escapeHtml(x.name)}</strong><strong>${x.score}/${x.total}</strong><span>${escapeHtml(x.date)}</span>`;box.appendChild(row)})}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),1800)}

$('revealBtn').onclick=reveal;$('correctBtn').onclick=()=>mark(true);$('wrongBtn').onclick=()=>mark(false);$('resetBtn').onclick=()=>{if(confirm('I-reset ang kasalukuyang recitation? Mawawala ang kasalukuyang puntos.'))resetGame()};$('retryBtn').onclick=resetGame;$('practiceBtn').onclick=()=>{index=state.missed.length?state.missed[0]:0;score=0;streak=0;$('celebrateCard').classList.add('hidden');$('questionCard').classList.remove('hidden');render()};$('randomBtn').onclick=randomQuestion;$('skipBtn').onclick=skip;$('scoreboardBtn').onclick=()=>{$('scoreboardCard').classList.toggle('hidden');renderScores();$('scoreboardCard').scrollIntoView({behavior:'smooth'})};$('clearScoresBtn').onclick=()=>{if(confirm('Burahin ang lahat ng naitalang iskor?')){localStorage.removeItem('teacherEdAP1Scores');renderScores()}};
$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊 Tunog':'🔇 Tahimik';$('soundBtn').setAttribute('aria-pressed',soundOn)};
$('englishBtn').onclick=()=>{document.body.classList.toggle('english-on');const on=document.body.classList.contains('english-on');$('englishBtn').setAttribute('aria-pressed',on);$('englishBtn').textContent=on?'EN English On':'EN English Support'};
render();
