function go(id){document.getElementById(id).scrollIntoView({behavior:'smooth'})}
function speak(t){if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=.9;speechSynthesis.speak(u)}}
const rp=[['cat 🐱','hat 🎩',1,'They end with /at/.'],['sun ☀️','fun 🎉',1,'They end with /un/.'],['ball ⚽','tall 🦒',1,'They end with /all/.'],['cake 🍰','snake 🐍',1,'They end with /ake/.'],['fish 🐟','dog 🐶',0,'Their ending sounds are different.'],['book 📚','pen ✏️',0,'Their ending sounds are different.'],['tree 🌳','car 🚗',0,'Their ending sounds are different.']];let ri=0;
function renderRhyme(){let x=rp[ri];document.getElementById('rq').innerHTML=`${x[0]} <b>+</b> ${x[1]}`;document.getElementById('rf').textContent=''}
function rhymeCheck(a){let x=rp[ri],ok=Boolean(x[2])===a,f=document.getElementById('rf');f.textContent=ok?'🌟 Correct! '+(x[2]?'They rhyme. '+x[3]:'They do not rhyme. '+x[3]):'💡 Try again. Listen to the ending sounds.';f.style.color=ok?'#347b49':'#9a5b1d'}
function nextRhyme(){ri=(ri+1)%rp.length;renderRhyme()}
const fd=[['cat 🐱',['hat 🎩','dog 🐶','sun ☀️'],0],['cake 🍰',['book 📚','snake 🐍','ball ⚽'],1],['sun ☀️',['fun 🎉','fish 🐟','car 🚗'],0],['ball ⚽',['tree 🌳','tall 🦒','pen ✏️'],1],['light 💡',['night 🌙','book 📚','apple 🍎'],0]];let fi=0;
function newFind(){let d=fd[fi%fd.length];document.getElementById('fq').innerHTML=`Which word rhymes with <b>${d[0]}</b>?`;document.getElementById('fc').innerHTML=d[1].map((x,i)=>`<button onclick="findCheck(${i})">${x}</button>`).join('');document.getElementById('ff').textContent='';fi++}
function findCheck(i){let d=fd[(fi-1)%fd.length],ok=i===d[2],f=document.getElementById('ff');f.textContent=ok?'🌟 Great job! You found the rhyming word.':'💡 Try again. Listen to the ending sound.';f.style.color=ok?'#347b49':'#9a5b1d'}
const sd=[['The cat sat on the ___.',['mat','sun','book'],0],['I like to read a ___.',['book','shoe','ball'],0],['The sun is very ___.',['bright','read','book'],0],['A fish can ___.',['swim','read','write'],0],['The teacher writes with a ___.',['pencil','cake','tree'],0]];let si=0;
function newSentence(){let d=sd[si%sd.length];document.getElementById('sq').textContent=d[0];document.getElementById('sc').innerHTML=d[1].map((x,i)=>`<button onclick="sentenceCheck(${i})">${x}</button>`).join('');document.getElementById('sf').textContent='';si++}
function sentenceCheck(i){let d=sd[(si-1)%sd.length],ok=i===d[2],f=document.getElementById('sf');f.textContent=ok?'✅ Correct! The sentence makes sense.':'💡 Think about which word makes sense in the sentence.';f.style.color=ok?'#347b49':'#9a5b1d'}
const mainText='Pencils are useful in school. We use pencils to write, draw, and complete our work.';
function mainCheck(ok){let f=document.getElementById('mf');f.textContent=ok?'🌟 Correct! The main idea is that pencils are useful for school work.':'💡 Look at all the things pencils help us do.';f.style.color=ok?'#347b49':'#9a5b1d'}
function detect(ok){let f=document.getElementById('df');f.textContent=ok?'🌟 Correct! The book teaches Mia about plants.':'💡 Read the last sentence again.';f.style.color=ok?'#347b49':'#9a5b1d'}
function saveWork(id,msg){let v=document.getElementById(id).value.trim(),m=document.getElementById(msg);if(v){localStorage.setItem('jungle_'+id,v);m.textContent='Saved on this device! 🌿'}else m.textContent='Please write something first.'}
function complete(){document.getElementById('done').textContent='🎉 Amazing work! You completed your Connect to Reading mission!';speak('Amazing work! You completed your Connect to Reading mission!')}
window.addEventListener('DOMContentLoaded',()=>{renderRhyme();newFind();newSentence();for(let i=1;i<=5;i++){let v=localStorage.getItem('jungle_g'+i);if(v)document.getElementById('g'+i).value=v}});