const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={stage:0, stars:0, sound:true, completed:new Set(), practiceLevel:'easy', practiceIndex:0, practiceScore:0, checkIndex:0, checkScore:0, masterScore:0};
const stageNames=['Engage','Connect','Explore','Learn','Guided Practice','Practice','Think','Review','Check','Master','Reflect','Celebrate'];
const games=[
 {name:'Luksong Tinik',icon:'🦶',clue:'Tumalon sa ibabaw ng mga kamay o paa ng nakaupong manlalaro.',how:'May “tinik” na binubuo ng kamay o paa. Unti-unting tumataas ang harang habang tumatagal ang laro.'},
 {name:'Tumbang Preso',icon:'🥫',clue:'Patumbahin ang isang lata gamit ang tsinelas.',how:'May “taya” na nagbabantay sa lata. Kapag natamaan ang lata, kailangang bumalik ang mga manlalaro sa kanilang puwesto ayon sa tuntunin ng laro.'},
 {name:'Patintero',icon:'✏️',clue:'Tumawid sa mga guhit habang iniiwasan ang taya.',how:'Dalawang pangkat ang naglalaro. May mga guhit na nagsisilbing hangganan at may mga taya na humaharang sa mga manlalarong tumatawid.'},
 {name:'Piko',icon:'🪨',clue:'Tumalon sa mga kahon na iginuhit sa lupa.',how:'Dalawa o higit pang manlalaro ang maaaring sumali. May bato o pamato at mga kahong paglalagyan ng paa habang umuusad.'}
];
const practice={easy:[
 ['Aling laro ang gumagamit ng “tinik” na binubuo ng kamay o paa?',['Piko','Luksong Tinik','Patintero','Tumbang Preso'],1],
 ['Aling laro ang gumagamit ng lata at tsinelas?',['Patintero','Piko','Tumbang Preso','Luksong Tinik'],2],
 ['Saang laro may mga guhit na kailangang tawirin habang iniiwasan ang taya?',['Patintero','Piko','Luksong Tinik','Game of the Generals'],0],
 ['Aling laro ang may mga kahong iginuguhit sa lupa?',['Tumbang Preso','Patintero','Piko','Luksong Tinik'],2],
 ['Ano ang tawag sa larong gumagamit ng pamato at mga kahon?',['Piko','Patintero','Tumbang Preso','Luksong Tinik'],0]],
developing:[
 ['Kung may batang tumatalon sa ibabaw ng kamay ng nakaupong manlalaro, anong laro ito?',['Patintero','Piko','Luksong Tinik','Tumbang Preso'],2],
 ['May isang lata na binabantayan ng taya. Anong laro ang malamang na nilalaro?',['Tumbang Preso','Piko','Patintero','Luksong Tinik'],0],
 ['Ang layunin ng pangkat ay makatawid sa mga guhit nang hindi nahuhuli ng taya. Anong laro?',['Piko','Patintero','Tumbang Preso','Game of the Generals'],1],
 ['Alin ang pinakaangkop na clue para sa Piko?',['Lata at tsinelas','Mga kahon at pamato','Bandila at ranggo','Tinik na kamay'],1],
 ['Bakit maaaring magkaiba ang paraan ng paglalaro ng isang larong Pilipino sa dalawang pamayanan?',['Dahil may iba’t ibang bersiyon','Dahil hindi ito laro','Dahil bawal ang laro','Dahil iisa lang ang paraan'],0]],
challenge:[
 ['Aling pahayag ang sinusuportahan ng aralin?',['Iisa lang ang bersiyon ng bawat laro.','May iba’t ibang bersiyon ng mga larong Pilipino sa iba’t ibang pamayanan.','Lahat ng laro ay banyaga.','Walang kaugnayan ang laro sa kultura.'],1],
 ['Aling halimbawa ang malinaw na larong Pilipino na inilarawan sa aralin?',['Chess lamang','Luksong Tinik','Basketball lamang','Video game lamang'],1],
 ['Ano ang ipinakikita ng pagkakaroon ng iba’t ibang bersiyon ng laro?',['Magkakaiba ang paraan ng paglalaro sa mga pamayanan.','Hindi mahalaga ang kultura.','Pare-pareho ang lahat ng pamayanan.','Hindi maaaring matutuhan ang laro.'],0],
 ['Ano ang layunin ng Game of the Generals ayon sa lesson source?',['Makadakip ng bandila ng kalaban.','Makapagtayo ng lata.','Makalukso sa tinik.','Makatawid sa guhit.'],0],
 ['Alin ang HINDI kabilang sa apat na larong tinalakay sa pp. 175–177?',['Piko','Patintero','Tumbang Preso','Game of the Generals'],3]]};
const check=[
 ['Ano ang larong gumagamit ng “tinik”?',['Luksong Tinik','Piko','Patintero','Tumbang Preso'],0],
 ['Ano ang ginagamit upang patumbahin ang lata sa Tumbang Preso?',['Pamato','Tsinelas','Guhit','Bandila'],1],
 ['Ano ang mahalagang bahagi ng Patintero?',['Mga guhit at taya','Lata at tsinelas','Kahon at pamato','Bandila at ranggo'],0],
 ['Ano ang ginagamit sa Piko upang markahan ang paglalaro?',['Lata','Pamato at mga kahon','Bandila','Tsinelas lamang'],1],
 ['Tama o Mali: Iisa lamang ang bersiyon ng larong Pilipino sa buong bansa.',['Tama','Mali'],1],
 ['Alin ang inimbento ni Sofronio Pasola, Jr. kasama ang anak niyang si Ronnie?',['Patintero','Piko','Game of the Generals','Luksong Tinik'],2],
 ['Bakit mahalagang kilalanin ang mga larong Pilipino?',['Upang pahalagahan ang kultura','Upang palitan lahat ng laro','Upang hindi na maglaro','Upang gawing pare-pareho ang lahat'],0],
 ['Ano ang pangunahing inaasahang matutuhan sa aralin?',['Makilala at mapahalagahan ang mga larong Pilipino','Makabisado ang lahat ng laro sa mundo','Matutong mag-code','Matutong magbilang'],0]
];
const warmups=[
 ['🦶','May tumatalon sa ibabaw ng nakaupong mga manlalaro.',['Luksong Tinik','Piko','Patintero','Tumbang Preso'],0],
 ['🥫','May lata at tsinelas; may taya na nagbabantay.',['Piko','Tumbang Preso','Patintero','Luksong Tinik'],1],
 ['✏️','May mga guhit at may taya na humaharang sa mga tumatawid.',['Patintero','Piko','Tumbang Preso','Luksong Tinik'],0],
 ['🪨','May mga kahon sa lupa at pamato.',['Tumbang Preso','Luksong Tinik','Piko','Patintero'],2]
];
function beep(ok=true){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;const c=new C();const o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?660:220;o.connect(g);g.connect(c.destination);g.gain.value=.03;o.start();o.stop(c.currentTime+.08)}catch(e){}}
function renderSteps(){const el=$('#steps');el.innerHTML=stageNames.map((n,i)=>`<button class="step ${i===state.stage?'active':''} ${state.completed.has(i)?'done':''}" data-stage="${i}">${i+1}. ${n}</button>`).join('');$$('.step').forEach(b=>b.onclick=()=>goStage(+b.dataset.stage));$('#progressLabel').textContent=`${state.completed.size} / 12`}
function markStage(i){if(!state.completed.has(i)){state.completed.add(i);state.stars+=1;}renderSteps();updateFinal()}
function goStage(i){state.stage=i;const target=document.querySelector(`[data-stage="${i}"]`);if(target)target.scrollIntoView({behavior:'smooth',block:'start'});renderSteps()}
function bindGo(){ $$('[data-go]').forEach(b=>b.onclick=()=>{const id=b.dataset.go; if(id==='home')window.scrollTo({top:0,behavior:'smooth'}); else document.getElementById(id==='map'?'map':'stage-'+id).scrollIntoView({behavior:'smooth'})}) }
function choiceButton(text,index,handler){const b=document.createElement('button');b.className='choice';b.textContent=text;b.onclick=()=>handler(b,index);return b}
let wi=0;
function renderWarmup(){const q=warmups[wi];$('#warmupVisual').innerHTML=`<div class="big-emoji">${q[0]}</div><div class="clue">${q[1]}</div>`;const box=$('#warmupChoices');box.innerHTML='';q[2].forEach((x,i)=>box.appendChild(choiceButton(x,i,(b,idx)=>{if(box.dataset.done)return;box.dataset.done='1';if(idx===q[3]){b.classList.add('correct');$('#warmupFeedback').innerHTML='🎉 Tama! Mahusay ang obserbasyon mo.';beep(true);state.stars+=2}else{b.classList.add('wrong');$('#warmupFeedback').innerHTML='💡 Halos! Tingnan ang clue at subukan muli sa susunod.';beep(false)}$('#warmupNext').hidden=false})));$('#warmupNext').textContent=wi<warmups.length-1?'➡️ Susunod na Clue':'🎯 Tapos na!';}
$('#warmupNext').onclick=()=>{if(wi<warmups.length-1){wi++;$('#warmupFeedback').textContent='';$('#warmupNext').hidden=true;$('#warmupChoices').dataset.done='';renderWarmup()}else{markStage(0);goStage(1)}};renderWarmup();
$$('[data-connect]').forEach(b=>b.onclick=()=>{$('#connectFeedback').textContent=`👍 Magandang koneksiyon! Ang mga laro ay bahagi ng karanasan ng mga bata sa pamayanan. Pinili mo: ${b.textContent.replace(/^\S+\s/,'')}`;markStage(1);setTimeout(()=>goStage(2),450)});
$('#gameCards').innerHTML=games.map((g,i)=>`<div class="game-tile" data-game="${i}"><div class="game-inner"><div class="face front"><div class="tile-icon">${g.icon}</div><h3>${g.name}</h3><small>Tap to discover</small></div><div class="face back"><h3>${g.name}</h3><p>${g.clue}</p><small>${g.how}</small></div></div></div>`).join('');$$('.game-tile').forEach(c=>c.onclick=()=>{c.classList.toggle('flipped');if($$('.game-tile.flipped').length>=4){markStage(2);setTimeout(()=>goStage(3),450)}});
function initGuided(){const qs=[['May lata at tsinelas. Anong laro?',['Piko','Tumbang Preso','Patintero'],1,'Isipin ang larong may binabantayang lata.'],['May mga guhit at taya na humaharang.',['Piko','Patintero','Luksong Tinik'],1,'Isipin ang larong tumatawid sa mga guhit.'],['May mga kahon at pamato.',['Tumbang Preso','Piko','Luksong Tinik'],1,'Isipin ang larong may mga kahon sa lupa.'],['May “tinik” na kamay o paa.',['Patintero','Luksong Tinik','Piko'],1,'Isipin ang larong tumatalon sa ibabaw ng nakaupong manlalaro.']];let i=0;function draw(){const q=qs[i];$('#guidedQuestion').textContent=q[0];$('#guidedChoices').innerHTML='';$('#guidedHintBox').classList.remove('show');$('#guidedFeedback').textContent='';$('#guidedNext').hidden=true; q[1].forEach((x,idx)=>$('#guidedChoices').appendChild(choiceButton(x,idx,(b,n)=>{if($('#guidedChoices').dataset.done)return;$('#guidedChoices').dataset.done='1';if(n===q[2]){b.classList.add('correct');$('#guidedFeedback').textContent='🏆 Tama! Kaya mo na ito.';state.stars+=1;beep(true)}else{b.classList.add('wrong');$('#guidedFeedback').textContent='💡 Halos! Gamitin ang hint at subukan muli.';beep(false)}$('#guidedNext').hidden=false})));$('#guidedChoices').dataset.done=''}$('#guidedHint').onclick=()=>{$('#guidedHintBox').textContent=qs[i][3];$('#guidedHintBox').classList.add('show')};$('#guidedNext').onclick=()=>{if(i<qs.length-1){i++;draw()}else{markStage(4);goStage(5)}};draw()}
initGuided();
$('#learnDone').onclick=()=>{markStage(3);goStage(4)};
function initPractice(){let data=practice[state.practiceLevel];$('#practiceCount').textContent=`${state.practiceIndex+1} / ${data.length}`;$('#practiceScore').textContent=`⭐ ${state.practiceScore}`;const q=data[state.practiceIndex];$('#practiceQuestion').textContent=q[0];$('#practiceChoices').innerHTML='';$('#practiceFeedback').textContent='';$('#practiceNext').hidden=true;data[state.practiceIndex][1].forEach((x,i)=>$('#practiceChoices').appendChild(choiceButton(x,i,(b,n)=>{if($('#practiceChoices').dataset.done)return;$('#practiceChoices').dataset.done='1';if(n===q[2]){b.classList.add('correct');$('#practiceFeedback').textContent='🎉 Excellent!';state.practiceScore++;state.stars++;beep(true)}else{b.classList.add('wrong');$('#practiceFeedback').textContent='💡 Balikan ang clue at subukan ang susunod.';beep(false)}$('#practiceScore').textContent=`⭐ ${state.practiceScore}`;$('#practiceNext').hidden=false})));$('#practiceChoices').dataset.done=''}
$$('.level').forEach(b=>b.onclick=()=>{state.practiceLevel=b.dataset.level;state.practiceIndex=0;state.practiceScore=0;$$('.level').forEach(x=>x.classList.remove('active'));b.classList.add('active');initPractice()});$('#practiceNext').onclick=()=>{const len=practice[state.practiceLevel].length;if(state.practiceIndex<len-1){state.practiceIndex++;initPractice()}else{markStage(5);goStage(6)}};initPractice();
$$('.think-btn').forEach(b=>b.onclick=()=>{b.nextElementSibling?.remove();const p=document.createElement('p');p.className='eng-support';p.textContent=b.dataset.answer;b.parentNode.appendChild(p);$('#thinkFeedback').textContent='💡 Magandang pag-iisip! Tandaan ang gabay at ipaliwanag ito sa klase.';markStage(6);setTimeout(()=>goStage(7),650)});$$('.think-choice').forEach(b=>b.onclick=()=>{$('#thinkFeedback').textContent='⭐ Magandang paraan! Ang mahalaga ay kilalanin at pahalagahan ang mga larong Pilipino.';markStage(6);setTimeout(()=>goStage(7),650)});
const review=[['🇵🇭 Larong Pilipino','Bahagi ng kultura o larong nagmula sa ibang bansa.'],['🦶 Luksong Tinik','Tumalon sa ibabaw ng “tinik” na kamay o paa.'],['🥫 Tumbang Preso','Patumbahin ang lata gamit ang tsinelas.'],['✏️ Patintero','Tumawid sa mga guhit habang iniiwasan ang taya.'],['🪨 Piko','Gumamit ng pamato at mga kahon.'],['🏘️ Iba’t ibang bersiyon','May iba’t ibang paraan ng paglalaro sa mga pamayanan.']];$('#reviewStrip').innerHTML=review.map(x=>`<div class="review-item"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');const reviewBtn=document.createElement('button');reviewBtn.className='primary';reviewBtn.textContent='✅ Natapos ko ang Review';reviewBtn.onclick=()=>{markStage(7);goStage(8)};$('#reviewStrip').appendChild(reviewBtn);
function initCheck(){const q=check[state.checkIndex];$('#checkCount').textContent=`${state.checkIndex+1} / ${check.length}`;$('#checkScore').textContent=`🎯 ${state.checkScore}`;$('#checkQuestion').textContent=q[0];$('#checkChoices').innerHTML='';$('#checkFeedback').textContent='';$('#checkNext').hidden=true;q[1].forEach((x,i)=>$('#checkChoices').appendChild(choiceButton(x,i,(b,n)=>{if($('#checkChoices').dataset.done)return;$('#checkChoices').dataset.done='1';if(n===q[2]){b.classList.add('correct');$('#checkFeedback').textContent='🎉 Correct!';state.checkScore++;state.stars+=2;beep(true)}else{b.classList.add('wrong');$('#checkFeedback').textContent='💡 Almost! Balikan ang konsepto at tingnan ang tamang ideya.';beep(false)}$('#checkScore').textContent=`🎯 ${state.checkScore}`;$('#checkNext').hidden=false})));$('#checkChoices').dataset.done=''}$('#checkNext').onclick=()=>{if(state.checkIndex<check.length-1){state.checkIndex++;initCheck()}else{markStage(8);goStage(9)}};initCheck();
const masterData=[['Tumalon sa ibabaw ng kamay o paa','Luksong Tinik'],['Patumbahin ang lata gamit ang tsinelas','Tumbang Preso'],['Tumawid sa mga guhit habang iniiwasan ang taya','Patintero'],['Gumamit ng pamato at mga kahon','Piko']];$('#masterItems').innerHTML=masterData.map((x,i)=>`<div class="master-row"><span>${i+1}. ${x[0]}</span><select data-master="${i}"><option value="">Piliin</option>${games.map(g=>`<option>${g.name}</option>`).join('')}</select></div>`).join('');$$('[data-master]').forEach(s=>s.onchange=()=>{const vals=$$('[data-master]').map(x=>x.value);state.masterScore=vals.reduce((n,v,i)=>n+(v===masterData[i][1]?1:0),0);$('#masterResult').textContent=`🔎 ${state.masterScore}/4 clues solved.`;if(vals.every(Boolean)){if(state.masterScore===4){$('#masterResult').textContent='🏆 PERFECT! Na-unlock mo ang Master Badge!';state.stars+=5;beep(true)}else $('#masterResult').textContent+=' Balikan ang isang clue at ayusin ang sagot.';if(state.masterScore===4){markStage(9);setTimeout(()=>goStage(10),650)}}});
$$('.confidence button').forEach(b=>b.onclick=()=>{$$('.confidence button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#reflectFeedback').textContent='🌈 Salamat sa tapat mong reflection. Patuloy lang sa pagkatuto!';markStage(10);goStage(11)});
function updateFinal(){const completed=state.completed.size;$('#finalStars').textContent=state.stars;$('#finalCompleted').textContent=completed;$('#finalMastery').textContent=state.masterScore===4?'MASTERED':completed>=10?'READY':'IN PROGRESS'}
function celebrate(){const c=$('#confetti');c.innerHTML='';for(let i=0;i<34;i++){const x=document.createElement('i');x.style.left=Math.random()*100+'%';x.style.top=(Math.random()*-30)+'px';x.style.animationDelay=(Math.random()*1.8)+'s';x.style.transform=`rotate(${Math.random()*90}deg)`;c.appendChild(x)}updateFinal()}
$('#restartBtn').onclick=()=>location.reload();$('#muteBtn').onclick=()=>{state.sound=!state.sound;$('#muteBtn').textContent=state.sound?'🔊':'🔇'};
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const n=+e.target.dataset.stage;if(n!==11)state.stage=n;renderSteps();if(n===11){if(!state.completed.has(11))markStage(11);celebrate()}}}),{threshold:.45});$$('.stage').forEach(s=>observer.observe(s));
bindGo();renderSteps();updateFinal();
