const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='teachered_ap3_aralin6_kasaysayan_v1';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{stars:0,badges:0,bestScore:0,done:{},practiceMistakes:[]};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function award(n=1){state.stars+=n;updateStats();save();}
function badge(){state.badges=Math.min(6,state.badges+1);updateStats();save();}
function complete(id){if(!state.done[id]){state.done[id]=true;award(1);}}
function updateStats(){ $('#starCount').textContent=state.stars;$('#badgeCount').textContent=state.badges;$('#bestScore').textContent=state.bestScore+'%';const total=Object.keys(progressIds).length, done=Object.values(progressIds).filter(x=>state.done[x]).length;const pct=Math.round(done/total*100);$('#progressText').textContent=pct+'%';$('#progressBar').style.width=pct+'%';$$( '.journey-dock button').forEach(b=>b.classList.toggle('active',state.done[b.dataset.go.slice(1)]));}
const progressIds={connect:'connect',learn:'learn',model:'model',practice:'practice',games:'games',apply:'apply',mastery:'mastery'};
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1700)}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.go)?.scrollIntoView({behavior:'smooth',block:'start'})));
$('#continueBtn').onclick=()=>{const ids=['connect','learn','model','practice','games','apply','mastery'];const next=ids.find(id=>!state.done[id])||'mastery';document.getElementById(next).scrollIntoView({behavior:'smooth'});};
$('#menuBtn').onclick=()=>{const n=$('#mainNav');n.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',n.classList.contains('open'));};
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&progressIds[e.target.id]){$$('.journey-dock button').forEach(b=>b.classList.toggle('active',b.dataset.go==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55% 0px'});Object.keys(progressIds).forEach(id=>observer.observe(document.getElementById(id)));

const connectOpts=[['Old family photo','good'],['New notebook bought today','try'],['A random guess','try'],['Birthday card from the event','good']];
$('#connectChoices').innerHTML=connectOpts.map(x=>`<button data-a="${x[1]}">${x[0]}</button>`).join('');
$$('#connectChoices button').forEach(b=>b.onclick=()=>{const good=b.dataset.a==='good';$('#connectFeedback').textContent=good?'🌟 Tama! Ang larawan o card na kaugnay sa pangyayari ay maaaring maging ebidensiya.':'💡 Mag-isip ng bagay na direktang kaugnay sa pangyayaring nais nating malaman.';$('#connectFeedback').className='feedback '+(good?'good':'try');if(good){complete('connect');toast('Great thinking!')}});

const learnChecks={history:['Mga pangyayari sa nakaraan','Mga bagay na mangyayari bukas'],evidence:['Larawan o dokumentong kaugnay ng pangyayari','Haka-haka lamang'],timeline:['Pag-aayos ng mga pangyayari ayon sa pagkakasunod-sunod','Paglalagay ng mga pangyayari nang walang ayos'],change:['Nagkaroon ng bagong kakayahan habang lumalaki','Parehong pangalan pa rin'],historians:['Mga taong nag-aaral at nangangalap ng impormasyon tungkol sa nakaraan','Mga taong nanghuhula tungkol sa hinaharap']};
$$('.check-learn').forEach(btn=>btn.onclick=()=>{const k=btn.dataset.key,box=document.querySelector(`.inline-check[data-check="${k}"]`);box.innerHTML=learnChecks[k].map((a,i)=>`<button class="mini-btn" data-c="${i}">${a}</button>`).join(' ');box.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{const good=i===0;box.innerHTML=(good?'🌟 Tama!':'💡 Balikan ang paliwanag at subukan muli.');box.style.color=good?'#18794e':'#9a6800';if(good){complete('learn');award(1)}})});

const guided=[['Larawan mula sa birthday','good'],['Isang hula ng kapitbahay','try'],['Bagong papel na walang kaugnayan','try'],['Regalong natanggap noong birthday','good']];$('#guidedChoices').innerHTML=guided.map(x=>`<button data-a="${x[1]}">${x[0]}</button>`).join('');$$('#guidedChoices button').forEach(b=>b.onclick=()=>{const good=b.dataset.a==='good';$('#guidedFeedback').textContent=good?'🌟 Magandang pagpili! Ang larawan o regalong kaugnay sa birthday ay maaaring magsilbing ebidensiya.':'💡 Hanapin ang bagay na direktang may kaugnayan sa birthday.';$('#guidedFeedback').className='feedback '+(good?'good':'try');if(good){complete('model');award(1)}});$('#guidedHint').onclick=()=>{$('#guidedHintText').textContent='💡 Hint: Isipin ang bagay na maaaring makita o maipakita upang maalala ang birthday.';$('#guidedHintText').classList.remove('hidden')};

const practice=[
 ['Ano ang kasaysayan?',['Kuwento ng mga naganap sa nakaraan','Listahan ng mga laruan','Plano para bukas','Hula sa hinaharap'],0,'Kasaysayan ay tungkol sa mga naganap sa nakaraan.'],
 ['Alin ang maaaring maging ebidensiya?',['Larawan ng pangyayari','Random na hula','Bagong bagay na walang kaugnayan','Imahinasyon lamang'],0,'Ang larawan na kaugnay sa pangyayari ay maaaring ebidensiya.'],
 ['Ano ang gamit ng timeline?',['Ipakita ang pagkakasunod-sunod ng mga pangyayari','Itago ang mga pangyayari','Pumili ng paboritong kulay','Manghula ng hinaharap'],0,'Ang timeline ay nag-aayos ng mga pangyayari ayon sa pagkakasunod-sunod.'],
 ['Sino ang historyador?',['Taong nag-aaral ng kasaysayan','Taong gumagawa ng laruan','Taong naghahalaman','Taong nagluluto'],0,'Ang historyador ay nag-aaral ng kasaysayan at nangangalap ng impormasyon at ebidensiya.'],
 ['Alin ang halimbawa ng pagbabago?',['Mas marunong ka nang magbasa ngayon','Pareho pa rin ang iyong pangalan','Pareho pa rin ang paborito mong laro','Pareho pa rin ang pangalan ng iyong pamilya'],0,'Maaaring magkaroon ng bagong kaalaman o kakayahan habang lumilipas ang panahon.'],
 ['Alin ang maaaring manatili?',['Iyong pangalan','Taas ng katawan','Bagong kakayahan','Hitsura habang lumalaki'],0,'Binanggit sa aralin na maaaring manatili ang pangalan o pagkakakilanlan.'],
 ['Ano ang maaaring itanong sa saksi?',['Ano ang nakita mo noong nangyari ito?','Ano ang mangyayari bukas?','Anong kulay ang gusto mo?','Ano ang paborito mong laro ngayon?'],0,'Ang saksi ay maaaring magbigay ng impormasyon tungkol sa nangyari.'],
 ['Ano ang magandang gawin kapag may mga pangyayaring ilalagay sa timeline?',['Ayusin ayon sa pagkakasunod-sunod','Ilagay nang sapalaran','Itago ang unang pangyayari','Piliin lamang ang pinakamasaya'],0,'Ang timeline ay tungkol sa pagkakasunod-sunod ng mga pangyayari.']
];let pi=0,pc=0;function renderPractice(){const q=practice[pi];$('#practiceNum').textContent=`${pi+1} / ${practice.length}`;$('#practiceScore').textContent=`${pc} correct`;$('#practiceQuestion').textContent=q[0];$('#practiceChoices').innerHTML=q[1].map((a,i)=>`<button data-i="${i}">${a}</button>`).join('');$('#practiceFeedback').textContent='';$('#practiceFeedback').className='feedback';$('#practiceHintText').classList.add('hidden');$('#nextPractice').classList.add('hidden');$$('#practiceChoices button').forEach(b=>b.onclick=()=>answerPractice(+b.dataset.i,b));}
function answerPractice(i,b){const q=practice[pi];$$('#practiceChoices button').forEach(x=>x.disabled=true);if(i===q[2]){b.classList.add('correct');pc++;$('#practiceFeedback').textContent='🎉 Excellent! '+q[3];$('#practiceFeedback').className='feedback good';award(1)}else{b.classList.add('incorrect');state.practiceMistakes.push({q:q[0],answer:q[1][q[2]],why:q[3]});$('#practiceFeedback').textContent='💡 Let’s think again. '+q[3];$('#practiceFeedback').className='feedback try'}complete('practice');$('#nextPractice').classList.remove('hidden')}
$('#practiceHint').onclick=()=>{$('#practiceHintText').textContent='💡 Hint: '+practice[pi][3];$('#practiceHintText').classList.remove('hidden')};$('#nextPractice').onclick=()=>{pi++;if(pi>=practice.length){toast('Practice complete!');pi=0;complete('practice');renderPractice();document.querySelector('#games').scrollIntoView({behavior:'smooth'});}else renderPractice()};renderPractice();

const detective=[['You want to remember what happened at your first birthday.',['A birthday photo','A guess','A blank sheet','A random story'],0],['You want to know who was present at the event.',['A photo from the event','A new notebook','A toy bought years later','A guess'],0],['You want to learn about an old event in the community.',['A document connected to the event','A made-up story','A random drawing','A guess'],0]];let di=0;function renderDetective(){const q=detective[di%detective.length];$('#detectiveQuestion').innerHTML=`<h3>${q[0]}</h3>`;$('#detectiveChoices').innerHTML=q[1].map((a,i)=>`<button data-i="${i}">${a}</button>`).join('');$('#detectiveFeedback').textContent='';$$('#detectiveChoices button').forEach(b=>b.onclick=()=>{const good=+b.dataset.i===q[2];$('#detectiveFeedback').textContent=good?'🔎 Case solved! Iyan ang ebidensiyang kaugnay sa pangyayari.':'💡 Hanapin ang ebidensiyang direktang may kaugnayan sa pangyayari.';$('#detectiveFeedback').className='feedback '+(good?'good':'try');if(good){award(1);di++;setTimeout(renderDetective,500)}})}renderDetective();

const timelineCorrect=['Unang kaarawan','Unang araw sa paaralan','Pagdiriwang ng Pasko kasama ang pamilya'];function initTimeline(){let arr=[...timelineCorrect].sort(()=>Math.random()-.5);$('#timelineItems').innerHTML=arr.map((t,i)=>`<div class="order-item" data-v="${t}"><strong class="ord-num">${i+1}</strong><span style="flex:1">${t}</span><button aria-label="Itaas">↑</button><button aria-label="Ibaba">↓</button></div>`).join('');$$('#timelineItems .order-item').forEach(row=>{row.querySelectorAll('button')[0].onclick=()=>move(row,-1);row.querySelectorAll('button')[1].onclick=()=>move(row,1)});$('#timelineFeedback').textContent=''}function move(row,d){const sib=d<0?row.previousElementSibling:row.nextElementSibling;if(!sib)return;d<0?row.parentNode.insertBefore(row,sib):row.parentNode.insertBefore(sib,row);$$('#timelineItems .order-item').forEach((x,i)=>x.querySelector('.ord-num').textContent=i+1)}$('#checkTimeline').onclick=()=>{const arr=$$('#timelineItems .order-item').map(x=>x.dataset.v);const ok=arr.every((x,i)=>x===timelineCorrect[i]);$('#timelineFeedback').textContent=ok?'🏆 Perfect! Naayos mo ang timeline.':'💡 Tingnan muna kung alin ang unang pangyayari, pagkatapos ay ang sumunod.';$('#timelineFeedback').className='feedback '+(ok?'good':'try');if(ok){complete('games');award(2)}};$('#resetTimeline').onclick=initTimeline;initTimeline();

const changeQs=[['Napansin mong mas marunong ka nang magbasa kaysa noong maliit ka.','Pagbabago'],['Pareho pa rin ang iyong pangalan.','Nananatili'],['Nagkaroon ka ng bagong talento.','Pagbabago'],['Ang paborito mong gawain ay pareho pa rin.','Nananatili']];let ci=0;function renderChange(){const q=changeQs[ci%changeQs.length];$('#changeQuestion').innerHTML=`<h3>${q[0]}</h3>`;$('#changeChoices').innerHTML=['Pagbabago','Nananatili'].map(a=>`<button data-v="${a}">${a}</button>`).join('');$('#changeFeedback').textContent='';$$('#changeChoices button').forEach(b=>b.onclick=()=>{const good=b.dataset.v===q[1];$('#changeFeedback').textContent=good?'🌟 Tama!':'💡 Isipin kung may bago o pareho pa rin.';$('#changeFeedback').className='feedback '+(good?'good':'try');if(good){award(1);ci++;setTimeout(renderChange,500)}})}renderChange();

const memPairs=[['Kasaysayan','Kuwento ng nakaraan'],['Ebidensiya','Impormasyon o patunay'],['Timeline','Mga pangyayari ayon sa pagkakasunod-sunod'],['Historyador','Taong nag-aaral ng kasaysayan']];let mem=[],first=null,locked=false,matched=0;function initMemory(){mem=memPairs.flatMap((p,i)=>[{id:i,text:p[0],type:'term'},{id:i,text:p[1],type:'def'}]).sort(()=>Math.random()-.5);first=null;locked=false;matched=0;$('#memoryGrid').innerHTML=mem.map((c,i)=>`<button class="memory-card" data-i="${i}">?</button>`).join('');$$('#memoryGrid .memory-card').forEach(b=>b.onclick=()=>flip(+b.dataset.i,b))}function flip(i,b){if(locked||b.classList.contains('flipped')||b.classList.contains('matched'))return;b.textContent=mem[i].text;b.classList.add('flipped');if(first===null){first=i;return}locked=true;const j=first,ok=mem[j].id===mem[i].id&&mem[j].type!==mem[i].type;setTimeout(()=>{if(ok){$$('#memoryGrid .memory-card')[j].classList.add('matched');b.classList.add('matched');matched++;award(1);$('#memoryFeedback').textContent='🧠 Match!';$('#memoryFeedback').className='feedback good';if(matched===4){complete('games');toast('Memory Master!')}}else{$$(`#memoryGrid .memory-card`)[j].textContent='?';b.textContent='?';$$('#memoryGrid .memory-card')[j].classList.remove('flipped');b.classList.remove('flipped');$('#memoryFeedback').textContent='💡 Hindi magkapareha. Balikan ang kahulugan.';$('#memoryFeedback').className='feedback try'}first=null;locked=false},450)}$('#resetMemory').onclick=initMemory;initMemory();

const bonus=[['Lumang larawan ng birthday','good'],['Hula ng kaibigan','try'],['Random na papel','try'],['Bagong laruan','try']];$('#bonusChoices').innerHTML=bonus.map(x=>`<button data-a="${x[1]}">${x[0]}</button>`).join('');$$('#bonusChoices button').forEach(b=>b.onclick=()=>{const good=b.dataset.a==='good';$('#bonusFeedback').textContent=good?'🌟 Great detective work!':'💡 Piliin ang ebidensiyang direktang kaugnay sa birthday.';$('#bonusFeedback').className='feedback '+(good?'good':'try');if(good){award(2);toast('Bonus star!')}});

$$('.scenario-btn').forEach(b=>b.onclick=()=>{const good=b.dataset.good==='true';$('#scenarioFeedback').textContent=good?'🌟 Good thinking! Ginamit mo ang ebidensiya o tamang pagkakasunod-sunod.':'💡 Subukan ang sagot na gumagamit ng ebidensiya o tamang pagkakasunod-sunod.';$('#scenarioFeedback').className='feedback '+(good?'good':'try');if(good){complete('apply');award(1)}});$$('.reflect').forEach(b=>b.onclick=()=>{$$('.reflect').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#reflectionFeedback').textContent='💛 Salamat sa iyong reflection!';$('#reflectionFeedback').className='feedback good';complete('apply')});

const final=[
 ['Ano ang kasaysayan?',['Kuwento ng mga naganap sa nakaraan','Listahan ng mga pangarap','Plano sa susunod na araw','Hula'],0,'Ang kasaysayan ay tungkol sa mga naganap sa nakaraan.'],
 ['Alin ang pinakamainam na ebidensiya para sa isang birthday event?',['Larawan mula sa birthday','Haka-haka','Bagong papel','Random na bagay'],0,'Ang larawan na kaugnay sa pangyayari ay maaaring ebidensiya.'],
 ['Ano ang ipinapakita ng timeline?',['Pagkakasunod-sunod ng pangyayari','Paboritong kulay','Mga hula','Mga laro'],0,'Ang timeline ay nag-aayos ng mga pangyayari ayon sa pagkakasunod-sunod.'],
 ['Sino ang historyador?',['Taong nag-aaral ng kasaysayan','Taong gumagawa ng laruan','Taong naglalaro','Taong nagtatanim lamang'],0,'Ang historyador ay nag-aaral at nangangalap ng impormasyon at ebidensiya tungkol sa nakaraan.'],
 ['Alin ang pagbabago?',['Nagkaroon ng bagong kakayahan','Pareho pa rin ang pangalan','Pareho pa rin ang pagkakakilanlan','Pareho pa rin ang paboritong gawain'],0,'Maaaring magkaroon ng bagong kaalaman o talento habang lumilipas ang panahon.'],
 ['Alin ang maaaring manatili?',['Pangalan','Taas','Hitsura','Bagong kasanayan'],0,'Maaaring manatili ang pangalan o pagkakakilanlan.'],
 ['Ano ang maaaring gamitin kasama ng mga saksi?',['Larawan at dokumento','Hula lamang','Imahinasyon lamang','Random na listahan'],0,'Ang mga larawan at dokumento ay maaaring maging patunay o ebidensiya.'],
 ['Kung gusto mong malaman kung ano ang ginawa mo noong bata ka, ano ang makatutulong?',['Lumang larawan o video','Hula','Bagong laruan','Walang kaugnayang papel'],0,'Maaaring makatulong ang larawan o video upang maalala ang nakaraan.'],
 ['Alin ang tamang ideya tungkol sa timeline?',['Nauna ang unang pangyayari bago ang mga sumunod','Lahat ng pangyayari ay sabay-sabay','Hindi mahalaga ang pagkakasunod-sunod','Puro hinaharap lamang'],0,'Mahalaga ang pagkakasunod-sunod sa timeline.'],
 ['Bakit mahalaga ang pag-aaral ng kasaysayan?',['Natutulungan tayo nitong malaman ang tungkol sa nakaraan','Para manghula ng lotto','Para makalimot sa mga pangyayari','Para gumawa ng random na kuwento'],0,'Tinutulungan tayo ng kasaysayan na maunawaan ang mga naganap sa nakaraan.'],
 ['Saan maaaring mangalap ng impormasyon ang historyador?',['Aklatan o museo','Sa hula lamang','Sa laruan lamang','Sa random na kuwaderno'],0,'Binanggit sa aralin ang aklatan, museo, lumang bahay, at iba pang makasaysayang lugar.'],
 ['Ano ang magandang unang hakbang sa paggawa ng timeline?',['Tukuyin ang mga pangyayari','Ilagay nang sapalaran','Itago ang unang pangyayari','Pumili ng dekorasyon'],0,'Una, tukuyin ang mga pangyayaring nais ilagay at pagkatapos ay ayusin ang mga ito.']
];let fi=0,fc=0,finalMiss=[];function renderFinal(){if(fi>=final.length){showResults();return}const q=final[fi];$('#finalNum').textContent=`${fi+1} / ${final.length}`;$('#finalScore').textContent=`${fc} correct`;$('#finalQuestion').textContent=q[0];$('#finalChoices').innerHTML=q[1].map((a,i)=>`<button data-i="${i}">${a}</button>`).join('');$('#finalFeedback').textContent='';$('#finalFeedback').className='feedback';$('#finalHintText').classList.add('hidden');$('#finalNext').classList.add('hidden');$$('#finalChoices button').forEach(b=>b.onclick=()=>answerFinal(+b.dataset.i,b))}function answerFinal(i,b){const q=final[fi];$$('#finalChoices button').forEach(x=>x.disabled=true);if(i===q[2]){b.classList.add('correct');fc++;award(2);$('#finalFeedback').textContent='🎉 Excellent! '+q[3];$('#finalFeedback').className='feedback good'}else{b.classList.add('incorrect');finalMiss.push({q:q[0],answer:q[1][q[2]],why:q[3]});$('#finalFeedback').textContent='💡 Let’s think again. '+q[3];$('#finalFeedback').className='feedback try'}$('#finalNext').classList.remove('hidden')}$('#finalHint').onclick=()=>{$('#finalHintText').textContent='💡 Hint: '+final[fi][3];$('#finalHintText').classList.remove('hidden')};$('#finalNext').onclick=()=>{fi++;renderFinal()};function showResults(){const pct=Math.round(fc/final.length*100);state.bestScore=Math.max(state.bestScore,pct);complete('mastery');if(pct>=90){badge();toast('🏆 Lesson Master!')}else if(pct>=80){badge();toast('🎯 Practice Pro!')}else{toast('⭐ Keep practicing!')}save();$('#mastery .mastery-card').classList.add('hidden');$('#results').classList.remove('hidden');$('#resultScore').textContent=pct+'%';$('#resultDetail').textContent=`Nakuha mo ang ${fc} / ${final.length} na tamang sagot.`;$('#resultAchievement').textContent=pct>=90?'🏆 Lesson Master':pct>=80?'🎯 Practice Pro':pct>=70?'⭐ Great Effort':'💡 Keep Practicing';$('#mistakesArea').classList.add('hidden');updateStats()}
function resetFinal(){fi=0;fc=0;finalMiss=[];$('#mastery .mastery-card').classList.remove('hidden');$('#results').classList.add('hidden');renderFinal()}$('#retryFinal').onclick=resetFinal;$('#mistakesBtn').onclick=()=>{const a=$('#mistakesArea');a.classList.toggle('hidden');a.innerHTML=finalMiss.length?'<h3>🔄 Practice My Mistakes</h3>'+finalMiss.map((m,i)=>`<div style="padding:10px 0;border-bottom:1px solid #dbe5f0"><strong>${i+1}. ${m.q}</strong><br>Correct answer: <b>${m.answer}</b><br><small>${m.why}</small></div>`).join(''):'<h3>🌟 Great work!</h3><p>Wala kang namiss na tanong sa final challenge.</p>'};$('#bonusBtn').onclick=()=>document.querySelector('#games').scrollIntoView({behavior:'smooth'});
$('#resetProgress').onclick=()=>{if(confirm('I-reset ang progress, stars, badges, at best mastery?')){localStorage.removeItem(KEY);location.reload()}};
updateStats();renderFinal();
